### ISSUE TITLE
PostProcessor::linkAndWriteFormulas() and PostProcessor::createAndWriteKinematicsScene() always call IWriter

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#10]
<b>What steps will reproduce the problem?</b>
1. load a 1.4 document
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
Expect no calls to IWriter::writeFormulas() or
IWriter::writeKinematicsScene(), consistent with others.

Instead PostProcessor::linkAndWriteFormulas() and
PostProcessor::createAndWriteKinematicsScene() always call writer function.

<b>Please use labels and text to provide additional information.</b>

<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=17</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
