### ISSUE TITLE
Material Tiling not exported

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#100]
<b>What steps will reproduce the problem?</b>
1. Create a simple plane
2. apply a simple texture on it
3. in MaterialEditor select that material and set &quot;Coordinates&quot;- &quot;Tiling&quot; to a number greater than &quot;1.0&quot; (example: 30.0)
4. export to DAE

- What is the expected output?
Answer: a plane with the texture repeated many and many times.

- What do you see instead?
Answer: a plane with the texture not repeated.

- What version of the product are you using?
Answer: for 3ds Max  Version: 1.3.1  Revision: 847M  Platform: x64

- On what operating system?
Answer: Windows Seven 64 bit with 3D Max 2011 x64<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=181</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
