### ISSUE TITLE
Export mesh and animated joints from Maya

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#103]
<b>What steps will reproduce the problem?</b>
1. I create a mesh skinned with 2 or more animated joints 
2. Export mesh and joints with Opencollada

<b>What is the expected output? What do you see instead?</b>
In .dae file every animated joint has its single animation, instead of there being one animation for the entire rig, and this make some problems.

<b>What version of the product are you using? On what operating system?</b>
Maya 2011 64 &amp; Opencollada 1.3.0

<b>Please provide any additional information below.</b>

<b>If possible, please provide a sample file that can be used to reproduce the</b>
<b>problem.</b>
<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=185</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
