### ISSUE TITLE
the light color and light level should be combined before export

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#105]
<b>What steps will reproduce the problem?</b>
1. setup a light with a level = 0

<b>What is the expected output? What do you see instead?</b>
exported color should be 0. 

In the extras, could be exported the color and level as in the UI.

<b>What version of the product are you using? On what operating system?</b>
MAX exporter
<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=187</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
