### ISSUE TITLE
COLLADASaxFWLPolygons.h includes non-existant header COLLADASaxFWLPolyBase.h

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#107]
Not much more to add... Here's a snippiet of the offending header:

/*^M
    Copyright (c) 2008-2009 NetAllied Systems GmbH^M
^M
        This file is part of COLLADASaxFrameworkLoader.^M
        ^M
    Licensed under the MIT Open Source License, ^M
    for details please see LICENSE file or the website^M
    http://www.opensource.org/licenses/mit-license.php^M
*/

#ifndef __COLLADASAXFWL_POLYGONS_H__
#define __COLLADASAXFWL_POLYGONS_H__

#include &quot;COLLADASaxFWLPHElement.h&quot;
#include &quot;COLLADASaxFWLPolyBase.h&quot;
.../*^M
    Copyright (c) 2008-2009 NetAllied Systems GmbH^M
^M
        This file is part of COLLADASaxFrameworkLoader.^M
        ^M
    Licensed under the MIT Open Source License, ^M
    for details please see LICENSE file or the website^M
    http://www.opensource.org/licenses/mit-license.php^M
*/

#ifndef __COLLADASAXFWL_POLYGONS_H__
#define __COLLADASAXFWL_POLYGONS_H__

#include &quot;COLLADASaxFWLPHElement.h&quot;
#include &quot;COLLADASaxFWLPolyBase.h&quot;
<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=189</p><hr/><h2>earlier comments</h2>
<p><strong>hobbes1...@gmail.com said, at 2012-06-18T16:16:40.000Z:</strong></p>
<p>Whoops, double posted code snippet...</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
