### ISSUE TITLE
Incorrect default unit, centimeters instead of meters

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#108]
<b>What steps will reproduce the problem?</b>
1. Load a file without a unit tag specified.
2. Examine the FileInfo to find the units.
3. Examine the geometry to compute the bounds.

<b>What is the expected output? What do you see instead?</b>
I expect the output to use the default units of meters as defined by the COLLADA spec. I expect the bounds of the mesh to be, in m, the value of the bounds of the vertices.

Instead, I see that the units are in cm. Because of this, when my code converts to m, the object is incorrectly scaled down. The resulting bounds are 1/100 the correct size.

<b>What version of the product are you using? On what operating system?</b>
Latest svn, r871. This appears to have been incorrectly, and without explanation, introduced in r366.

<b>Please provide any additional information below.</b>
Reverting most of (but not all) of r366 will likely fix the problem.

<b>If possible, please provide a sample file that can be used to reproduce the</b>
<b>problem.</b>
http://open3dhub.com/download/b38ea3aebcdd9a384d09615baa1011cdb8ff86040fd2921c7cfa8379c62f75e4/mapgen_terrain_1.dae
<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=190</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
