### ISSUE TITLE
Support for Maya 2013 / 3ds Max 2013

### ISSUE THREAD

**Issue by Bunkerbewohner** [KhronosGroup/OpenCOLLADA#109]
So far OpenCOLLADA only supports Maya and 3ds Max up to version 2011. However, there are already two newer versions of both programs available (2012, 2013). OpenCOLLADA cannot be installed for either one of the new versions right now.

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
