### ISSUE TITLE
COLLADAMaya -> rename to OpenCollada or OpenColladaMaya

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#11]
When searching for the OpenCollada Maya plugin in Maya / Window / Preferences 
/ Plugin manager, it shows under COLLADAMaya.

That is a bit confusing, because everywhere else (this website, file format 
etc) refers to 'OpenCollada'.

Can you please rename the plugin into OpenColladaMaya or something like that?
Thanks<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=20</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
