### ISSUE TITLE
OpenCOLLADA should preserve/expose original unique IDs for all elements

### ISSUE THREAD

**Issue by fabrobinet** [KhronosGroup/OpenCOLLADA#112]
SceneKit in Mountain Lion (the Apple framework) has an API that allow to retrieve an entity using the COLLADA UID. If OpenCOLLADA changes the uniqueID then SceneKit will have no way to honor this API.

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
