### ISSUE TITLE
3dwarehousebrowser script error

### ISSUE THREAD

**Issue by opencollada-sebastian** [KhronosGroup/OpenCOLLADA#116]
1.run 3dwarehouse browser (G3D::Browser::openBrowser())
2.click at any model in browser

Browser goes to model's page and opens dialog "Script Error", "Unable to get value of the property 'log': object is null or undefined".
Everything works as expected, but error dialog is annoying.

What version of the product are you using? On what operating system?
Svn revision 842, which is the most recent version of 3dwarehouse browser. On Windows 7 x64.

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
