### ISSUE TITLE
Support for DirectX11 shader when 2013 support complete.

### ISSUE THREAD

**Issue by vinceLightcraft** [KhronosGroup/OpenCOLLADA#118]
When exporting objects using the DirectX11 shader, record all parameters and textures used within shader into the Collada file.

For reference to DirectX11 shader and Next-Gen viewport:
http://usa.autodesk.com/adsk/servlet/pc/item?siteID=123112&id=15500357

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
