### ISSUE TITLE
Not writing relative paths for CgFX shaders on export.

### ISSUE THREAD

**Issue by vinceLightcraft** [KhronosGroup/OpenCOLLADA#119]
What steps will reproduce the problem?
Enable Relative paths and Cgfx file references, and export a Collada file of object with CgFX shader applied.

What is the expected output?
Cgfx files should be copied to output directory similar to copied textures. Collada file should have relative paths written into the .dae file.

 What do you see instead?
.dae file has absolute paths written into file instead of relative, and Cgfx files are not copied to output directory.

What version of the product are you using? On what operating system?
Maya 2011 Windows7 64-bit. OpenColladaMaya 1.3.0

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
