### ISSUE TITLE
dae23ds and dae2ogre exports empty files for a basic cylinder_colladamaya_again.dae file

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#12]
Building dae23ds and dae2ogre exe (in debug mode, svn revision r652, 
Windows 32bit, MSVC 2008)

run dae23ds cylinder_colladamaya_again.dae cylinder_colladamaya_again.3ds
and
dae2ogre cylinder_colladamaya_again.dae cylinder_colladamaya_again.ogre

results in nearly empty files.

Is export of triangle mesh, with animation not supported?
Or does the export break because of missing textures/materials in the 
original file?

Thanks,
Erwin
<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=23</p><hr/><h2>earlier comments</h2>
<p><strong>opencollada2@gmail.com said, at 2009-11-09T13:17:48.000Z:</strong></p>
<p>Hi Erwin,

the reason the mesh does not get imported is, that is instantiated via a controller
and both converters currently do not support controllers.

However, even when the geometry is instantiated directly using <instance_geometry>,
the .3ds file seems to be buggy. I will have a look at it.

Robert</p><p><strong>erwin.co...@gmail.com said, at 2009-11-09T14:41:37.000Z:</strong></p>
<p>
converting skinned skeleton animation would be very important feature: for simple 
textured meshes, people generally simply use .obj files, rather than COLLADA .dae :-)

Do you have any estimate how much work is needed to support skinned skeleton 
animation/controllers, and fix this issue (in terms of days/weeks/months)?

Thanks a lot,
Erwin
</p><p><strong>opencollada2@gmail.com said, at 2009-11-09T15:38:57.000Z:</strong></p>
<p>Yes, that is true. But please note that the dae2orge converter was originally written
as an example program for the usage of OpenCOLLADA. It is by far not feature complete.

We have not yet an estimate how much work it is needed to support this in 3ds. This
would require a further analysis of the 3ds file format.</p><p><strong>erwin.co...@gmail.com said, at 2009-11-09T16:01:22.000Z:</strong></p>
<p>
To be honest, I would rather have a binding/conversion from OpenCollada to John 
Ratcliff's MeshImport library:

MeshImport library: http://code.google.com/p/meshimport
Example how to use MeshImport: http://code.google.com/p/meshimporttest/
Docs: http://docs.google.com/View?id=d5v2g3t_18csmgsxc7
BLOG with further info: http://www.codesuppository.blogspot.com

Any way to get a skinned animated skeleton from Maya into a game engine, through 
OpenCollada would be great, and it seems John Ratcliff's MeshImport is a good 
starting point for that (and MeshImport also uses the MIT license, so you are free to 
copy the source code into your the OpenCollada project)

</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
