### ISSUE TITLE
Textures in CgFX shaders not copied to output directory on export.

### ISSUE THREAD

**Issue by vinceLightcraft** [KhronosGroup/OpenCOLLADA#120]
What steps will reproduce the problem?
Enable Relative paths, Cgfx file references, and Copy textures, export file with cgfx shader and texture.

What is the expected output? 
Texture files should be copied to output directory, as when textures used with lambert/blinn/phong/etc materials are copied.

What do you see instead?
No textures are copied to output directory with .dae.

What version of the product are you using? On what operating system?
Maya 2011 Windows7 64-bit OpenColladaMaya 1.3.0

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
