### ISSUE TITLE
Complex Cgfx shader crashes Maya 2011 on export

### ISSUE THREAD

**Issue by vinceLightcraft** [KhronosGroup/OpenCOLLADA#121]
What steps will reproduce the problem?
Use of certain shaders will cause Maya 2011 to crash before completing export.

What is the expected output? 
Standard file creation.

What do you see instead?
Incomplete .dae.

What version of the product are you using? On what operating system?
Maya 2011 Windows7 64-bit OpenColladaMaya 1.3.0

Please provide any additional information below.
Shader available at:
www.lightcrafttech.com/temp/2012_10_08/CarBodyVertexColDomeRefl.cgfx

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
