### ISSUE TITLE
Enhancement Request: Add support for Morph weights KHR extension

### ISSUE THREAD

**Issue by uklumpp** [KhronosGroup/OpenCOLLADA#122]
https://collada.org/mediawiki/index.php/Morph_weights_KHR_extension specifies how morph target values can be properly targeted fpr manipulation. This is important for animation tools that don't limit themselves to bone-based skinning, but also allow morph targets/blend shapes. Typical example is facial animation with lip syncing, where shape variations such as emotions or phonemes/visemes are implemented as morph target animation.

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
