### ISSUE TITLE
Enhancement Request: Add support for Sparse Array KHR extension

### ISSUE THREAD

**Issue by uklumpp** [KhronosGroup/OpenCOLLADA#123]
https://collada.org/mediawiki/index.php/Sparse_Array_KHR_extension specifies how arrays with lots of redundant information can be expressed in a compact fashion. This is a common problem when including morph targets/blend shapes in a COLLADA file. For example, a subtle shape variation limited to a small area on the head leads to deltas written for every vertex of the given figure. Sparse arrays allow for much less redundant data to be written.

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
