### ISSUE TITLE
Collada 1.5 viewer?

### ISSUE THREAD

**Issue by metaleap** [KhronosGroup/OpenCOLLADA#128]
(Would have asked this in the collada.org forums but they don't allow Gmail-address sign-ups. A big "Khronos WTH" moment there, but oh well... and so, here I am...)

Been looking around but couldn't find any app that's a "definite", complete, reference Collada 1.5-compliant viewer app... Used "AssImp Viewer" so far, but now noticed it does not properly support strictly-1.5 documents -- only those that, even if versioned as 1.5, would be source-identical if they were versioned as 1.4.1.

There's so many folders here in this repo, can someone tell me if an official reference Viewer is included, or available elsewhere?

Also tried to build the viewer in the ColladaDOM SourceForge project [but no such luck...](http://sourceforge.net/projects/collada-dom/forums/forum/531264/topic/6265189/index/page/1)

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
