### ISSUE TITLE
texture transparency problem 

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#13]
<b>What steps will reproduce the problem?</b>
1. Import the file in the attached .zip into 3D Studio Max.
2. Notice that transparency doesn't work as intended on the plant.
3. Select the Opacity Map and set &quot;Mono Channel Output&quot; to &quot;Alpha&quot;. 
Execute a render; this is how the model is intended to be viewed.
4. Export model using the OpenCOLLADA MAX exporter.  
5. Bring the exported model back into MAX.
6. Notice that the transparency is still incorrect.

<b>What is the expected output? What do you see instead?</b>

Transparency should look correct on model.

<b>What version of the product are you using? On what operating system?</b>

3D Studio Max 2010 x64 on Windows 7 RC.
<b>Please provide any additional information below.</b>

<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=25</p><hr/><h2>earlier comments</h2>
<p><strong>opencollada2@gmail.com said, at 2009-11-12T09:14:43.000Z:</strong></p>
<p>I could reproduce this. 

However, the "Mono Channel Output" is not supported by COLLADA. The only way to store
this would be in an extra tag. We will reorganize and improve extra tag handling in
near future. After this, preservation of Max specific data will be possible.</p><p><strong>kelley.p...@gmail.com said, at 2009-11-12T17:52:04.000Z:</strong></p>
<p>Preservation of MAX data would be nice, but I'm wondering if this could be easily
solved by just making sure that "Mono Channel Output" is set on import if opaque is
set to A_ONE.  No extra data would be required.  I don't see anyone wanting the
current behavior.</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
