### ISSUE TITLE
3D Studio Max 9 SP2 start Error code:1114

### ISSUE THREAD

**Issue by maingear** [KhronosGroup/OpenCOLLADA#131]
DLL <D:\Program Files\Autodesk\3D Studio Max\PlugIns\COLLADAMaxNew.dle> failed to initialize.
Error code:1114 - A dynamic library (DLL) initialization routine failed.

Steps taken:
1. Installed fresh 3D Studio Max 9 + SP 2
2. Started the program and quit it without any problems
3. Downloaded and ran OpenCOLLADA_3ds_Max_1.3.1_x86.msi with no errors
4. Started Max again, and the above mentioned error pops up.
5. After clicking OK Max continues to start, but the plugin is not loaded
6. Same problem after restart until plugin COLLADAMaxNew.dle is removed

What can I do?

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
