### ISSUE TITLE
Maya plugin: Exporting in the same location as the .mb and its texture will get <init_from> wrong

### ISSUE THREAD

**Issue by fcoulombe** [KhronosGroup/OpenCOLLADA#132]
reproduced in Maya2013
So if you have this directory structure
project/
       asset/
              file.mb
              file_texture.png

file has a material that uses the file_texture.png
if you export a .dae in the asset folder (with the copy texture option), i will get something like this:
 <library_images>
    <image id="mario_fire_png" name="mario_fire_png">
      <init_from>file:///C:/src/project/asset/</init_from>

if i export it in project where the texture doesn't reside, i will get
 <library_images>
    <image id="mario_fire_png" name="mario_fire_png">
      <init_from>file:///C:/src/project/file_texture.png</init_from>

I don't know if this is wanted but it seems kind of odd that the filename is not there

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
