### ISSUE TITLE
Evaluate SketchUp version in the SketchUp transparency workaround

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#14]
Since prior versions of SketchUp exported wrong values for transparency
into COLLADA files, the Max plug-in contains a workaround to fix thi son
import, evaluating the &lt;creator&gt; element and checking for &quot;Google
SketchUp&quot;. In current versions of SketchUp this seems to be fixed, therefor
the version of the creating SketchUp needs to be evaluated in the workaround.<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=26</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
