### ISSUE TITLE
Set Dummy object size

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#15]
Dummy helper node size is to small. When importing a DAE file with
OpenCollada, it get way to small, it's not even possible to see it in the
viewport unless you zoom in on it...
I'm not sure how the size of the dummy node is/should be derived or if it's
set by the unit that's used for the scene, maybe the scene boudingbox?<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=27</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
