### ISSUE TITLE
Plugin for Maya 8

### ISSUE THREAD

**Issue by victoryc** [KhronosGroup/OpenCOLLADA#150]
I read the note saying that OpenCollada binaries are available for Maya 2008 onwards. Does anybody know whether the source code would work for an earlier version, specifically, Maya 8? My plan is to take the source code and build the plugin myself. But, if the source code won't work for earlier versions of Maya, please let me know.

Thanks!

P.S. Maya 8 is not same as Maya 2008; instead, it is an earlier version released around 2006.

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
