### ISSUE TITLE
Importing a rigged figure from Poser only loads the rig. The geometry doesn't import

### ISSUE THREAD

**Issue by BrainWave3D** [KhronosGroup/OpenCOLLADA#152]
I'm using the New OpenCOLLADA for Maya (MacOSX) Beta.
Open Poser with the default Andy figure. 
File>Export Collada|RWY
Select Andy Body. (Deselect ground, lights, main camera).
Import in to Maya 2013 64-bit on IntelMac using the New OpenCOLLADA for Maya (MacOSX) Beta

> Notice only the rig appears

![Screen shot 2013-03-06 at 12 41 01 PM](https://f.cloud.github.com/assets/3791345/229435/e384f340-869e-11e2-9d50-f2b0c06f2371.png)

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
