### ISSUE TITLE
Transparency Export from Maya

### ISSUE THREAD

**Issue by tparisi** [KhronosGroup/OpenCOLLADA#153]
Using Maya2013 and the latest OpenCOLLADA exporter. Transparency doesn't seem to be getting exported. I have a blinn shader with non-zero transparency but the value of the transparency tag is always 1, no matter what the setting is inside Maya. 

See attached files. Here is the offending fragment from shader "blinn1"

            <transparent opaque="RGB_ZERO">
              <color>0.1880369 0.1880369 0.1880369 1</color>
            </transparent>
            <transparency>
              <float>1</float>
            </transparency>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
