### ISSUE TITLE
Export Collada 1.5 from 3DSMax

### ISSUE THREAD

**Issue by Lu05** [KhronosGroup/OpenCOLLADA#154]
Hey,

I´m trying to export my models from 3DSMax 2011 x64 to Collada 1.5 with the OpenCollada plugin but everytime I export something it is always in Collada 1.4.1.

Can anyone help me to export to 1.5?

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
