### ISSUE TITLE
Export specular level from Max

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#16]
The OpenCOLLADA Max plugin does not export specular level. <p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=29</p><hr/><h2>earlier comments</h2>
<p><strong>esent...@gmail.com said, at 2011-01-19T19:09:29.000Z:</strong></p>
<p>FCollada/ColladaMax plugin did it this way:
<spec_level>
<float>...</float>
<texture texture=".." texcoord="CHANNEL1"/>
</spec_level>

In OpenCollada it's like this, without the level:
<technique profile="OpenCOLLADA3dsMax">
<specularLevel>
<texture texture=".." texcoord="CHANNEL1"/>
</specularLevel>

Please add support for this, thank you!</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
