### ISSUE TITLE
Cannot dial morph target values

### ISSUE THREAD

**Issue by BrainWave3D** [KhronosGroup/OpenCOLLADA#167]
I have a simple test case created in Poser Pro.
A sphere with a custom morph.
I exported as Collada|RWY with the morph targets unbaked and imported it into Max and Maya 2013 (both Win/Mac 64 bit) using OpenCollada 1.4.0

> There's no way to adjust the morph target via the Deformer Attributes envelope. 
> I've attached a screenshot of how the Autodesk fbx/dae import allows to adjust the morph target.

Also, note this issue also occurs with the 1.3.0 plugin for Max and Maya 2011.
![Screen Shot 2013-03-26 at 6 18 32 PM](https://f.cloud.github.com/assets/3791345/306395/98a8c56a-967d-11e2-9dd2-4d429012aa2e.png)

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
