### ISSUE TITLE
Ibook 2 doesn't open format .dae

### ISSUE THREAD

**Issue by S9ava** [KhronosGroup/OpenCOLLADA#170]
Hello, i have a problem with import 3d model opencollada  in iBook.
I use 3dsmax 2012 x64 and colladamax 1.4.0
At import there is a mistake:
Has not been added, as its actives did not manage to be consolidated.

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
