### ISSUE TITLE
Can't change UP direction throu export dialogue

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#18]
Can't change UP direction throu export dialog.
(Very useful for content developing.)<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=31</p><hr/><h2>earlier comments</h2>
<p><strong>opencollada2@gmail.com said, at 2009-11-24T08:30:28.000Z:</strong></p>
<p>Will be added in future.</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
