### ISSUE TITLE
Ambiguous symbol

### ISSUE THREAD

**Issue by azzogat** [KhronosGroup/OpenCOLLADA#182]
Recently hit this snag on VS2010

namespace COLLADABU
{
    typedef std::string String;
}
in COLLADABUPrerequisites.h 

Comes up as  Error 11 error C2872: 'String' : ambiguous symbol  when used  in COLLADA2GLTFWriter.cpp 580

To be fair, although a trivial issue, typedefing std::string as String is quite ambiguous indeed.

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
