### ISSUE TITLE
OpenCOLLADA and 3ds Max 9: Error 1114

### ISSUE THREAD

**Issue by Flam1ngDem0n** [KhronosGroup/OpenCOLLADA#183]
I am trying to get OpenCOLLADA with 3ds max 9. Considering some of the games I work with still use plugins that only work with 3ds max 9, I still use it. I have installed OpenCOLLADA version 1.3.0 32-Bit for 3ds max, and I get the following error.

![2013-05-15_1343](https://f.cloud.github.com/assets/2099250/508997/d9157ab2-bd97-11e2-8077-a5ef8c9e6160.png)

This in-turn prevents me from using the Plugin. What is causing this issue?

Thanks for any help given.

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
