### ISSUE TITLE
COLLADA plugin for MAYA 2012 and later doesn`t work?

### ISSUE THREAD

**Issue by onogu** [KhronosGroup/OpenCOLLADA#184]
Hi there.

I use COLLADA MAYA plugin for export our product but cannot export Cgfx parameter.
By using latest version on MAYA2011, it has no ploblem but 2012 and later version cannot
include Cgfx parameter.

Our product are below
http://ef-12.com/

and You can download custom CgFx file below
http://ef-12.com/?page_id=435
(click 　EF12_PreviewShader4MAYA　link)

Please help me.

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
