### ISSUE TITLE
DirectX material properties not exported

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#19]
<b>What steps will reproduce the problem?</b>
1.Open 3dsMax
2. Create some object
3. Open materials dialog
4. change material type from &quot;standard&quot; to DirectX
5. change material properties.
6. assign material
7. export
8. you will see only original MAX material properties.

<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=32</p><hr/><h2>earlier comments</h2>
<p><strong>opencollada2@gmail.com said, at 2009-11-24T08:29:52.000Z:</strong></p>
<p>We will add  DirectX support in future.</p><p><strong>denis.o...@gmail.com said, at 2011-01-19T13:52:45.000Z:</strong></p>
<p>PS: I can code fix, if some one points me place in MaxAPI to watch :) it's non intuitive conserning extendent materials :\</p><p><strong>opencollada2@gmail.com said, at 2011-01-19T16:21:01.000Z:</strong></p>
<p>It would be nice if you could spend some time to code a fix.

Actually I am not an expert when Max materials are concerned, by I here are some information that might help to get into this topic.

In EffectExporter::exportSimpleEffect there is already a check if a material is a DirectX material:
        IDxMaterial* dxm = static_cast<IDxMaterial*> ( baseMaterial->GetInterface( IDXMATERIAL_INTERFACE ) );

The IDxMaterial interface seems to be the right one to retrieve data from a directX material.

I have also found the following usages of this interface in the Max SDK samples:
samples\modifiers\uvwunwrap\unwrap.cpp
samples\utilities\collector\collector.cpp
samples\utilities\mappath\mappath.cpp

These might be helpful, too. </p><p><strong>denis.o...@gmail.com said, at 2011-01-19T17:42:32.000Z:</strong></p>
<p>seems i found right peace of code: http://svn.kwxport.org/kwxport/trunk/kwxport/exportmain.cpp

lines from:
"IParamBlock2 *fxpb = materials[i].first->GetMaxMaterial()->GetParamBlock(0);"

Do you still need my help? :)</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
