### ISSUE TITLE
cmake build no longer works on windows visual studio

### ISSUE THREAD

**Issue by fcoulombe** [KhronosGroup/OpenCOLLADA#192]
make sure the build script doesn't find libxml or pcre in other locations than Externals

something to do with the external not being in the export set

>CUSTOMBUILD : CMake error : install(EXPORT "LibraryExport" ...) includes target "OpenCOLLADABaseUtils_static" which requires target "pcre" that is not in the export set.
2>CUSTOMBUILD : CMake error : install(EXPORT "LibraryExport" ...) includes target "GeneratedSaxParser_static" which requires target "xml" that is not in the export set.
2>CUSTOMBUILD : CMake error : install(EXPORT "LibraryExport" ...) includes target "OpenCOLLADASaxFrameworkLoader_static" which requires target "pcre" that is not in the export set.
2>CUSTOMBUILD : CMake error : install(EXPORT "LibraryExport" ...) includes target "OpenCOLLADASaxFrameworkLoader_static" which requires target "xml" that is not in the export set.
2>CUSTOMBUILD : CMake error : install(EXPORT "LibraryExport" ...) includes target "OpenCOLLADABaseUtils_static" which requires target "pcre" that is not in the export set.
2>CUSTOMBUILD : CMake error : install(EXPORT "LibraryExport" ...) includes target "GeneratedSaxParser_static" which requires target "xml" that is not in the export set.
2>CUSTOMBUILD : CMake error : install(EXPORT "LibraryExport" ...) includes target "OpenCOLLADASaxFrameworkLoader_static" which requires target "pcre" that is not in the export set.
2>CUSTOMBUILD : CMake error : install(EXPORT "LibraryExport" ...) includes target "OpenCOLLADASaxFrameworkLoader_static" which requires target "xml" that is not in the export set.

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
