### ISSUE TITLE
redundent line in the cmake build script

### ISSUE THREAD

**Issue by fcoulombe** [KhronosGroup/OpenCOLLADA#193]
line 41
list(APPEND CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/Externals/cmake-modules")

line 146
set(CMAKE_MODULE_PATH "${EXTERNAL_LIBRARIES}/cmake-modules")

146 is overiding the variable with what is already there

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
