### ISSUE TITLE
Geometry class has a clone function but copy constructor is private

### ISSUE THREAD

**Issue by fcoulombe** [KhronosGroup/OpenCOLLADA#196]
COLLADAFWGeometry.h

Geometry* clone() const { return new Geometry(*this); }
    private:
/** Disable default copy ctor. */
Geometry( const Geometry& pre );

it doesn't look like there's any harm in having a copy constructor but i rather leave this to someone who actually know what he's doing

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
