### ISSUE TITLE
3DS Max 2014 binaries ?

### ISSUE THREAD

**Issue by wapwork** [KhronosGroup/OpenCOLLADA#197]
Hi,

I was wondering if someone has tried to build OpenCOLLADA for 3DSMax 2014 ?
I saw on the OpenCOLLADA Tools wiki that there are binaries for 2013 but not 2014.
I will be happy to help too but my computing skills are poor.

Thanks in advance !

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
