### ISSUE TITLE
output debug binaries with suffix

### ISSUE THREAD

**Issue by fcoulombe** [KhronosGroup/OpenCOLLADA#198]
since it is not currently possible to link debug binaries with release build and release binaries with debug build... wouldn't it be nice to output the libs with a "d" suffix so that both binaries don't override each others?

this helps while developing and not having to rebuild collada with both variants every time you switch between release and debug.

an alternative would be to look into why debug can't link with release.
seems to have something to do with the debug iterator

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
