### ISSUE TITLE
Shader support in framwork and sax fwl loader

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#20]
OpenCOLLADA does not yet support the import of shaders. The should be
imported as part of the effect class.<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=33</p><hr/><h2>earlier comments</h2>
<p><strong>jhosen...@gmail.com said, at 2011-08-19T00:54:46.000Z:</strong></p>
<p>Are there any plans to implement this feature in the near future?</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
