### ISSUE TITLE
cg library version

### ISSUE THREAD

**Issue by tak3110** [KhronosGroup/OpenCOLLADA#208]
Hi.

Maya uses different version cg library.

ex.
 MAYA2012(32bit)		cg 3.0.0015(64bit)
 MAYA2012(64bit)		cg 3.0.0015(64bit)
 MAYA2013(32bit)		cg 3.1.0003(32bit)
 MAYA2013(64bit)		cg 3.1.0003(64bit)
 MAYA2014(64bit)		cg 3.1.0013(64bit)

But, Open COLLADA has a single version cg library.

ex.
externals/cg/include/

I think Open COLLADA may have some strict version cg libraries.

ex.
externals/cg/3.0.0015/include/
externals/cg/3.1.0003/include/
externals/cg/3.1.0013/include/
		:

Thanks.

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
