### ISSUE TITLE
COLLADAMax - Problems with Visual Studio project file configuration

### ISSUE THREAD

**Issue by ufoxp** [KhronosGroup/OpenCOLLADA#213]
You have pretty big mess in Visual Studio project settings, at least for 3DS MAX 2013, eg. for MSVC /VERSION can only have two numbers separated by a dot, you have three..., UNICODE macros are not present which makes 3DS MAX SDK 2013 unhappy and so on... pretty annoying :) I can fix it a little but I only have VS2012 so I'll probably be unable to propagate changes to VS2005 project files or fix compilation for older 3DS MAXes. You use some C++11 features (type inference - re-purposed "auto" keyword) so VS2005 will not compile all source files anyways... Should I bother with some more fixes and pull request for those or do you prefer this to be left intact (as some kind of IQ test ;])?

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
