### ISSUE TITLE
COLLADAFW::Mesh remaps TEXCOORD semantic to UV functions

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#22]
<b>What steps will reproduce the problem?</b>
1. COLLADAFWMesh.h and .cpp remap TEXCOORD semantic to UVCoords().
2. Mesh class appears to support UV and not texture, and cannot support both.
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
In COLLADA, texture coordinates are not the same as UV coordinates. A mesh
can have both sets of semantics. Therefore the Mesh class should provide
storage and methods for both semantics. E.g.:

Mesh::getTexCoords() [rename current interface] should return data from
&lt;input semantic=&quot;TEXCOORD&quot;&gt;.

Mesh::getUVCoords() [reimplement] should return data from &lt;input
semantic=&quot;UV&quot;&gt; and this is data that is rarely used (advanced applications
only).

<b>Please use labels and text to provide additional information.</b>
Also, each Mesh can have multiple sets of vertex attribute data. The Mesh
class currently supports only one of each semantic.

<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=39</p><hr/><h2>earlier comments</h2>
<p><strong>Marcus.C...@gmail.com said, at 2009-12-15T11:13:54.000Z:</strong></p>
<p>The code in this function is incorrect because texture coordinates cannot have
InputSemantic::UV in COLLADA:

    bool MeshLoader::loadTexCoordsSourceElement ( const InputShared& input )
    {
        bool retValue = true;

        // Get the semantic of the current input element.
        InputSemantic::Semantic semantic = input.getSemantic ();
        if ( semantic != InputSemantic::UV && semantic != InputSemantic::TEXCOORD )
        {
            std::cerr << "The current input element is not a UV / TEXCOORD element!"
<< std::endl;
            return false;
        }
</p><p><strong>Marcus.C...@gmail.com said, at 2009-12-15T11:22:41.000Z:</strong></p>
<p>This function is also wrong for the same reason.

    bool MeshLoader::loadSourceElement ( const InputShared& input )
    {
        bool retValue = false;

        // Get the semantic of the current input element.
        InputSemantic::Semantic semantic = input.getSemantic ();
        switch ( semantic )
        {
...
        case InputSemantic::UV:
        case InputSemantic::TEXCOORD:
            retValue = loadTexCoordsSourceElement ( input );
            break;
...
        }
</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
