### ISSUE TITLE
Maya Dynamics Rigid Bodies support

### ISSUE THREAD

**Issue by davidgaleano** [KhronosGroup/OpenCOLLADA#225]
It seems there is no way to export both visual and physics nodes at the same time from Maya. OpenCollada seems to only export visual nodes, whilst the Dynamica plugin only exports physics nodes. Is there any way we could combine the functionality somehow?

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
