### ISSUE TITLE
Bad management of loader object flags with external references

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#23]
<b>What steps will reproduce the problem?</b>
1. Set loader object flags as below :
        int objectFlags = 
            COLLADASaxFWL::Loader::SCENE_FLAG | 
            COLLADASaxFWL::Loader::VISUAL_SCENES_FLAG |
            COLLADASaxFWL::Loader::LIBRARY_NODES_FLAG |
            COLLADASaxFWL::Loader::GEOMETRY_FLAG |
            COLLADASaxFWL::Loader::EFFECT_FLAG |
            COLLADASaxFWL::Loader::ANIMATION_FLAG |
            COLLADASaxFWL::Loader::IMAGE_FLAG |
            COLLADASaxFWL::Loader::MATERIAL_FLAG;
        saxLoader.setObjectFlags ( objectFlags );

2. Load a document A.dae which references a node in a document B.dae
(external reference). B.dae has one &lt;library_nodes&gt; element which contains
the referenced node. A.dae does not have any &lt;library_nodes&gt; element. 

<b>What is the expected output? What do you see instead?</b>
writeLibraryNodes() should be called once when B.dae is parsed
But it is not. If saxLoader.setObjectFlags is not called, then
writeLibraryNodes is called

<b>What version of the product are you using? On what operating system?</b>
The latest trunk 

<b>Please provide any additional information below.</b>
The problem seems to come from the class variable Loader::mParsedObjectFlags.
If i reset this variable to 0 just before the parsing of the second file,
then it works

<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=41</p><hr/><h2>earlier comments</h2>
<p><strong>opencollada2@gmail.com said, at 2009-12-18T10:06:56.000Z:</strong></p>
<p>This mechanism to select which parts of a COLLADA should be loaded is not mature. It
still requires some work. However, you code should also work, if do not set these
flags. Their only purpose is to improve performance by not parsing Part that would be
ignored by your software.</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
