### ISSUE TITLE
Incorrect Data in dae files is silently dropped when validation fails

### ISSUE THREAD

**Issue by gaiaclary** [KhronosGroup/OpenCOLLADA#236]
Hi;

I have worked on a blender report about a collada file that imported objects without weight information:

https://projects.blender.org/tracker/index.php?func=detail&aid=36395&group_id=9&atid=498

In this case there where more weights defined than used. This results in silently aborting a skin controller silently, see ColladaFWValidate,line 123:
 
    if ( jointsVertexPairCount != weightIndices.getCount() )
        return false;

And this results in Blender silently importint the object without skin controller -> no weights. It took me almost a day to find the problem and i needed to debug the collada libraries for this research.

For better usability i propose to add some sort of logging here. validation failures should be reported maybe in the standard error output, or in any other convenient way. Just silently dropping items is IMHO the worst we can do here :(

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
