### ISSUE TITLE
Rotation error when importing via the OpenCollada Maya importer

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#24]
<b>What steps will reproduce the problem?</b>
2. Import test_LOD0.dae into Maya 2010 using the OpenCollada Maya importer.
3. Notice the &quot;Can't get the rotation, about we have a skew in the 
transform matrix!&quot; message in the &quot;Output Window&quot;, and notice the 
powerlines that are rotated 90 degrees relative to the correct orientation.

<b>What is the expected output? What do you see instead?</b>

1. Import test_LOD0.dae into Max 2010 using the OpenCollada Max importer.
2. Notice the powerlines look correct - the cables are properly connected 
from pole to pole.

<b>What version of the product are you using? On what operating system?</b>

OpenCollada Maya Importer 1.2.2, on Windows 7 x64.

<b>Please provide any additional information below.</b>

<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=42</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
