### ISSUE TITLE
[ColladaMax] Reflectivity

### ISSUE THREAD

**Issue by GuyGood** [KhronosGroup/OpenCOLLADA#242]
Hi guys,

I am using the OpenCollada ColladaMax Exporter 1.4.1 and I am experiencing problems with the material export. Using a standard 3dsMax Material and using a Bitmap as a reflection map, i get the texture reference in the exported dae but it does not write a "reflectivity" element. 
I read the spec and it does not say that <reflectivity> amount is required when <reflective> is used but i need the amount because even if I use a texture instead of a color, i would love to have the float value available. 

I have looked through the issues and although i think "hacking" this in is quite easy, it seems that building the plug-in is not? 

So i am writing here for 2 things: 

1) Just present you this bug. At least I think it is a bug or some enhancement

2) If anyone around here has already sucessfully build the 1.4.1 plugin for windows 3dsmax 2013 64 Bit and is more experienced, if he could "hack" this in and maybe send me the plugin? Sorry, i am not sure how much effort this takes but I thought that if VS is sucessfully configured, it would be a matter of a few minutes to export the <reflectivity> of the standard 3dsmax material. 

Anyway, thank you in advance and thanks for any help :)

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
