### ISSUE TITLE
COLLADAStreamWriter/src/COLLADASWSampler.cpp:364: possible bad if test ?

### ISSUE THREAD

**Issue by dcb314** [KhronosGroup/OpenCOLLADA#243]
I just tried to compile openCOLLADA with gcc flag -Wlogical-op

It said

OpenCOLLADA-9665d1614b027ffd7815dc745c4fab4d69eb3321/COLLADAStreamWriter/src/COLLADASWSampler.cpp:364:38: warning: logical 'or' of collectively exhaustive tests is always true [-Wlogical-op]

Source code is

        if ( mMipmapMaxlevel != 255 &&
            ( mSamplerType != SAMPLER_TYPE_1D || mSamplerType != SAMPLER_TYPE_DEPTH || mSamplerType != SAMPLER_TYPE_UNSPECIFIED ) )
            writeMipMapLevel = true;

Suggest swap || for &&

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
