### ISSUE TITLE
compiler/link error

### ISSUE THREAD

**Issue by DINmatin** [KhronosGroup/OpenCOLLADA#248]
in vs2013 for windows desktop

compiling halts at GeneratedSaxParserUtils.cpp, line: 175

size_t length = std::min(maxLen, bufferLength);

this can be fixed by substituting this line with:

size_t length; if (maxLen>bufferLength) {length = bufferLength;} else {length = maxLen;}

but how to fix the following?
Error	4	error LNK1117: syntax error in option 'VERSION:1.3.0'

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
