### ISSUE TITLE
Access to id/sid attributes of elements

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#25]
<b>What steps will reproduce the problem?</b>
1. My loader needs to retrieve the id/sid of collada elements
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
The framework classes don't seem to expose sid attributes of elements after
parsing. This is a change compared to FCollada API which stores ids and
sids in the framework classes. In OpenCollada, the sids seem to be stored
in the class SidTreeNode (see class DocumentProcessor and FileLoader) but
the information is lost during post-processing stage because the class
FileLoader is destroyed after the file is loaded.

<b>What version of the product are you using? On what operating system?</b>
the latest trunk

<b>Please provide any additional information below.</b>
<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=43</p><hr/><h2>earlier comments</h2>
<p><strong>opencollada2@gmail.com said, at 2009-12-18T13:12:48.000Z:</strong></p>
<p>The id of elements is provided as "originalId".

We will add an option to load sid. This will be configurable using a pre processor flag.
However, the only application for we see for this is extra data that references
elements via sid. Do you have any other applications?</p><p><strong>christop...@gmail.com said, at 2009-12-18T14:10:56.000Z:</strong></p>
<p>2 use cases :

1/ <extra> that references elements with ids and sids. 
2/ importing a document and saving it again should keep the original id and sid
intact. It will ease the work of conditioners. 

Is it a lot of work for you to do the change ? 

The 2 only missing features that prevent me switching from FCollada to opencollada
are the import of <profile_GLSL> for materials and the ability to read sids.

Is it possible to have a status update for the import of <newparam> elements for GLSL
materials ? 

 

 </p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
