### ISSUE TITLE
<double_sided>

### ISSUE THREAD

**Issue by DINmatin** [KhronosGroup/OpenCOLLADA#250]
i'm no programmer. thus can anyone help implementing the export of two-sided materials?

it should be in EXTENDED_SHADER_PARAMETERS. i don't understand how certain extended shader parameters are exported and others not. so something like this:

<extended_shader>
     <double_sided>1</double_sided>
</extended_shader>

this would be so great as the colladaloader in three.js would interpret it correctly

thx, /martin.

**Comment by RemiArnaud** [comment]
this is not the right place. Please post bug in the three.js forum to report COLLADA importer issues.
