### ISSUE TITLE
Material props: missing color for textured props

### ISSUE THREAD

**Issue by septag** [KhronosGroup/OpenCOLLADA#254]
_3dsmax 2012 (64bit)_
_OpenCollada_: latest master build from repo

When setting a texture to a specific material property in 3dsmax (like diffuse or specular, ...) . exported collada property no longer contains __color__ values and is replaced by __texture__ value.
But both values should be available under material property tags, _color_ and _texture_ are both important in many renderers and is definitely required.

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
