### ISSUE TITLE
How to handle Polylists with multiple inputs from same source

### ISSUE THREAD

**Issue by gaiaclary** [KhronosGroup/OpenCOLLADA#259]
I wonder how this particular Collada should be imported to Blender:

    <polylist count="2" material="side-zenith_1">
        <input offset="0" semantic="VERTEX" source="#z1-ext_01_vertices"/>
        <input offset="1" semantic="TEXCOORD" source="#side-zenith" set="0"/>
        <input offset="2" semantic="TEXCOORD" source="#side-zenith" set="1"/>
        <input offset="3" semantic="TEXCOORD" source="#side-zenith" set="2"/>
        <input offset="4" semantic="TEXCOORD" source="#side-zenith" set="3"/>
        <vcount>281 24 </vcount>
        <p>4758 1 1 1 1 4759 ... 279 279 279 </p>
    </polylist>

The problem is how to handle multiple inputs with same source. Could possibly OpenCollada handle this and merge multiple inputs with same semantic and same source into one single input ? 

This is related to a bug report in Blender: https://developer.blender.org/T38482
And to a question on stackexchange:
http://stackoverflow.com/questions/21577226/how-to-handle-polylists-with-multiple-inputs-from-same-source

**Comment by RemiArnaud** [comment]
it is not the same data for each set, it has a different offset.

**Comment by RemiArnaud** [comment]
please re-open if need be.
