### ISSUE TITLE
[ColladaMaya] Baked Transforms and Character Clips incompatible 

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#26]
<b>What steps will reproduce the problem?</b>
1. create a character with a (source) animation clip
2. export with baked transforms option enabled
3. &lt;animation_clip&gt; tag for the clip does not instantiate the
   matrix curves

<b>What is the expected output? What do you see instead?</b>

the &lt;animation_clip&gt; only instantiates visibility curves, see below for why
it gets those and not the matrices.

<b>What version of the product are you using? On what operating system?</b>

ColladaMaya plugin r715 for Maya 2009 on Windows XP 32bit

<b>Please provide any additional information below.</b>

AFAICS there are two problems:
1) when baked transforms are enabled
VisualSceneExporter::exportMatrixTransform places the matrix plug
immediately in the AnimationSampleCache so that later when
AnimationHelper::isAnimated() is called it never returns kISANIM_Character
(since for animated items in the cache it always returns kISANIM_Sample).

To get around this I simply commented out the line
mDocumentExporter-&gt;getAnimationCache()-&gt;cachePlug(plug, true); in
exportMatrixTransform, but that is probably not the real solution here.

2) Now that the &quot;matrix&quot; plug is actually examined in isAnimated() it turns
out that it never is part of a Maya Character set as they only contain
keyable attributes and &quot;matrix&quot; is not keyable. The Character set contains
the attributes from which &quot;matrix&quot; is ultimately derived (&quot;translateX&quot;,
&quot;translateY&quot;, etc.), so when isAnimated() looks at getAnimatingNode(plug)
it only gets a MObject::kNullObj and therefore never returns kISANIM_Character.

<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=45</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
