### ISSUE TITLE
xml parser fails on linux

### ISSUE THREAD

**Issue by jellion** [KhronosGroup/OpenCOLLADA#265]
Hi, I pulled the most recent version from the repository and it crashes on document loading. I double-checked that I am linking to the xml2 library that came with the distribution.  I am running linux, ubuntu.  The same code works fine on mac osx.

Here is the relevant call stack:
#0  __strncmp_sse42 () at ../sysdeps/x86_64/multiarch/strcmp-sse42.S:164
#1  0x000000000159f7e5 in __xmlParserInputBufferCreateFilename (
    URI=0x22617c8 
    enc=XML_CHAR_ENCODING_NONE) at xmlIO.c:2412
#2  0x00000000015781a2 in xmlNewInputFromFile (ctxt=0x2261840, 
    filename=0x22617c8 
    at parserInternals.c:1462
#3  0x000000000158ee84 in xmlCreateURLParserCtxt (
    filename=0x22617c8 
    at parser.c:12591
#4  0x000000000153e68c in GeneratedSaxParser::LibxmlSaxParser::parseFile(char const*) ()
    at /OpenCOLLADA/GeneratedSaxParser/src/GeneratedSaxParserLibxmlSaxParser.cpp:72
#5  0x00000000006df2c8 in COLLADASaxFWL::VersionParser::createAndLaunchParser() ()
    at /OpenCOLLADA/COLLADASaxFrameworkLoader/src/COLLADASaxFWLVersionParser.cpp:329
#6  0x00000000006c85da in COLLADASaxFWL::FileLoader::load() ()
    at /OpenCOLLADA/COLLADASaxFrameworkLoader/src/COLLADASaxFWLFileLoader.cpp:79
#7  0x00000000006a743d in COLLADASaxFWL::Loader::loadDocument(std::string const&, COLLADAFW::IWriter*) ()
    at /OpenCOLLADA/COLLADASaxFrameworkLoader/src/COLLADASaxFWLLoader.cpp:221
#8  0x00000000015242bc in COLLADAFW::Root::loadDocument(std::string const&) ()

**Comment by RemiArnaud** [comment]
old issue related to wrong version of xml2
