### ISSUE TITLE
need OpenCollada for Maya 2015 MAC

### ISSUE THREAD

**Issue by CoIin** [KhronosGroup/OpenCOLLADA#268]
The bundles here:

https://github.com/KhronosGroup/OpenCOLLADA/wiki/OpenCOLLADA-Tools

only go up to Maya 2014, and trying to import that leads to a "too old SDK was used" error. Can someone build for the current SDK please?

Thanks.

**Comment by RemiArnaud** [comment]
Closing since we've been building maya 2015 for mac dor a while now. Please open other bugs as required
