### ISSUE TITLE
OpenCollada import issue with morphs and 3Ds Max

### ISSUE THREAD

**Issue by spoodge** [KhronosGroup/OpenCOLLADA#270]
As in this post...

https://github.com/KhronosGroup/OpenCOLLADA/issues/29

What steps will reproduce the problem?
1. Load up Daz studio V3 and max 2009.
2. Install opencollada plugin v 1.2.5 (32 or 64 bit gets same results)
3. load DAZ content such as Michael 4 or Victoria 4.2, and apply several
morphs (or just one) to either his body or his face.
4. export to DAE file, including the morphs.
5. using OpenCollada, import into max.

What is the expected output? What do you see instead?
You would expect to see the 3D mesh of Michael 4 or Victoria 4.2 with a
Morph and Skin modifier applied to it. Each channel of that Morph modifier
would correspond to one of the morphs exported unbaked out of DAZ studio
V3.
Instead of seeing the full 3D model, with skin and morph information, you
only see the helpers that make up the skeleton for rigging. There is no 3D
mesh.

What version of the product are you using? On what operating system?
OpenCollada 1.2.5
Windows 7 64 bit
DAZ studio v3
3Ds Max 2009

Please provide additional information below.
Exporting from DAZ without the morphs gives a correct import into 3Ds Max:
it shows the full 3D mesh with a Skin modifier properly applied.

Still seems to have this issue, ...

"Instead of seeing the full 3D model, with skin and morph information, you
only see the helpers that make up the skeleton for rigging. There is no 3D
mesh."

has any progress been made ? Tried all versions both 32 and 64 still only imports skeleton when trying to export morphs from Poser Pro 2012.

tia

**Comment by RemiArnaud** [comment]
Sorry, this is the wrong place for this bug. 
Please ask DAZ to fix their exporter.
