### ISSUE TITLE
Triangle Strips in ColladaMax

### ISSUE THREAD

**Issue by JamieT187** [KhronosGroup/OpenCOLLADA#279]
Hi guys,

I was wondering if there's the possibility to implement triangle strips into the ColladaMax exporter?  I'm working on a project where triangle strips is the ONLY option :-(  It seems that tri-strips are becoming obsolete as time goes on, so I understand that there isn't much demand for them, but if someone reading this knows how it could be added to the Max exporter I would SO greatful!

Thanks

**Comment by RemiArnaud** [comment]
this is not the job of the exporter to make such transformations, but external tools that can do dae->dae transformations.

see https://collada.org/mediawiki/index.php/Portal:Conditioners_directory for example, which contains a t-strip conditionner

Best Regards
-- Remi
