### ISSUE TITLE
Some of exported bones have type='NODE', instead of 'JOINT'

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#28]
1. Create biped object in 3ds max (Create-&gt;Systems-&gt;Biped)
2. Export scene using OpenCOLLADA exporter

In exported COLLADA file all of the scene nodes have type='NODE', but all
of them are 'JOINT's.
Only nodes used in skin controller(s) have type='JOINT'.

3ds max 9, Windows XP SP2
<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=50</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
