### ISSUE TITLE
OpenCollada import issue with morphs and 3Ds Max, exported from DAZ studio v3

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#29]
<b>What steps will reproduce the problem?</b>
1. Load up Daz studio V3 and max 2009.
2. Install opencollada plugin v 1.2.5 (32 or 64 bit gets same results)
3. load DAZ content such as Michael 4 or Victoria 4.2, and apply several 
morphs (or just one) to either his body or his face.
4. export to DAE file, including the morphs.
5. using OpenCollada, import into max.

<b>What is the expected output? What do you see instead?</b>
You would expect to see the 3D mesh of Michael 4 or Victoria 4.2 with a 
Morph and Skin modifier applied to it.  Each channel of that Morph modifier 
would correspond to one of the morphs exported unbaked out of DAZ studio 
V3.
Instead of seeing the full 3D model, with skin and morph information, you 
only see the helpers that make up the skeleton for rigging.  There is no 3D 
mesh.

<b>What version of the product are you using? On what operating system?</b>
OpenCollada 1.2.5
Windows 7 64 bit
DAZ studio v3
3Ds Max 2009

Please provide additional information below.
Exporting from DAZ without the morphs gives a correct import into 3Ds Max: 
it shows the full 3D mesh with a Skin modifier properly applied.
<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=53</p><hr/><h2>earlier comments</h2>
<p><strong>robindei...@gmail.com said, at 2010-04-01T14:46:20.000Z:</strong></p>
<p>This is a real blocker for us on a job at the moment.

If it's not easily (or imminently) fixable, is there any hacking we can do to the
.dae file - such as that hinted at in issue 11
[http://code.google.com/p/opencollada/issues/detail?id=11], which unfortunately
doesn't solve anything here - to make this work?

Many thanks</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
