### ISSUE TITLE
Evaluating double sided

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#30]
&quot;could you possibly add &lt;double_sided&gt;1&lt;/double_sided&gt; under
extras.technique.double_sided for 3ds max in your next update&quot;

<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=54</p><hr/><h2>earlier comments</h2>
<p><strong>redu...@gmail.com said, at 2011-02-27T02:54:43.000Z:</strong></p>
<p>Yes please! </p><p><strong>redu...@gmail.com said, at 2011-02-27T14:47:39.000Z:</strong></p>
<p>Did not ColladaMax from feeling support this? I think this is very useful for game development, so one can tell when a mesh must be rendered double sided and when not..</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
