### ISSUE TITLE
Maya 2016 support?

### ISSUE THREAD

**Issue by jhurlbut** [KhronosGroup/OpenCOLLADA#307]
I can't seem to find a build that is compatible with Maya 2016. 

// Error: line 1: Plug-in, "COLLADAMaya" was compiled against too old a version of the Maya API and is thus incompatible with the current Maya version. (COLLADAMaya) //

**Comment by RemiArnaud** [comment]
yes, I have not compiled for maya 2016 yet.
thanks for opening this issue. will get to this soon

� Remi

**Comment by RemiArnaud** [comment]
done
Max, Maya (PC and MAC) 2016 builds are available

**Comment by SphereFilm** [comment]
Any chance you have a compatible version for Maya 2017?

**Comment by RemiArnaud** [comment]
Working on this

**Comment by tneveu1** [comment]
Has there been any changes to this issue?  I'm also looking to export from Maya 2017

**Comment by RemiArnaud** [comment]
It's been release a while ago. 
See https://www.dropbox.com/sh/jssp45b88jkcoql/AADmXd26rNJhaZzTkPLfzYAOa/COLLADAMaya/win/v1.6.47/x64/ReleasePlugin2017?dl=0 for example
