### ISSUE TITLE
Plugin Crash 3dsmax2015 import

### ISSUE THREAD

**Issue by Webrow** [KhronosGroup/OpenCOLLADA#308]
I have a DAE file, created form Revit. 
As soon as I start the import of the file, 3ds max application crashes 
"Application crashed, save all files, the application will be closed" 

is there any way to figure out what is causing this ?

**Comment by RemiArnaud** [comment]
one thing you can do is the check if the collada document is valid
there are a few validators available.
this one http://sourceforge.net/projects/colladarefinery/files/COLLADA%20Coherency%20Test/
or the one in the openCOLLADA package

**Comment by RemiArnaud** [comment]
was the collada file valid ?
maybe you can send a file that causes the problem ?

**Comment by RemiArnaud** [comment]
closing - no response from @Webrow
