### ISSUE TITLE
Issue exporter warnings

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#31]
The OpenCollada exporter should warn users when it encounters features that
it cannot convert to Collada format. For example, the 3ds Max 2010 built-in
converter warns when it encounters non-standard material types (such as
&quot;Architectural&quot;) or when it has to cull entire geometries that cannot be
converted.

OpenCollada's exporter might produce better Collada files but it culls
geometries and materials silently forcing the user to report to trial and
error to figure out if anything got lost in the process.<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=57</p><hr/><h2>earlier comments</h2>
<p><strong>opencollada said, at 2010-02-16T07:02:59.000Z:</strong></p>
<p>Important feature, right.</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
