### ISSUE TITLE
Import into Maya causes multiple shape nodes to assign to one transform node

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#32]
<b>What steps will reproduce the problem?</b>
1. Export a model from SketchUp
2. Import into Maya
3. Maya transform nodes have multiple shape nodes

<b>What is the expected output? What do you see instead?</b>
I expect to see each shape node to have it's own individual transform node
as this is how Maya creates geometry by default. 

Instead Maya transform nodes have multiple shape nodes which messes the
scene as it makes it almost impossible to select geometry inside of Maya. 

I can run this MEL Script:

string $sel[] = `ls -sl -dag -lf`;
for ($each in $sel)
{
     string $group = `group -em -n ($each + &quot;_transform&quot;)`;
     parent -s $each $group;
}

But that will break the hierarchy of the original SketchUp scene.

<b>What version of the product are you using? On what operating system?</b>
Maya 2010x64, 1.2.2 Collada for Maya and Vista x64

<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=60</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
