### ISSUE TITLE
Error when exporting a single polygon (triangle)

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#33]
I'm using the OpenCOLLADA plugin (1.2.2.674) for Maya 2010 (64bit).

When trying to export a single polygon (a triangle), the geometry
description gets all confused with some &quot;inputs&quot; winding up in the
&quot;vertices&quot; section (instead of the &quot;triangles&quot; one):

       &lt;vertices id=&quot;polygon_MSHShape-vertices&quot;
name=&quot;polygon_MSHShape-vertices&quot;&gt;
         &lt;input semantic=&quot;POSITION&quot; source=&quot;#polygon_MSHShape-positions&quot;/&gt;
         &lt;input semantic=&quot;NORMAL&quot; source=&quot;#polygon_MSHShape-normals&quot;/&gt;
         &lt;input semantic=&quot;COLOR&quot; source=&quot;#polygon_MSHShape-colorSet1&quot;/&gt;
       &lt;/vertices&gt;
       &lt;triangles material=&quot;coloredChecker_SHDSG&quot; count=&quot;1&quot;&gt;
         &lt;input semantic=&quot;VERTEX&quot; source=&quot;#polygon_MSHShape-vertices&quot;
offset=&quot;0&quot;/&gt;
         &lt;input semantic=&quot;TEXCOORD&quot; source=&quot;#polygon_MSHShape-map1&quot;
offset=&quot;1&quot; set=&quot;0&quot;/&gt;
         &lt;p&gt;0 0 1 1 2 2&lt;/p&gt;
       &lt;/triangles&gt; 

But if I split this polygon in two (giving two triangles instead of one)
then everything is fine:

       &lt;vertices id=&quot;polygon_MSHShape-vertices&quot;
name=&quot;polygon_MSHShape-vertices&quot;&gt;
         &lt;input semantic=&quot;POSITION&quot; source=&quot;#polygon_MSHShape-positions&quot;/&gt;
       &lt;/vertices&gt;
       &lt;triangles material=&quot;coloredChecker_SHDSG&quot; count=&quot;2&quot;&gt;
         &lt;input semantic=&quot;VERTEX&quot; source=&quot;#polygon_MSHShape-vertices&quot;
offset=&quot;0&quot;/&gt;
         &lt;input semantic=&quot;NORMAL&quot; source=&quot;#polygon_MSHShape-normals&quot;
offset=&quot;1&quot;/&gt;
         &lt;input semantic=&quot;TEXCOORD&quot; source=&quot;#polygon_MSHShape-map1&quot;
offset=&quot;2&quot; set=&quot;0&quot;/&gt;
         &lt;input semantic=&quot;COLOR&quot; source=&quot;#polygon_MSHShape-colorSet1&quot;
offset=&quot;3&quot;/&gt;
         &lt;p&gt;0 0 0 0 3 1 3 0 2 2 2 0 0 3 0 0 1 4 1 0 3 5 3 0&lt;/p&gt;
       &lt;/triangles&gt; 

Now if I also use the &quot;exportTexTangents=1&quot; option, it gets even more
confused (the &quot;NORMAL&quot; element is still in the wrong section and the
&quot;offset&quot; numbers are wrong):

       &lt;vertices id=&quot;polygon_MSHShape-vertices&quot;
name=&quot;polygon_MSHShape-vertices&quot;&gt;
         &lt;input semantic=&quot;POSITION&quot; source=&quot;#polygon_MSHShape-positions&quot;/&gt;
         &lt;input semantic=&quot;NORMAL&quot; source=&quot;#polygon_MSHShape-normals&quot;/&gt;
       &lt;/vertices&gt;
       &lt;triangles material=&quot;coloredChecker_SHDSG&quot; count=&quot;1&quot;&gt;
         &lt;input semantic=&quot;VERTEX&quot; source=&quot;#polygon_MSHShape-vertices&quot;
offset=&quot;0&quot;/&gt;
         &lt;input semantic=&quot;TEXCOORD&quot; source=&quot;#polygon_MSHShape-map1&quot;
offset=&quot;1&quot; set=&quot;0&quot;/&gt;
         &lt;input semantic=&quot;COLOR&quot; source=&quot;#polygon_MSHShape-colorSet1&quot;
offset=&quot;2&quot;/&gt;
         &lt;input semantic=&quot;TEXTANGENT&quot;
source=&quot;#polygon_MSHShape-textangents&quot; offset=&quot;3&quot; set=&quot;0&quot;/&gt;
         &lt;input semantic=&quot;TEXBINORMAL&quot;
source=&quot;#polygon_MSHShape-texbinormals&quot; offset=&quot;3&quot; set=&quot;0&quot;/&gt;
         &lt;p&gt;0 0 0 0 1 1 0 1 2 2 0 2&lt;/p&gt;
       &lt;/triangles&gt;

Finally, when exporting just a single polygon (a triangle), invisible nodes
are also getting exported (even though the option &quot;exportInvisibleNodes&quot; is
set to 0). 
<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=63</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
