### ISSUE TITLE
Wrong pose (Maya 2015 x64)

### ISSUE THREAD

**Issue by bmpix** [KhronosGroup/OpenCOLLADA#330]
Hi,

When I'm trying use the latest build (57) to export a posed skinned character from .mb to dae (baketransforms = on, I need it), and then I try to import this dae back into Maya, I'm getting a completely wrong pose. That has been happening with the previous builds too. When I load the exported collada file elsewhere, the pose it correct.
.mb: https://dl.dropboxusercontent.com/u/15523014/adam_tree.mb
exported .dae: https://dl.dropboxusercontent.com/u/15523014/adam_tree.dae

Thank you!

**Comment by mycheckgithub** [comment]
Hello,

Here are the 2 screenshots. First one opening the original .mb and the second one importing the .dae
I don't see any difference about the pose.

Could you tell me more about it ?

  Thanks

![originalfile](https://cloud.githubusercontent.com/assets/2933765/8088322/b724b398-0fa0-11e5-97de-a0f9acfb3832.jpg)
![importeddae](https://cloud.githubusercontent.com/assets/2933765/8088326/ba8374f2-0fa0-11e5-89f0-5e94fa72ab0d.jpg)

**Comment by bmpix** [comment]
Thank you for looking into it. The pose in the screenshots you posted is correct; however, I'm getting this when I import the .dae into Maya scene. Looks to me like some signs are flipped in the rotations... Is there some option I'm not aware of?
![screen shot 2015-06-10 at 10 45 11 am](https://cloud.githubusercontent.com/assets/707549/8089673/3d86f876-0f5e-11e5-8d08-4f7979c91454.png)

**Comment by bmpix** [comment]
Sorry for being annoying, but any ideas how to fix that?

**Comment by RemiArnaud** [comment]
So, we are talking about a Maya import bug then?
Are you certain your using the opencollada dae import? (If it is the default importer provided by Autodesk, then you'd have to open a bug with Autodesk)

**Comment by bmpix** [comment]
I'm not quite sure. I have disabled the default plugin (I believe it's the fbxmaya.mll), I click File-Import, choose OpenCollada importer, and import that DAE. Gives me exactly the image I posted...

**Comment by bmpix** [comment]
Remi, you were right. It was a bug in Maya 2015, fixed in 2016.
