### ISSUE TITLE
Stable versions

### ISSUE THREAD

**Issue by aothms** [KhronosGroup/OpenCOLLADA#339]
Hi,

Is there any plan to stabilize on a public API, version it and release it? Downstream applications that rely on OpenCOLLADA now can only reference a specific commit number to build against, hence do not have any means to reference a stable version of the API while retaining bug fixes.

For example, the following commit [1] breaks compilation of the library I administer because it adds an additional argument to the COLLADASW::Scene constructor.

Other, major, applications have also noticed similar problems [2].

[1] https://github.com/KhronosGroup/OpenCOLLADA/commit/6fa340dd64ca813a45ebe3db28b23f93b1ba0916#diff-18
[2] https://developer.blender.org/T45300

Kind regards,
Thomas

**Comment by RemiArnaud** [comment]
Yes, sorry. 

@mycheckgithub @mcbarnes 
I'm wondering how best to deal with this.

This particular change is adding physics export, which is something that should have been there years ago. We do bug fixing, improvements and new features as openCOLLADA is moving forward.
openCOLLADA did not see much development in the past years, but its active again, and a lot of important improvement have been made last few months.

I don't see how it will be possible to release stable libraries, and maintain them (bug fixes only, no API change), based on the resources available to do so. So we can create releases, but there won't be any guarantee that the next release is maintaining API compatibility - not much different than having the upstream application use a specific SHA.

It's a matter of sharing the work. openCOLLADA is evolving in term of bug fixes, features. It provides max and maya exporters ready to use. And application writers using openCOLLADA have to share a bit of the burden by updating their integration from time to time.

Unless someone want to sign up to create and maintain release branches?
another idea is for someone to fork openCOLLADA?

But probably a better idea would be for upstream users to submit PR to recreate the entry points they are relying on if/when they are changed ? Probably two version of the constructor could be made available, and thus maintained forever. 

This said, we can automatically add a tag each time a PR is successfully merged, which could be easier than managing sha1. 

What do you think?

**Comment by aothms** [comment]
Ok, fair enough. Many thanks for the detailed reply. Here is a pull request [1]

[1] https://github.com/KhronosGroup/OpenCOLLADA/pull/340

Kind regards,
Thomas

**Comment by hobbes1069** [comment]
Regardless of API stability, versioned releases would be really nice. The current version in Fedora is 0 Release 24 :) It would be nice to reset the release to 1 every now and again.

Also, API stability can be checked, I use abi-compliance-checker but there are other tools to compare the current release to the new checkout and rebuild dependent packages as needed.

**Comment by RemiArnaud** [comment]
I'm reopening this, because I want to improve the situation before closing this issue.

**Comment by RemiArnaud** [comment]
@hobbes1069  -  could you comment on https://github.com/KhronosGroup/OpenCOLLADA/pull/340 if this fix works for you?

**Comment by hasufell** [comment]
Gentoo will have remove opencollada support from blender because of this. Arbitrary git snapshots are fragile and not maintainable.

**Comment by RemiArnaud** [comment]
I'm reporting here that we now have versioning in place, so you can now refer to a specific version of openCOLLADA in your builds. (see https://github.com/KhronosGroup/OpenCOLLADA/releases)

Also, we want to maintain API compatibility at the openCOLLADA library level and follow the semantic versioning rules, http://semver.org/  where major number changes when change is made that breaks backward compatibility. Our intent is in fact not to do that anytime soon, so if you detect a change that breaks backward compatibility consider this a bug and report it here. In other words, do not expect the major version number (1) to change anytime soon

**Comment by aothms** [comment]
@RemiArnaud this is great news. Thanks for making this happen.
