### ISSUE TITLE
Vertex color export bug in the Maya plugin

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#34]
I'm using the OpenCOLLADA plugin (1.2.2.674) for Maya 2010 (64bit).

It would seem that the vertex color export is broken: it systematically
defaults to 0, turning the whole object into whatever the first vertex's
color is. Here is the example (arranged in columns) of the following snipped:

       &lt;triangles count=&quot;2&quot; material=&quot;polygon-01-coloredChecker_SHD&quot;&gt;
         &lt;input semantic=&quot;VERTEX&quot; source=&quot;#polygon_MSHShape-vertices&quot;
offset=&quot;0&quot;/&gt;
         &lt;input semantic=&quot;NORMAL&quot; source=&quot;#polygon_MSHShape-normals&quot;
offset=&quot;1&quot;/&gt;
         &lt;input semantic=&quot;COLOR&quot; source=&quot;#polygon_MSHShape-colorSet1&quot;
offset=&quot;2&quot;/&gt;

(Vertex/Normal/Color)
     0 0 0
     3 1 0
     2 2 0
     0 3 0
     1 4 0
     3 5 0

As you can see, the last column is supposed to relate to the array of
vertex color, but instead it is only 0 all the way. Instead of being
something more like:

     0 0 0
     3 1 1
     2 2 2
     0 3 3
     1 4 4
     3 5 5 

<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=64</p><hr/><h2>earlier comments</h2>
<p><strong>heinrich...@gmail.com said, at 2010-08-13T14:35:43.000Z:</strong></p>
<p>I second that. Same experience with Win 7 Maya 2011 64 bit, COLLADAMaya 1.3.0rc1, and 1.2.2. on OS X 10.6 Maya 2011 64 bit. 

cheers, 

h</p><p><strong>kproudf...@gmail.com said, at 2010-11-17T21:53:37.000Z:</strong></p>
<p>We're having the same issue (looks like its noted in bug IDs 88 and 100 as well).

We use your released version of the exporter and don't build our own, and thus we cannot take advantage of your patch fix noted in issue 100.  Any estimate on a released fix for this one? It's basically a show stopper for us, as we use vertex colors extensively on our assets...

Thanks Julien!</p><p><strong>martin.b...@gmail.com said, at 2010-11-19T15:48:24.000Z:</strong></p>
<p>I have a fix for this I will be posting a new bug with the fix in it for the devs to integrate.</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
