### ISSUE TITLE
COLLADAMaya 2016 (released on Sep 10, 2015) does not work on my machine

### ISSUE THREAD

**Issue by grandyang** [KhronosGroup/OpenCOLLADA#342]
COLLADAMaya 2016 (released on Sep 10, 2015) does not work on my machine.

I used Maya 2016 x64 English

I added 'COLLADAMaya.mll' to in plug-in managers, but I cannot export the file, it says "Error:line 0: Cannot find procedure 'openColladaExporterOpts'. 

Does anyone have an idea how to solve this. Thanks!

**Comment by RemiArnaud** [comment]
Where did you get this version?
looking at http://opencollada.fl4re.com , COLLADAMaya/win/  the latest version is from 08/04

2015-08-04_00-55-22_#60

**Comment by grandyang** [comment]
Now it works, however, some parts of the model look weird, moreover, no texture exported. Could you please help me with it, thanks!

I used version from 08/04 ReleasePlugin2016.zip

**Comment by RemiArnaud** [comment]
We're not experiencing any problems with the exporter.
Maybe you can share an exported model ?

**Comment by RemiArnaud** [comment]
also, make sure you select the option to 'copy' the textrues when you
export if you want the textures to be 'exported'.
what software are you using to import the model into?

**Comment by grandyang** [comment]
I used meshlab to import the model. 
By the way, how can share a file here, like uploading a file?

**Comment by RemiArnaud** [comment]
you can use dropbox to share a file for example.

**Comment by RemiArnaud** [comment]
you can just share it with me -> remi @ acm . org

**Comment by grandyang** [comment]
Sure, I will share one tomorrow morning, thanks!

**Comment by grandyang** [comment]
Is that also your email address,can I send you an email with attachment instead?

**Comment by RemiArnaud** [comment]
yes it is

**Comment by RemiArnaud** [comment]
please re-open if this is still a problem with more recent exporter
