### ISSUE TITLE
Import screws up model/skeleton

### ISSUE THREAD

**Issue by ryukra** [KhronosGroup/OpenCOLLADA#345]
I'm using the latest version of opencollada.
If I import a model from someone who exported it with the opencollada2016 plugin I get this:

http://puu.sh/kiEMb/45c76e6ac9.png

http://puu.sh/khs1f/27a06c964a.jpg

http://puu.sh/kiEWg/6a70a9133c.jpg

Here are two of these models:
http://puu.sh/kiFDF/d00bdc9189.dae
http://puu.sh/kiFEC/8f1ec4456b.dae

This is how it looks in blender with the default importer:
http://puu.sh/kiFLf/4b7d22ab32.jpg

**Comment by RemiArnaud** [comment]
yes, the daes looks fine. The importer is broken.

@mycheckgithub or @jerome-jacob could you take a look at this ? 
The importer got broken sometime ago, out of sync with the exporter updates I imagine.

**Comment by mycheckgithub** [comment]
#347 

This should fix the import bug.
Please let me know if it's ok for you.

**Comment by RemiArnaud** [comment]
@ryukra could you grab the binaries from opencollada.fl4re.com - pull request 347 - and verify that the bug is fixed.

Thank you.

**Comment by ryukra** [comment]
Works! Thanks. :)

**Comment by RemiArnaud** [comment]
Awesome work @mycheckgithub
