### ISSUE TITLE
Bone animated model exported incorrectly

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#35]
<b>What steps will reproduce the problem?</b>
1. Create mesh with bones, ik helpers and basic rigging.
2. Animate and export it.
3. Load the model in Papervision 3d with the DAE parser.

<b>What is the expected output? What do you see instead?</b>
I expect syncronized/acceptable animation. In my example I load a horse,
the front legs move very slow and the back legs move really fast, the front
legs look tilted about 30 degrees. So the whole animation looks very bad. I
rendered the animation in 3dsmax to video and the animation plays properly.

<b>What version of the product are you using? On what operating system?</b>

Windows 7 Ultimate 32-bits
3dsmax 2010
Open Collada 1.2.5
Papervision3D Rev. 939

Will it be better if I bake the animation to vertex level? I think that
will work but then the file size will be huge, thanks!
<b>Please provide any additional information below.</b><p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=66</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
