### ISSUE TITLE
OpenCOLLADA Maya: PhysX capsule transform not correct

### ISSUE THREAD

**Issue by jerome-jacob** [KhronosGroup/OpenCOLLADA#356]
PhysX capsule transform is not computed correctly. Code supposes capsules are Y axis oriented which is not always true.

**Comment by RemiArnaud** [comment]
Do you mean that in PhysX the capsules can be defined on a different axis than Y, and therefore we need a transform when exporting ?

**Comment by jerome-jacob** [comment]
Exactly.

**Comment by RemiArnaud** [comment]
@jerome-jacob can this be closed?

**Comment by jerome-jacob** [comment]
Fixed and PR merged.
