### ISSUE TITLE
No import of normal maps

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#36]
This issue is rather a feature request

<b>What steps will reproduce the problem?</b>

1. Exporting a Model with a normal map in 3ds max
2. Import it in your own framework using your own IWriter implementation
3. The normal map will appear in it's own OpenCollada-Max extra profile in
the DAE file

<b>What is the expected output? What do you see instead?</b>

The normal map is being recognized and registered in the appropriate
(currently not existing) field of the Common Effect class. 
Instead, the sampler is recognized in the image library, but it isn't
possible to link it from the appropriate material, as the required
SamplerID isn't existant in the EffectCommon class ( SamplerPointerArray ).

<b>What version of the product are you using? On what operating system?</b>

1.5, Visual C++ 08, Windows Vista x64

<b>Please provide any additional information below.</b>

A possible workaround is to store your normal maps in the emission field,
as it is not required for most applications. However, this is a rather
important feature.

<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=67</p><hr/><h2>earlier comments</h2>
<p><strong>opencollada said, at 2010-04-12T18:14:13.000Z:</strong></p>
<p>Candidate for an <extra> tag.</p><p><strong>nitrogen...@gmail.com said, at 2010-04-14T11:47:06.000Z:</strong></p>
<p>See http://code.google.com/p/opencollada/issues/detail?id=59 for a patch which solves 
at least the export in extra tag problem (for normal maps as well for a couple of 
other maps).

Any idea when that patch gets applied and a new build is uploaded? It's inconvenient 
to use custom builds for months.</p><p><strong>opencollada2@gmail.com said, at 2011-01-19T15:38:21.000Z:</strong></p>
<p>Probably fixed with issue 59. Please verify.</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
