### ISSUE TITLE
Visual Studio 2015 compile error comes 

### ISSUE THREAD

**Issue by darongE** [KhronosGroup/OpenCOLLADA#366]
I compiled visual studio 2015.  But can't compile..

![compile_error](https://cloud.githubusercontent.com/assets/3068049/11235968/3cf0f3a0-8e19-11e5-8fc9-bf3e8cb1e9b7.png)

**Comment by RemiArnaud** [comment]
Please use VS 2013 for now.

**Comment by darongE** [comment]
Ok
