### ISSUE TITLE
OpenCollada loses settings when exporting from Max 2010

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#37]
<b>What steps will reproduce the problem?</b>
1. Open &quot;Test Case - Glass Wall and Boxes.max&quot; under 3ds Max 2010
2. Export using OpenCollada
3. Import file from step 2 using OpenCollada
4. Notice light settings have been lost

<b>What is the expected output? What do you see instead?</b>
Exporting and re-importing a file should result in the original model.

<b>What version of the product are you using? On what operating system?</b>
OpenCollada 1.2.5 or 1.3.0 RC under 3ds Max 2010 64-bit mode.

Please let me know if you can reproduce the problem.<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=70</p><hr/><h2>earlier comments</h2>
<p><strong>opencollada said, at 2010-04-22T07:12:06.000Z:</strong></p>
<p>Support for <technique profile="OpenCOLLADA3dsMax"> not supported during import. Will
be included as soon as the custom extra tag handling is finalized for the OpenCOLLADA
profile.</p><p><strong>cowwoc%b...@gtempaccount.com said, at 2010-04-22T22:54:09.000Z:</strong></p>
<p>Hi Sebastian,

Is there an issue number for the extra tag handling? Is this expected in the short or
long term?</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
