### ISSUE TITLE
joint with no influence in the skinning process are not included into library controller

### ISSUE THREAD

**Issue by mycheckgithub** [KhronosGroup/OpenCOLLADA#372]
If a joint (having childrens) into the skeleton hierarchy is not part of the skinning process (no influence), then it won't be included into the library controller so no WorldInverseBindPose will be calculated for him.

We need BindPose for all joints into the skeleton hierarchy independently of the skinning.

**Comment by RemiArnaud** [comment]
@mycheckgithub - can this be closed?

**Comment by RemiArnaud** [comment]
@mycheckgithub - closed. Please re-open if needed
