### ISSUE TITLE
Debug build of OpenCOLLADAValidator fails when CMAKE_DEBUG_POSTFIX used

### ISSUE THREAD

**Issue by Stinkfist0** [KhronosGroup/OpenCOLLADA#377]
Invoke CMake with e.g. `-DCMAKE_DEBUG_POSTFIX=d`. Building of OpenCOLLADAValidator will fail as potential debug postfix is not considered in `target_link_libraries`

**Comment by Stinkfist0** [comment]
https://github.com/KhronosGroup/OpenCOLLADA/pull/235

**Comment by RemiArnaud** [comment]
PR failed to build. Please re-open as needed
