### ISSUE TITLE
OpenCollada for Maya2015

### ISSUE THREAD

**Issue by MM85** [KhronosGroup/OpenCOLLADA#379]
Hello, 
I don't come put the opencollada for maya 2015. What files are we need? Links direct? 
I want this pack because i want make 3d files in dae with Maya. That files be used for the reality augmented and the french exam. It's cool if you quite reply fast.

I'am sorry for the language and my expression, i am an french etudiant.

**Comment by RemiArnaud** [comment]
Telechargements sur opencollada.fl4re.com
Versions stables - suivez le lien COLLADAMaya 
La derniere version a le plus grand numero. 
Tenez nous au courant !

**Comment by MM85** [comment]
I have this crash. It's possible you make a short video in guide of Youtube? I think is very better to understand this manipulation. Else, say me by step :/
![image](https://cloud.githubusercontent.com/assets/16709781/12339564/eaba7032-bb15-11e5-8503-6086acf4d534.png)

**Comment by RemiArnaud** [comment]
Does not seem related to the exporter per say. 

See http://upandready.typepad.com/up_and_ready/2013/09/maya-2014-the-case-of-foundationdll-error.html

-- Rémi

**Comment by MM85** [comment]
I desinstall this version and put Maya 2013, it's more easy
