### ISSUE TITLE
wrong opacity for effects without set transparency

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#38]
<b>What steps will reproduce the problem?</b>
1. import scene with an effect without explicitly set transparency
2. if this effect is a first one processed by the parser, it would
interally have mOpaqueMode undefined (in release some random number, in
debug it's 0xcdcdcdcd) as mOpaqueMode is not set in LibraryEffectsLoader
constructor

<b>What is the expected output? What do you see instead?</b>
expected is that it would be set to UNSPECIFIED_OPAQUE

<b>What version of the product are you using? On what operating system?</b>
trunk, r736, win7-64, visual studio 2008

<b>Please provide any additional information below.</b>
patch would be to add
		, mOpaqueMode( UNSPECIFIED_OPAQUE )
line to COLLADASaxFWLLibraryEffectsLoader.cpp after line 37
<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=71</p><hr/><h2>earlier comments</h2>
<p><strong>mikee%mi...@gtempaccount.com said, at 2010-04-20T20:17:09.000Z:</strong></p>
<p>i've found this issue when I've worked around a bug in GoogleSketchup, which by
default sets transparency to 0 (instead of 1 as it should be for A_ONE) and does not
indicated it with changed transparency mode
can you also make the original transparency mode visible from the API for each
effect? i know that all calculations regarding opacity are done inside the API, but
if an exporter does not conform to the specifications than we have no option how to
check this i.e. if I know that transparency mode is set to default and all objects in
the scene have transparency 0, than I can pretty much safely say that the exporter is
bugged and assume that the mode used was A_ZERO .. I am doing a similar thing right
now (reverting transparency when numobjects_withTransparency_0 >
numobjectswithTransparency_1), but as I said I can only assume that</p><p><strong>opencollada2@gmail.com said, at 2011-01-19T16:33:35.000Z:</strong></p>
<p>If have fixed the bug in r815.

Leaving this issue open due to the requested enhancement.</p><p><strong>stepan.h...@gmail.com said, at 2011-05-09T16:48:59.000Z:</strong></p>
<p>OpaqueMode is fundamental information that needs to be exposed.
Imagine that application imports
    <transparent opaque="RGB_ZERO">
      <texture texture="glass_tga-sampler" texcoord="CHANNEL1" />
    </transparent>
With OpaqueMode hidden, application does not know where to read transparency from.</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
