### ISSUE TITLE
ColladaMAYA 2014 - animation failing to export/import

### ISSUE THREAD

**Issue by dawnchapel** [KhronosGroup/OpenCOLLADA#380]
Hello! I'm trying to do a round-trip import/export of animation in Maya 2014, on windows 7 x64.  The export reports no errors, but when I re-import it to see if it worked, all of the animation is gone.

I have a joint hierarchy smooth-bound to polygons.  Some of the animation is done via set driven keys - so the keyframes are on nurbs curves whose transformations drive the transformation of the joints.  Some of the keyframe animation is on the joints themselves, on joints that have no set driven keys on them.  All of the animation was done on an animation layer other than the BaseAnimation layer, however I also tried merging the animation layer with the BaseAnimation layer and got the same results.

When I export, I'm trying to export the joint movement only, so I select the root node of the joint hierarchy, and go to export selected.  Bake transforms, animations, and optimize animations are all enabled.

(I note that Autodesk's fbx/collada exporter allows me to specify a frame range of animation to export, while the openCOLLADA exporter does not, but I am having the same issue with the Autodesk exporter.)

**Comment by RemiArnaud** [comment]
animations were broken recently - wrong ID was provided for targets. Can you do me a favor and check again with the latest exporter available ?

**Comment by dawnchapel** [comment]
Sure, I tried it just now with the .mll from the 2016-01-13_18-30-30_#82 dropbox folder.  It's dated as having been modified 43 hours ago.  Is there a newer one?  (I had help in finding that dropbox, I'm still unable to find the link to where on the khronos website or on github the plugin updates are being pushed to.)

**Comment by dawnchapel** [comment]
I've attempted to recreate the issue in a simpler file than the one that I'm working on, and got the same result.  I've attached the maya binary and the exported .DAE file.

In the attached maya binary, keys are set only on the control object (a nurbs circle), and the transformations of the circle drives the transformations of the joint hierarchy via set driven keys.  In the exported collada file, I selected the root joint of the joint hierarchy, and exported selected using the openCOLLADA exporter.  I imported it into a new maya scene using the openCOLLADA importer, and none of the joint movement came with it.

[opencollada_sdktest_01_15_16.zip](https://github.com/KhronosGroup/OpenCOLLADA/files/92726/opencollada_sdktest_01_15_16.zip)

**Comment by RemiArnaud** [comment]
Looks like you are using a 'bend controller' - which is very specific to non real time modeling software.
The only way to export this would be to 'bake' the animation, but then the flexibility of the controller will be lost. So it would no be very useful. 

Sorry but if you want to export this with COLLADA you'll have to bake, or use more standard animations on the skeleton.

**Comment by dawnchapel** [comment]
Yeah, I'm not looking to keep the control objects, I *just* want to keep the movement of the joints so that I can load the finished animation library into the engine I'm using.  I didn't see any option to bake out the animation in the openCOLLADA exporter, I'll investigate other baking options in Maya.
