### ISSUE TITLE
Maya 2014 issue

### ISSUE THREAD

**Issue by animationfund** [KhronosGroup/OpenCOLLADA#383]
Hi guys! I tried setting up Collada for Maya 2014 on mac and received this error:

// Error: line 1: dlopen(/Users/Shared/Autodesk/maya/2014/plug-ins/COLLADAMaya.bundle, 1): Library not loaded: /usr/lib/libc++.1.dylib  Referenced from: /Users/Shared/Autodesk/maya/2014/plug-ins/COLLADAMaya.bundle  Reason: image not found (COLLADAMaya)

I placed the files where the read me file mentioned but something seems wrong still. Is there any chance anyone could help with this please? Thanks!

**Comment by RemiArnaud** [comment]
what version of OSX are you using ?
have you installed the latest service pack ? http://techgoggles.in/index.php/fixed-maya-2014-mac-os-x-yosemite-10-10-compatibility-issues/

**Comment by animationfund** [comment]
10.68 unfortunately my computer is old so it can't handle the update without crashing. Although I found out yesterday that by default Maya 2014 comes with Collada installed with the .fbx option. I was able to get it working from that.

**Comment by RemiArnaud** [comment]
I think this library comes standard with 10.7

otherwise it seems a complicated process to get it working with 10.6 ->
http://stackoverflow.com/questions/18033255/install-libc-on-mac-10-6-8

I will have to close this bug, but make a note that 10.6 is not supported
