### ISSUE TITLE
Incorrect target name for animation data when using namespaces

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#39]
<b>What steps will reproduce the problem?</b>
1. In Maya, create and animate a box with two keyframes.
2. Create a namespace, and add the box to it.
3. Export the Collada file.

<b>What is the expected output? What do you see instead?</b>
Expected: Animation data that references the object definition in 
&lt;library_visual_scenes&gt;.

Instead:  The object name defined in &lt;library_visual_scenes&gt; contains the 
namespace as part of its name (i.e. namespace_box1).  However, the 
animation data references the target object without the namespace pre-
pended to the name. (i.e. box1).  This prevents box1 from receiving the 
animation information.

<b>What version of the product are you using? On what operating system?</b>
From 'trunk' on 3/11/2010.
Using Windows x64.

<b>Please provide any additional information below.</b>

I was able to temporarily fix this by making the following change 
in 'COLLADAMayaAnimationExporter.cpp' on line 1292:

Before:
         else nodeId = mDocumentExporter-&gt;mayaNameToColladaName ( 
fnDagNode.name ().asChar ());
  
After:
         else nodeId = mDocumentExporter-&gt;mayaNameToColladaName ( 
fnDagNode.name ().asChar (), false );   <p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=72</p><hr/><h2>earlier comments</h2>
<p><strong>kproudf...@gmail.com said, at 2010-10-14T22:37:26.000Z:</strong></p>
<p>we're running into a similar show-stopper.  The name space is getting into our animation channels... and thus all of our animations are breaking.

Any updates on this?

We're using the latest release of OpenCollada, in Maya 2011 32bit.</p><p><strong>dmccart...@altego.com said, at 2011-09-28T20:49:24.000Z:</strong></p>
<p>This is affecting us as well.  If we commit the source change proposed by the op's, can that be integrated into the next build?</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
