### ISSUE TITLE
Linker errors in libXml

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#40]
$ scons
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
g++ -o COLLADAValidator/bin/posix/x86_64/debuglibxml/OpenCOLLADAValidator
-static
COLLADAValidator/obj/posix/x86_64/debuglibxml/src/ValidationErrorHandler.o
COLLADAValidator/obj/posix/x86_64/debuglibxml/src/main.o
-LCOLLADABaseUtils/lib/posix/x86_64/debug
-Lcommon/libftoa/lib/posix/x86_64/debug
-Lcommon/libBuffer/lib/posix/x86_64/debug
-LCOLLADAFramework/lib/posix/x86_64/debug
-LExternals/MathMLSolver/lib/posix/x86_64/debug
-LExternals/UTF/lib/posix/x86_64/debug
-LCOLLADASaxFrameworkLoader/lib/posix/x86_64/debuglibxml
-LGeneratedSaxParser/lib/posix/x86_64/debuglibxml
-lOpenCOLLADASaxFrameworkLoader -lMathMLSolver -lOpenCOLLADAFramework
-lOpenCOLLADABaseUtils -lGeneratedSaxParser -lpcre -lftoa -lbuffer -lUTF -lxml2
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.5.0/../../../../lib/libxml2.a(nanohttp.o):
In function `xmlNanoHTTPConnectHost':
(.text+0x93d): warning: Using 'getaddrinfo' in statically linked
applications requires at runtime the shared libraries from the glibc
version used for linking
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.5.0/../../../../lib/libxml2.a(nanohttp.o):
In function `xmlNanoHTTPConnectHost':
(.text+0xa24): warning: Using 'gethostbyname' in statically linked
applications requires at runtime the shared libraries from the glibc
version used for linking
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.5.0/../../../../lib/libxml2.a(xmlIO.o):
In function `xmlGzfileOpenW':
(.text+0xed0): undefined reference to `gzopen64'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.5.0/../../../../lib/libxml2.a(xmlIO.o):
In function `xmlGzfileOpenW':
(.text+0xefc): undefined reference to `gzdopen'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.5.0/../../../../lib/libxml2.a(xmlIO.o):
In function `__xmlParserInputBufferCreateFilename':
(.text+0x103c): undefined reference to `gzdirect'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.5.0/../../../../lib/libxml2.a(xmlIO.o):
In function `xmlFreeZMemBuff':
(.text+0x1168): undefined reference to `deflateEnd'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.5.0/../../../../lib/libxml2.a(xmlIO.o):
In function `xmlGzfileClose':
(.text+0x2b35): undefined reference to `gzclose'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.5.0/../../../../lib/libxml2.a(xmlIO.o):
In function `xmlGzfileWrite':
(.text+0x2b65): undefined reference to `gzwrite'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.5.0/../../../../lib/libxml2.a(xmlIO.o):
In function `xmlIOHTTPCloseWrite':
(.text+0x2ceb): undefined reference to `deflate'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.5.0/../../../../lib/libxml2.a(xmlIO.o):
In function `xmlIOHTTPWrite':
(.text+0x3054): undefined reference to `deflate'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.5.0/../../../../lib/libxml2.a(xmlIO.o):
In function `xmlIOHTTPWrite':
(.text+0x311a): undefined reference to `crc32'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.5.0/../../../../lib/libxml2.a(xmlIO.o):
In function `xmlGzfileRead':
(.text+0x31e5): undefined reference to `gzread'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.5.0/../../../../lib/libxml2.a(xmlIO.o):
In function `xmlCreateZMemBuff':
(.text+0x32ad): undefined reference to `deflateInit2_'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.5.0/../../../../lib/libxml2.a(xmlIO.o):
In function `xmlCreateZMemBuff':
(.text+0x32c0): undefined reference to `crc32'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.5.0/../../../../lib/libxml2.a(xmlIO.o):
In function `xmlGzfileOpen_real':
(.text+0x1529): undefined reference to `gzdopen'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.5.0/../../../../lib/libxml2.a(xmlIO.o):
In function `xmlGzfileOpen_real':
(.text+0x1573): undefined reference to `gzopen64'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.5.0/../../../../lib/libxml2.a(nanohttp.o):
In function `xmlNanoHTTPFreeCtxt':
(.text+0xd8a): undefined reference to `inflateEnd'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.5.0/../../../../lib/libxml2.a(nanohttp.o):
In function `xmlNanoHTTPRead':
(.text+0xfcd): undefined reference to `inflate'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.5.0/../../../../lib/libxml2.a(nanohttp.o):
In function `xmlNanoHTTPMethodRedir':
(.text+0x1cf8): undefined reference to `inflateInit2_'
collect2: ld returned 1 exit status
scons: ***
[COLLADAValidator/bin/posix/x86_64/debuglibxml/OpenCOLLADAValidator] Error 1
scons: building terminated because of errors.

$ gcc --version
gcc (GCC) 4.5.0
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ uname -a
Linux bstation 2.6.33-ARCH #1 SMP PREEMPT Mon Apr 26 19:31:00 CEST 2010
x86_64 Intel(R) Core(TM) i7 CPU 920 @ 2.67GHz GenuineIntel GNU/Linux<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=75</p><hr/><h2>earlier comments</h2>
<p><strong>lub...@gmail.com said, at 2010-05-03T01:49:18.000Z:</strong></p>
<p>same issue on ubuntu 9.10 64bit with gcc 4.4

$ scons
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
g++ -o COLLADAValidator/bin/posix/x86_64/debuglibxml/OpenCOLLADAValidator -static
COLLADAValidator/obj/posix/x86_64/debuglibxml/src/ValidationErrorHandler.o
COLLADAValidator/obj/posix/x86_64/debuglibxml/src/main.o
-LCOLLADABaseUtils/lib/posix/x86_64/debug -Lcommon/libftoa/lib/posix/x86_64/debug
-Lcommon/libBuffer/lib/posix/x86_64/debug -LCOLLADAFramework/lib/posix/x86_64/debug
-LExternals/MathMLSolver/lib/posix/x86_64/debug
-LExternals/UTF/lib/posix/x86_64/debug
-LCOLLADASaxFrameworkLoader/lib/posix/x86_64/debuglibxml
-LGeneratedSaxParser/lib/posix/x86_64/debuglibxml -lOpenCOLLADASaxFrameworkLoader
-lMathMLSolver -lOpenCOLLADAFramework -lOpenCOLLADABaseUtils -lGeneratedSaxParser
-lpcre -lftoa -lbuffer -lUTF -lxml2
/usr/lib/gcc/x86_64-linux-gnu/4.4.1/../../../../lib/libxml2.a(nanohttp.o): In
function `xmlNanoHTTPConnectHost':
(.text+0xe50): warning: Using 'getaddrinfo' in statically linked applications
requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/x86_64-linux-gnu/4.4.1/../../../../lib/libxml2.a(nanohttp.o): In
function `xmlNanoHTTPConnectHost':
(.text+0xf64): warning: Using 'gethostbyname' in statically linked applications
requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/x86_64-linux-gnu/4.4.1/../../../../lib/libxml2.a(xmlIO.o): In function
`xmlGzfileOpenW':
(.text+0xdb9): undefined reference to `gzopen64'
/usr/lib/gcc/x86_64-linux-gnu/4.4.1/../../../../lib/libxml2.a(xmlIO.o): In function
`xmlGzfileOpenW':
(.text+0xddc): undefined reference to `gzdopen'
/usr/lib/gcc/x86_64-linux-gnu/4.4.1/../../../../lib/libxml2.a(xmlIO.o): In function
`__xmlParserInputBufferCreateFilename':
(.text+0xf44): undefined reference to `gzread'
/usr/lib/gcc/x86_64-linux-gnu/4.4.1/../../../../lib/libxml2.a(xmlIO.o): In function
`__xmlParserInputBufferCreateFilename':
(.text+0xf70): undefined reference to `gzrewind'
/usr/lib/gcc/x86_64-linux-gnu/4.4.1/../../../../lib/libxml2.a(xmlIO.o): In function
`xmlFreeZMemBuff':
(.text+0x10b8): undefined reference to `deflateEnd'
/usr/lib/gcc/x86_64-linux-gnu/4.4.1/../../../../lib/libxml2.a(xmlIO.o): In function
`xmlGzfileClose':
(.text+0x2a65): undefined reference to `gzclose'
/usr/lib/gcc/x86_64-linux-gnu/4.4.1/../../../../lib/libxml2.a(xmlIO.o): In function
`xmlGzfileWrite':
(.text+0x2a95): undefined reference to `gzwrite'
/usr/lib/gcc/x86_64-linux-gnu/4.4.1/../../../../lib/libxml2.a(xmlIO.o): In function
`xmlIOHTTPCloseWrite':
(.text+0x2c4b): undefined reference to `deflate'
/usr/lib/gcc/x86_64-linux-gnu/4.4.1/../../../../lib/libxml2.a(xmlIO.o): In function
`xmlIOHTTPWrite':
(.text+0x2ffc): undefined reference to `deflate'
/usr/lib/gcc/x86_64-linux-gnu/4.4.1/../../../../lib/libxml2.a(xmlIO.o): In function
`xmlIOHTTPWrite':
(.text+0x30c2): undefined reference to `crc32'
/usr/lib/gcc/x86_64-linux-gnu/4.4.1/../../../../lib/libxml2.a(xmlIO.o): In function
`xmlGzfileRead':
(.text+0x3195): undefined reference to `gzread'
/usr/lib/gcc/x86_64-linux-gnu/4.4.1/../../../../lib/libxml2.a(xmlIO.o): In function
`xmlCreateZMemBuff':
(.text+0x328d): undefined reference to `deflateInit2_'
/usr/lib/gcc/x86_64-linux-gnu/4.4.1/../../../../lib/libxml2.a(xmlIO.o): In function
`xmlCreateZMemBuff':
(.text+0x32a0): undefined reference to `crc32'
/usr/lib/gcc/x86_64-linux-gnu/4.4.1/../../../../lib/libxml2.a(xmlIO.o): In function
`xmlGzfileOpen_real':
(.text+0x1479): undefined reference to `gzdopen'
/usr/lib/gcc/x86_64-linux-gnu/4.4.1/../../../../lib/libxml2.a(xmlIO.o): In function
`xmlGzfileOpen_real':
(.text+0x14c3): undefined reference to `gzopen64'
/usr/lib/gcc/x86_64-linux-gnu/4.4.1/../../../../lib/libxml2.a(nanohttp.o): In
function `xmlNanoHTTPFreeCtxt':
(.text+0xa7a): undefined reference to `inflateEnd'
/usr/lib/gcc/x86_64-linux-gnu/4.4.1/../../../../lib/libxml2.a(nanohttp.o): In
function `xmlNanoHTTPRead':
(.text+0xce3): undefined reference to `inflate'
/usr/lib/gcc/x86_64-linux-gnu/4.4.1/../../../../lib/libxml2.a(nanohttp.o): In
function `xmlNanoHTTPMethodRedir':
(.text+0x1e31): undefined reference to `inflateInit2_'
collect2: ld returned 1 exit status
scons: *** [COLLADAValidator/bin/posix/x86_64/debuglibxml/OpenCOLLADAValidator] Error 1
scons: building terminated because of errors.

$ svn info
Path: .
URL: http://opencollada.googlecode.com/svn/trunk
Repository Root: http://opencollada.googlecode.com/svn
Repository UUID: ec7ac696-a6cd-11de-b195-ab392a2a73f5
Revision: 741
Node Kind: directory
Schedule: normal
Last Changed Author: robert@opencollada.org
Last Changed Rev: 741
Last Changed Date: 2010-04-15 16:00:19 +0200 (Thu, 15 Apr 2010)

$ gcc --version
gcc (Ubuntu 4.4.1-4ubuntu9) 4.4.1
Copyright (C) 2009 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ uname -a
Linux bBook 2.6.31-9-rt #152-Ubuntu SMP PREEMPT RT Thu Oct 15 13:22:24 UTC 2009
x86_64 GNU/Linux
</p><p><strong>lub...@gmail.com said, at 2010-05-05T12:44:26.000Z:</strong></p>
<p>I had to set this in SConstruct:

vars.Add(BoolVariable('SHAREDLIB', 'Set to build shared libraries instead of static 
ones (untested).', 1))</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
