### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [KhronosGroup/OpenCOLLADA#402]
I would like to point out that identifiers like "[`__COLLADAFW_UNIQUEID_H__`](https://github.com/KhronosGroup/OpenCOLLADA/blob/d616b9966b8fc626a01e2a8c2ce283f7967c0d4d/COLLADAFramework/include/COLLADAFWUniqueId.h#L11)" and "[`__COLLADASTREAMWRITER_CSWC_H__`](https://github.com/KhronosGroup/OpenCOLLADA/blob/469fda06976a6c559c65113ea317cf2bdab55300/COLLADAStreamWriter/include/COLLADASWConstants.h#L11)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by RemiArnaud** [comment]
thank you.

Please submit a pull request if possible ?

**Comment by RemiArnaud** [comment]
closing as no PR was provided. re-open as needed
