### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [KhronosGroup/OpenCOLLADA#403]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") like the following.
* [ExtraDataElementHandler](https://github.com/KhronosGroup/OpenCOLLADA/blob/f4b31b4327b0eaaf539f57c618c39be83331aebd/COLLADASaxFrameworkLoader/src/COLLADASaxFWLExtraDataElementHandler.cpp#L27 "Destructor for ExtraDataElementHandler")
* [IFilePartLoader](https://github.com/KhronosGroup/OpenCOLLADA/blob/f4b31b4327b0eaaf539f57c618c39be83331aebd/COLLADASaxFrameworkLoader/src/COLLADASaxFWLIFilePartLoader.cpp#L33 "Destructor for IFilePartLoader")
* [OgreWriter::writeVisualScene](https://github.com/KhronosGroup/OpenCOLLADA/blob/f4b31b4327b0eaaf539f57c618c39be83331aebd/dae2ogre/src/DAE2OgreOgreWriter.cpp#L117 "OgreWriter::writeVisualScene function")

**Comment by RemiArnaud** [comment]
Please submit pull request

thanks

**Comment by RemiArnaud** [comment]
closing this as no PR was provided. please re-open as needed
