### ISSUE TITLE
Loading Failure - 3DS Max Design 2014

### ISSUE THREAD

**Issue by cprettyman** [KhronosGroup/OpenCOLLADA#404]
Hi

I just downloaded and installed ColladaMaxNew.dle, but I get two erros when launching Max.  Im not sure if this is the reason, but I am running 3DS Max Design (the version that ships with Autodesk's AEC Suites, instead of the Media and Entertainment Suites.  

![image](https://cloud.githubusercontent.com/assets/17343739/13186615/03daf116-d715-11e5-9f0c-a3f4d4d71b23.png)

![image](https://cloud.githubusercontent.com/assets/17343739/13186634/19a20304-d715-11e5-9c02-63563e8eef2d.png)

**Comment by RemiArnaud** [comment]
I'm not familiar with AEC Suites - Looking at the list of Autodesk products, which one is it ?

<img width="231" alt="screen shot 2016-03-04 at 5 05 10 pm" src="https://cloud.githubusercontent.com/assets/142521/13544501/61da5c22-e22b-11e5-8eba-5f46b40285d7.png">

**Comment by RemiArnaud** [comment]
demangler says missing symbol is public: 
void __cdecl morphChannel::buildFromNode(class INode * __ptr64,int,int,int) __ptr64

FYI - online C++ Demangler http://d.fuqu.jp/c++filtjs/

**Comment by RemiArnaud** [comment]
so that symbol is in morpher.dlm, which is an optional module for 3dsmax. Can you install it with 3dsMax Design 2014?

**Comment by RemiArnaud** [comment]
@cprettyman can you test the collada Max plugin without morph support as built by this PR - https://github.com/KhronosGroup/OpenCOLLADA/pull/427

**Comment by RemiArnaud** [comment]
the SP5 version of the MAX 2014 exporter should fix that problem.
Can you give it a try?

go to opencollada.fl4re.org 
look for folder: PULL_REQUEST#445/COLLADAMax/2016-06-20_11-48-08_#266

download and install the MAX 2014 SP5 release version


Thanks

**Comment by RemiArnaud** [comment]
@cprettyman - the 2014 SP5 special build has been merged, and this should fix this issue. 
please test version 1.6.19 and re-open this issue if it is not fixed.
