### ISSUE TITLE
Feature : Update Existing Scene

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#41]
It would be excellent if the importers supported updating of existing scene 
files. By that I mean if there were an option to import a dae and state 
that you wanted the contents of the dae to be used to either:

A. merge into the existing scene
B. update nodes where names are the same and add anything new that doesn't 
already exist.
C. only update the current scene nodes and not add anything new to the 
scene.

This can be an incredibly useful feature (specifically for animation)

Our primary focus is with 3dsmax.

Great project you guys have here.

Cheers

Kyle<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=76</p><hr/><h2>earlier comments</h2>
<p><strong>opencollada2@gmail.com said, at 2011-01-20T09:07:53.000Z:</strong></p>
<p>Seem to be a cool idea, but has very low priority for us. </p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
