### ISSUE TITLE
Importer overwrites original .ma file.

### ISSUE THREAD

**Issue by tak3110** [KhronosGroup/OpenCOLLADA#413]
Hi.
I think this is not good.

I imported xxxx.dae. The original xxx.ma file was overwritten.

e.g.
<pre>
xxxx.ma
xxxx.dae
</pre>

Thanks.

**Comment by tak3110** [comment]
Please tell me why importFile   called at COLLADAMayaFileTranslator.cpp.
<pre>
namespace COLLADAMaya
{

    const String FileTranslator::ASCII_PATH_EXTENSION = ".ma";
    const String FileTranslator::ASCII_PATH_EXTENSION_DEBUG = ".opencollada.ma";
</pre>
<pre>
        // Set the imported file name and path.
//        COLLADABU::URI mayaAsciiFileURI ( mayaAsciiFileName );
        COLLADABU::URI mayaAsciiFileURI ( importFileName );
#ifdef NDEBUG
        mayaAsciiFileURI.setPathExtension ( ASCII_PATH_EXTENSION );
#else
        mayaAsciiFileURI.setPathExtension ( ASCII_PATH_EXTENSION_DEBUG );
#endif
        String mayaAsciiFileName = mayaAsciiFileURI.getURIString ();
        const char* cpMayaAsciiFileName = mayaAsciiFileName.c_str();
</pre>
<pre>
        MFileIO::importFile ( cpMayaAsciiFileName );
</pre>

**Comment by RemiArnaud** [comment]
yes, not good. 
I have no idea why it would use different naming/extension in debug or not.

What do you think should be done about this?

**Comment by tak3110** [comment]
Why importer call MFileIO::importFile ?

> What do you think should be done about this?

I think importer shuld use different naming same as debug mode.

**Comment by RemiArnaud** [comment]
@tak3110 
could you please review and then test https://github.com/KhronosGroup/OpenCOLLADA/pull/429 when its done building

**Comment by tak3110** [comment]
Thanks.

But, I could not build.

I think you should add a variable declaration like below.

>        COLLADABU::URI mayaAsciiFileURI ( importFileName );

**Comment by RemiArnaud** [comment]
sorry. I fixed the issue and the build did succeed.
Can you test the importer so we can merge this and close the issue ?

thanks!

**Comment by RemiArnaud** [comment]
@tak3110 any update on testing the fix?

**Comment by tak3110** [comment]
@RemiArnaud  Many thanks !

**Comment by RemiArnaud** [comment]
I assume this means it works. So merging then
