### ISSUE TITLE
Copy Textures option crashes Maya Mac

### ISSUE THREAD

**Issue by AlunAlun** [KhronosGroup/OpenCOLLADA#418]
When the Copy Textures option is selected in the Maya exporter on Mac, it crashes Maya immediately. If Maya is not forced to quit within a few seconds, the computer will freeze, requiring a hard reset.

The problem occurs with both Maya 2015 and 2016, for Mac. I have tested with several different scenes (from simple to complex). It does not occur on with Maya 2016 for PC, with the same scenes.

I am using 2016-04-11_11-53-33_#105.

**Comment by RemiArnaud** [comment]
@AlunAlun - could you please test the build in the PR (see link above) and see if this fixes the issue.

If you look at the PR, you'll see the path to the specific build in the fl4rebot comments:

binaries: look for folder: PULL_REQUEST#419/COLLADAMaya/mac/2016-04-13_01-02-11_#222 
inside http://opencollada.fl4re.com

**Comment by AlunAlun** [comment]
@RemiArnaud Yes that appeared to fix the problem. Maya no longer crashes and the texture files are copied correctly to the output folder. Many thanks!

**Comment by RemiArnaud** [comment]
fix was merged. it will be in v1.6.3
