### ISSUE TITLE
Animation exporting in 1.3.0 RC1 is inconsistent.

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#42]
<b>What steps will reproduce the problem?</b>
1. select any animated object.
2. export it with 'Sampling' turned on.
3. view the .dae file, it does not contain any animation data in the file.
4. re-export again, but with 'Sampling' TURNED OFF, don't bother looking at
dae file.
5. re-export a 3rd time, this time check the 'Sampling' box again (TURN IT ON).
6. examine the exported .dae file, it now contains animation data, where it
did not in step 2 using the SAME SETTINGS. I can reproduce this many times
consistenly.

<b>What is the expected output? What do you see instead?</b>
Expecting to see an animated model, no animation is present until you do an
export with sampling turned off, and then again with it turned back on.

<b>What version of the product are you using? On what operating system?</b>
Maya 2011
Windows 7
OpenCOLLADA 1.3.0 RC1

Thanks.

<b>Please provide any additional information below.</b>

<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=80</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
