### ISSUE TITLE
Locator in attached scene has animations but OpenCollada will not export them.

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#43]
<b>What steps will reproduce the problem?</b>
1. Load the attached file into Maya (I'm using Maya 2009)
2. Export the file as a DAE (Using the latest version of Open Collada)
3. Import/Open the DAE with any program including Maya and no animations on
the locator named rightInnerFlapController will be there.

<b>What is the expected output? What do you see instead?</b>

I expected the animations to export on the locator named
&quot;rightInnerFlapController&quot;.  They don't export.

<b>What version of the product are you using? On what operating system?</b>

Maya 2009 OpenCOLLADA_Maya_1.3.0rc1

<b>Please provide any additional information below.</b>

<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=85</p><hr/><h2>earlier comments</h2>
<p><strong>keeperof...@gmail.com said, at 2010-06-01T23:40:38.000Z:</strong></p>
<p>I forgot to mention that I created these nodes by importing an FBX file.  If you need
the fbx file I can supply it.</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
