### ISSUE TITLE
colladaMax: exporting animation corrupt the scene

### ISSUE THREAD

**Issue by corentinjaffre** [KhronosGroup/OpenCOLLADA#430]
Hi,
When I export an animation with colladaMaxNew with 3dsMax 2014, the resulting DAE has a corrupt hierarchy.
I seems that some lines are inserted at the wrong place.

This is what I got when I export the scene:
```
  </animation>
    <scene>
      <instance_visual_scene url="#MaxScene"/>
    </scene>
  </library_animations>
</COLLADA>
```

And this is what is working when I manually modify the DAE:
```
  </animation>
  </library_animations>
  <scene>
    <instance_visual_scene url="#MaxScene"/>
  </scene>
</COLLADA>
```

**Comment by RemiArnaud** [comment]
please send a max file so we can test and debug and fix.
remi (at) acm (dot) org

thanks

**Comment by RemiArnaud** [comment]
thanks for the model

**Comment by RemiArnaud** [comment]
@corentinjaffre - would you be so kind to test the artifact produced by the bot in the PR ?

**Comment by corentinjaffre** [comment]
The plug-in doesn't load (same issue as #417, maybe because of morpher again ?)

**Comment by RemiArnaud** [comment]
@corentinjaffre  -  can you test the SP5 version of the plugin available on opencollada.fl4re.com, following the path : PULL_REQUEST#445/COLLADAMax/2016-06-15_09-48-08_#265/win/x64/Release_Max2014_SP5

this plug-in should load fine with MAX2014 SP5.

**Comment by RemiArnaud** [comment]
@corentinjaffre - the fix was merged in master and building now
This will be build 1.6.22.

can you confirm bug is fixed ?

**Comment by RemiArnaud** [comment]
@corentinjaffre - please confirm. 
AFAIK the bug is fixed, and this issue will be closed.

**Comment by corentinjaffre** [comment]
On 27/06/2016 21:26, Rémi Arnaud wrote:
>
> @corentinjaffre <https://github.com/corentinjaffre> - please confirm.
> AFAIK the bug is fixed, and this issue will be closed.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/KhronosGroup/OpenCOLLADA/issues/430#issuecomment-228849073>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AF5dR2t-XM0-uhXHEiLrFOLuWy0TvRwMks5qQCQCgaJpZM4IVWcF>.
>

The plug-in is loading perfectly.
Thanks !
