### ISSUE TITLE
Installing plugin

### ISSUE THREAD

**Issue by Mbr24** [KhronosGroup/OpenCOLLADA#434]
Hi. I recently installed Maya 2015 and i'm not able to install the openCollada plugin. 
Gives an error in the version.. And i tried some of them.

**Comment by RemiArnaud** [comment]
That's surprising, we use Maya 2015 and the openCOLLADA plugin everyday, on
multiple machine.

Are you talking about the MAC or WIN version ?

**Comment by Mbr24** [comment]
Can you paste the link of the file that is supossed to be, please?

Its a Win version 64 bits.

Thank you.

**Comment by RemiArnaud** [comment]
following the folders from opencollada.fl4re.com, latest release, maya, windows X64, release Maya 2015
https://www.dropbox.com/sh/9nbx5or387t3rap/AAA4YAZhpBFzaNArET42xmqza?dl=0

**Comment by RemiArnaud** [comment]
closing issue, please re-open if you still have difficulties
