### ISSUE TITLE
missing geometry when importing into Maya 2010/2011

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#44]
<b>What steps will reproduce the problem?</b>
1. Run Maya 2010 or 2011.
2. Set the units to 'meters' in the preferences.
3. Import 'test_LOD0.dae' from the attached .zip file via the OpenCollada 
importer.
4. Notice that only the building is visible.  The ground and roads are 
missing.
5. Run Max 2010.
6. Import 'test_LOD0.dae' from the attached .zip file via the OpenCollada 
importer.
7. Notice that the entire building, the ground, and the road is visible.  
This is how it should look.
<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=86</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
