### ISSUE TITLE
Incompatible with Maya 2016LT?

### ISSUE THREAD

**Issue by monavari-lebrecht** [KhronosGroup/OpenCOLLADA#447]
Hi,

I am using a mac with Maya 2016LT SP4
I placed the mel files in /Users/Shared/Autodesk/maya/scripts and the .bundle file in /Users/Shared/Autodesk/maya/2016LT/plug-ins.
I downloaded the files in version 1.16.22. But when I try to load the plugin I get an error:
// Error: line 1: The plug-in is not compatible with this application (COLLADAMaya)

Is it because I am using the LT version of Maya?

Best regards,

Constantin

**Comment by RemiArnaud** [comment]
I don't know, maybe that's the SP4 which is the problem?
Like we just figured out we needed a MAX 2014 SP5 special version...

let's make sure it works with 2016 (classic) first..

**Comment by RemiArnaud** [comment]
We don't support LT I am afraid. I'm going to mark this as  'contribution requested' if someone want to add LT target.

**Comment by ivalylo** [comment]
AFAIK, Maya LT doesn't support third party plugins at all, it's part of its limitations.

**Comment by RemiArnaud** [comment]
ok, then its won't fix and closing
