### ISSUE TITLE
OpenCollada 1.3.x beta not loading for macos 10.5.8 & maya 2011

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#45]
I've put files under 2011, and I'm sure they are staying in appropriate folders. When I click &quot;loaded&quot; I get this error and plugin doesn't load:

// Error: dlopen(/Users/Shared/Autodesk/maya/2011/plug-ins/COLLADAMaya.bundle, 1): no suitable image found.  Did find:	/Users/Shared/Autodesk/maya/2011/plug-ins/COLLADAMaya.bundle: unknown required load command 0x80000022 (COLLADAMaya)<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=91</p><hr/><h2>earlier comments</h2>
<p><strong>hurt...@gmail.com said, at 2010-06-27T01:12:47.000Z:</strong></p>
<p>to make sure I've downloaded following:

"OpenCOLLADA 1.3.0beta for Maya 2011 Mac OS X 10.6 available now! http://bit.ly/9j21FG"

Does this mean you won't support leopard anymore ?</p><p><strong>hurt...@gmail.com said, at 2010-06-27T19:26:46.000Z:</strong></p>
<p>I've installed maya 2011 hotfix 2, nothing changed</p><p><strong>jare...@gmail.com said, at 2010-07-31T17:21:43.000Z:</strong></p>
<p>This is probably because the plugin was built for 10.6. I haven't tried it, but you can probably download the source code, change the target to 10.5 and recompile.</p><p><strong>jare...@gmail.com said, at 2010-08-04T04:52:57.000Z:</strong></p>
<p>Well, I've tried to compile this, but it just isn't happening. I changed every 2010 reference I could find in the project to 2011, but something is still trying to access 2010. Finally, I just created a symlink called 2010 to get around that. Then libtool kept throwing errors like: "file: -lxml2 is not an object file (not allowed in a library), so I've kinda given up. Any help compiling a 10.5.x version of this plugin would be great!</p><p><strong>opencollada said, at 2010-08-04T06:46:43.000Z:</strong></p>
<p>Attached is the latest XCode Project file that I used to build on 10.6. should build on 10.5, too. Take a look at the build instructions, too
http://code.google.com/p/opencollada/source/browse/#svn/trunk/COLLADAMaya/COLLADAMaya.xcodeproj
http://code.google.com/p/opencollada/source/browse/trunk/COLLADAMaya/BUILD_MAC.TXT</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
