### ISSUE TITLE
patch: remove Windows-1252 characters from OpenCOLLADA source code

### ISSUE THREAD

**Issue by ian-bruce** [KhronosGroup/OpenCOLLADA#458]
I wrote up a detailed explanation of this patch, but GitHub's crappy web interface apparently ate it, and I can't be bothered to retype it. I don't know why there isn't an email address I can just mail the patch to; anyway, use it however you see fit.

ian_bruce@mail.ru

[opencollada_0.1.0~20160714.0ec5063.diff.txt](https://github.com/KhronosGroup/OpenCOLLADA/files/405444/opencollada_0.1.0.20160714.0ec5063.diff.txt)

**Comment by RemiArnaud** [comment]
Can you create a pull request please.

**Comment by ian-bruce** [comment]
I'm not sure how I would do that, since I didn't use Git when developing the patch. It's just a standard unified-diff patchfile; it should be easy to apply to an unpacked source tree.

on Unix/Linux:

    $ cd opencollada/
    $ patch -p1 <../opencollada_0.1.0~20160714.0ec5063.diff

There must be some similar patch utility program on MS-Windows, but I'm not familiar with it.

As I pointed out in my original comment, which got eaten, one of the most common problem characters in the original source text is "\xEFBFBD". It turns out that this is not actually a Windows-1252 character, but the UTF-8 encoding of the Unicode "REPLACEMENT CHARACTER".

http://www.fileformat.info/info/unicode/char/0fffd/index.htm

It therefore appears that there was some previous attempt at automatic conversion of Windows-1252 characters to Unicode, which failed. C/C++ source code is not supposed to contain Unicode, anyway. Along with the actual Windows-1252 characters, I have replaced every instance of "REPLACEMENT CHARACTER" with a context-appropriate ASCII substitute.

As I also pointed out in my original comment, when reviewing this patch on a Unix/Linux system, the following environment variable setting is helpful:

    export LANG=C

**Comment by RemiArnaud** [comment]
I created a branch. Could you create the PR using this link:https://github.com/KhronosGroup/OpenCOLLADA/compare/misc/remove-windows-1252-characters?expand=1  ?

I can create the PR, but its your contribution, so I want it properly attributed.

BTW, this is a very good contribution, thanks for taking the time.

**Comment by RemiArnaud** [comment]
this was merged
