### ISSUE TITLE
Parsing crashes when compiled with Visual Studio 2010

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#46]
<b>What steps will reproduce the problem?</b>
1. Compile debug build of dae2ogre with Visual Studio 2010
2. Try convert any dae file
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
Crashes inside iterator cleanup in std::_Container_Base12::_Orphan_all().

<b>What version of the product are you using? On what operating system?</b>
Revision 750 compiled with Visual Studio 2010 in Windows 7

<b>Please provide any additional information below.</b>
Possible reason: New Visual Studio has added more error checking to std libs. It enables iterator cleanup when iterator debug level is 2. Which is now default in debug build. This adds iterator info to string and makes string destructor brake if it's illegally constructed or memcpyed.
<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=92</p><hr/><h2>earlier comments</h2>
<p><strong>jean.sr...@gmail.com said, at 2010-09-01T15:09:10.000Z:</strong></p>
<p>The problems is in GeneratedSaxParserTemplateBase.h:318
The constructor of the object DataType cannot called by memcpy() or malloc(). The good way to do this is to use a "placement new" operator.
The attached patch should do the trick.</p><p><strong>stepan.h...@gmail.com said, at 2010-10-09T16:19:36.000Z:</strong></p>
<p>If confirmation is needed, yes, the bug is real and the patch fixes it.

And if two liner feels like overdesign, here's oneliner :)</p><p><strong>virgile....@gmail.com said, at 2010-11-12T08:35:09.000Z:</strong></p>
<p>This probably happens somewhere else, I have the same issues but this fix doesn't change anything (this piece of code is not even called before the crash happens).

Going to take a quick look.</p><p><strong>virgile....@gmail.com said, at 2010-11-12T09:17:22.000Z:</strong></p>
<p>Found the problem.
In COLLADASaxFWLColladaParserAutoGen14Private.cpp:3284 :

const accessor__AttributeData accessor__AttributeData::DEFAULT = {0, 0, 0, 0, 1};
Initializing a struct containing a std::string (non-POD) as a POD struct.

Same probably applies to COLLADASaxFWLColladaParserAutoGen15Private.cpp

Easy workaround is to make a static function to create it, or add constructor/destructor to this class so that POD initialization is not needed anymore.</p><p><strong>opencollada2@gmail.com said, at 2011-01-18T15:40:01.000Z:</strong></p>
<p>Thanks for providing the patches. 

I have applied the two liner in r807.

The issue concerning the non-POD struct requires adjustments to our generator, which needs to be postponed for now.</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
