### ISSUE TITLE
Morph Target Export bug

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#47]
<b>What steps will reproduce the problem?</b>
Export a morph target mesh from Maya2010 using COLLADAMaya 1.2.2.674 exporter.

<b>What is the expected output? What do you see instead?</b>
It should deform such that the mesh is still consistent. Instead the mesh will deform and holes will show as it does.

<b>What version of the product are you using? On what operating system?</b>
Maya 2010, COLLADAMaya 1.2.2.674, Windows XP
<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=95</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
