### ISSUE TITLE
Maya LT 2016

### ISSUE THREAD

**Issue by SteveArt** [KhronosGroup/OpenCOLLADA#478]
I tried to use the 2016 Open Collada Plugin with Maya LT 2016 but I get a compatibility error.

// Error: line 1: The plug-in is not compatible with this application (COLLADAMaya)

Should it work or is it only compatible with normal Maya?

**Comment by RemiArnaud** [comment]
as the plugin said unfortunately.
you can try to get a SDK for Maya LT and see if you can compile the plug-in
(and make changes?)

**Comment by mflux** [comment]
I'm also using Maya LT (much cheaper for game dev and web dev). It would be great if this supported Maya LT. I'm using collada export in order to then export to GLTF, but MayaLT only converts to FBX so the current process is Maya->FBX->DAE->GLTF which is pretty bad.

**Comment by RemiArnaud** [comment]
Autodesk says you cannot write plugins for LT
http://www.autodesk.com/products/maya/compare/compare-products
Go talk to Autodesk.
