### ISSUE TITLE
Bake animation does not work with maya 2011 64bit, operCollada 1.3.0rc1

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#48]
<b>What steps will reproduce the problem?</b>
1. Open Maya 2011 64bit.
2. Create joints, rig them so they controlled by objects with constrains.
3. Create animation on control objects (not on joints).
4. Try to export with &quot;bake transforms&quot;.

<b>What is the expected output? What do you see instead?</b>

You will have no baked animation. Just the first frame.

<b>What version of the product are you using? On what operating system?</b>

Windows 7 64bit, Maya 2011 64bit, OpenCOLLADA_Maya_1.3.0rc1.

<b>Please provide any additional information below.</b>

Usuallu you see how currentTime indicator runs through time slider, bakeing all keyframes. Now it does not happening. And you dont have animation in dae-file after export.

script editor reads (paths deleted by *****):

===========================
file -force -options &quot;bakeTransforms=1;relativePaths=0;copyTextures=0;exportTriangles=1;cgfxFileReferences=0;isSampling=1;curveConstrainSampling=0;removeStaticCurves=1;exportPolygonMeshes=1;exportLights=1;exportCameras=1;exportJointsAndSkin=1;exportAnimations=1;exportInvisibleNodes=0;exportDefaultCameras=0;exportTexCoords=1;exportNormals=1;exportNormalsPerVertex=1;exportVertexColors=1;exportVertexColorsPerVertex=1;exportTexTangents=1;exportTangents=1;exportReferencedMaterials=0;exportMaterialsOnly=0;exportXRefs=0;dereferenceXRefs=1;exportCameraAsLookat=0;cameraXFov=0;cameraYFov=1;doublePrecision=0;&quot; -type &quot;OpenCOLLADA exporter&quot; -ea &quot;D:/*****/tanya.dae&quot;;
fileCmdCallback;
about -application;
// Result: maya // 
about -product;
// Result: Maya 2011 // 
about -version;
// Result: 2011 Hotfix 2 x64 // 
about -cutIdentifier;
// Result: 201006030309-775258 // 
about -osv;
// Result: Microsoft Windows 7 Ultimate Edition, 64-bit Windows 7  (Build 7600)
 // 
file -q -ns;
// Result: Pioneer_Animated_4 // 
file -q -exn;
// Result: D:/*******/tanya.mb // 
currentUnit -q -linear -fullName;
// Result: meter // 
file -q -ns;
// Result: Pioneer_Animated_4 // 
// Error: Export of constraints not supported: bn_Head_01_orientConstraint1 // 
// Error: Export of constraints not supported: bn_l_Hand_01_orientConstraint1 // 
// Error: Export of constraints not supported: bn_l_Collar_01_orientConstraint1 // 
// Error: Export of constraints not supported: bn_r_Hand_01_orientConstraint1 // 
// Error: Export of constraints not supported: bn_r_Collar_01_orientConstraint1 // 
// Error: Export of constraints not supported: bn_l_Foot_01_orientConstraint1 // 
// Error: Export of constraints not supported: bn_r_Foot_01_orientConstraint1 // 
memory -he;
// Result: 620.914063 // 
memory -fr;
// Result: 910.402344 // 
memory -pf;
// Result: 713497 // 
// Result: D:/*****/tanya.dae // <p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=96</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
