### ISSUE TITLE
Crash when opening a collada scene on 3dsMax 2014

### ISSUE THREAD

**Issue by corentinjaffre** [KhronosGroup/OpenCOLLADA#481]
Hi,

I try to open a collada scene with 3dsMax 2014 with the latest COLLADAMax plug-in, and 3dsMax crashes when loading the scene.
Is there a .log somewhere, or anything which could help me pinpoint the problem?
The .dae file open fine with the autodesk fbx/collada plug-in, by the way.

Corentin

**Comment by RemiArnaud** [comment]
please make sure you use the SP5 version of the exporter if you use 2014 with SP5?

can you confirm?

**Comment by corentinjaffre** [comment]
I confirm: I'm using the 1.6.33, x64, 3dsmax2014 SP5 plug-in.

**Comment by RemiArnaud** [comment]
can you provide the offending dae document ?
remi (at) acm (dot) org

**Comment by corentinjaffre** [comment]
Unfortunately, I can't share any scene, as they are from my client...

**Comment by RemiArnaud** [comment]
@mycheckgithub @Birdy3D  do you know where log / errors would be available ?
Maybe using a debug build of the plugin would help ?

How can we help tracking and fixing this crash ?
maybe @mycheckgithub can get in touch with @corentinjaffre and figure out a remote debug session ?

**Comment by mycheckgithub** [comment]
I tested with a simple dae test and i have no crash during import with colladaMax plugin.

Can you reproduce this crash with a simple scene you created in maya, then exported by colladaMax and re-imported by colladaMax ?

**Comment by RemiArnaud** [comment]
@corentinjaffre  - have Franck sign NDA with customer, and provide him with scene ?

**Comment by RemiArnaud** [comment]
No feedback in over a month
