### ISSUE TITLE
Camera target field contains name not ID of corresponding node

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#49]
<b>What steps will reproduce the problem?</b>
1. Create a scene with a targeted camera
2. Export using any version of OpenCollada
3. Check the camera -&gt; extra -&gt; technique -&gt; target field

What I expect to find there is the ID of the node that stores target matrix. What I find is the name of the field, which I can't resolve with. 

&lt;library_cameras&gt;
    &lt;camera id=&quot;Camera01-camera&quot; name=&quot;Camera01&quot;&gt;
      &lt;optics&gt;
        &lt;technique_common&gt;
          &lt;perspective&gt;
          ....
          &lt;/perspective&gt;
        &lt;/technique_common&gt;
      &lt;/optics&gt;
      &lt;extra&gt;
        &lt;technique profile=&quot;OpenCOLLADA3dsMax&quot;&gt;
          &lt;target&gt;#Camera01.Target&lt;/target&gt;
        &lt;/technique&gt;
      &lt;/extra&gt;
    &lt;/camera&gt;
  &lt;/library_cameras&gt;

and

&lt;node id=&quot;node-Camera01.Target&quot; name=&quot;Camera01.Target&quot;&gt;
    &lt;matrix&gt;...&lt;/matrix&gt;
&lt;/node&gt;

This occurs on the latest stable build available for download via the website (1.2.5) and the latest download from Google Code (1.3.0rc).<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=98</p><hr/><h2>earlier comments</h2>
<p><strong>opencollada said, at 2010-08-06T06:31:18.000Z:</strong></p>
<p>Verified. The OpenCOLLADA3dsMax profile is no yet fully specified.</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
