### ISSUE TITLE
OpenMaya: "Static Curve Removal" option sets constant channels of animations to 0

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#50]
<b>What steps will reproduce the problem?</b>
1. Open Maya, create a scene with an object with non-zero Y position
2. Put some animation keys for that object at different frame numbers, by only translating it over X and Z axes
3. Export with &quot;Static Curve Removal&quot; option on

<b>What is the expected output? What do you see instead?</b>
Channel Y of the animation is set to 0 for each exported key, which is incorrect.

<b>What version of the product are you using? On what operating system?</b>
OpenCOLLADA Maya 1.3.0, RC1
Maya 2011 x64 Hotfix 3 on Windows 7 x64 Professional (EN)

<b>Please provide any additional information below.</b>
Proposed solutions:
- Write the true value of a constant channel, even if it's constant, when the two other components are non-constant (preferred solution)
- Change the &lt;channel&gt; tag of exported animation so that it binds only the X and Z channels (supported by the specs but some importers may not like it)
- Export two separate animations for X and Z (works but creates larger files)<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=99</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
