### ISSUE TITLE
Vertex color indexes are not exported correctly

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#51]
In GeometryPolygonExporter::writeVertexIndices, the Idx from vertex attributes is used to lookup color set name despite the fact it is always set to -1. The result is index is always 0. I've hardcoded the index to be 0 for color, and it fixes the problem, but only works with on colorset.

Any ideas on how to fix it properly?

Code that behave incorrectly :
case COLLADASW::COLOR:
{
    MString&amp; colorSetName = mColorSetNames[vertexAttributes.getIdx()];
    int colorIndex = 0;
    {
#if MAYA_API_VERSION &gt;= 700
        fnMesh.getColorIndex ( polyIndex, iteratorVertexIndex, colorIndex, &amp;colorSetName );
#else
        fnMesh.getFaceVertexColorIndex ( polyIndex, iteratorVertexIndex, colorIndex );
#endif
    }
    primitivesBasePoly-&gt;appendValues ( colorIndex );
}
break;<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=100</p><hr/><h2>earlier comments</h2>
<p><strong>julien.hamaide said, at 2010-08-11T09:07:43.000Z:</strong></p>
<p>Here's a patch that correct this bug</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
