### ISSUE TITLE
latest binary could not download

### ISSUE THREAD

**Issue by p0mp0k0** [KhronosGroup/OpenCOLLADA#511]
latest binary download url http://opencollada.fl4re.com/ could not access

**Comment by RemiArnaud** [comment]
I just tried. Everything looks fine  

Here's a direct link I tested

https://www.dropbox.com/sh/jssp45b88jkcoql/AABVu4K2fUp77e8xj-bG3THka/COLLADAMaya/win/v1.6.45/x64/ReleasePlugin2017/COLLADAMaya.mll

**Comment by p0mp0k0** [comment]
Unfortunately, I still can not access the original url.
Using chorme, echo error message about NET::ERR_CERT_COMMON_NAME_INVALID.
Using IE11,  is timeout.
But your link url I can access by IE, so please give me the actual url for 3DSMax 2017.
Thanks.

**Comment by RemiArnaud** [comment]
https://www.dropbox.com/sh/jssp45b88jkcoql/AABLcdSf5xVZIfAibyLVFvhqa/COLLADAMax/v1.6.45/x64/Release_Max2017?dl=0
