### ISSUE TITLE
Can OpenCOLLADA for 3ds Max, convert from stl to open collada dae

### ISSUE THREAD

**Issue by Priyanka9891** [KhronosGroup/OpenCOLLADA#515]
Can OpenCOLLADA for 3ds Max, convert from stl to open collada dae?

**Comment by Priyanka9891** [comment]
Please also let me know if this software is for free

**Comment by RemiArnaud** [comment]
OpenCOLLADA exports models loaded in 3dsmax, so if you can load Stl in max, you can export them back as collada

The software is free and open source.
