### ISSUE TITLE
Patch / crash when exporting morphs in 3ds max

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#52]
<b>What steps will reproduce the problem?</b>
1. Create an object with a morph controller. Important: The morph targets should not be nodes in the scenes which the morph controller references. Instead the morph controller should &quot;own&quot; the morph targets. 
2. Try to export the model in 3ds max 2010.

<b>What is the expected output? What do you see instead?</b>

Expected: Model is exported properly.
Actual: 3ds max crashes hard. This is because an assert is triggered at

ColladaMaxControllerExporter.cpp:123
assert( geometryExportNode );

Attached is a patch which solves the problem for me. I am not sure if this is the real fix or whether the real fix should be done somewhere else.

Patch discussion (2 small changes):

Change 1: The initial pose is not in the list of exported objects. Thus the assert in question fails. This should not happen. The patch adds code to check for this condition and inserts the initial pose into the list of exported objects if necessary.

Change 2: A small fix to properly escape morph target ids.

On demand I can provide an example file reproducing the problem.
<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=101</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
