### ISSUE TITLE
Issues importing DAE animation

### ISSUE THREAD

**Issue by NewHolland** [KhronosGroup/OpenCOLLADA#521]
![maya_anim_issue_v001](https://cloud.githubusercontent.com/assets/28796400/26229928/89f5ddfe-3c88-11e7-970c-ddea9db51f78.jpg)
Hi
We've been exporting DAE data from AXYZ Anima 2.5.

The data imports into Blender okay, yet importing into Maya is not fully successful. We can see the mesh, it has shaders/textures, and is bound to the skeleton. Yet the animation does not attach.

We've tried Maya 2015/2016/2017 and ColladaMaya 1.6.2/1.6.47. The results are the same.

Attached is the Collada test data (1 man, walking for 10 frames).

NOTE: Please rename the attached file; it is a ZIP file.

All help appreciated.

clinton

**Comment by RemiArnaud** [comment]
If you have a mac, can you try it in preview?

**Comment by NewHolland** [comment]
Hi Remi

Mac Preview plays the animation (but is untextured possibly owing to pathing issues).

We also tried it in Cinema4d on the Mac, and it gave the same result as Maya; no motion.

**Comment by RemiArnaud** [comment]
Definitely a problem with the importer in those tools then, but maybe it's something that can be tweaked in the dae itself to work around importer bug.
I suggest you find a working dae on maya. A simple one, exported from maya OpenCOLLADA, imported back. There are options in exporter to play with if needed. 
Once we have a working model, we can compare the internal structure and see what the problem may be. 

Maybe it does not like clips, or require a single clip, some of those are easy to hack in your dae.

**Comment by NewHolland** [comment]
Hi Remi

Interesting that you suggest that, as we've been doing something along those lines since I first posted.

We managed to get a working DAE in Maya by round tripping through Blender. To be honest, it's our 'backup' workflow, although going straight from Anima>Maya is far preferred for a few reasons (mainly owing to scene translation).

Attached is the same scene, but exported from Blender. It works in Maya. 

I've looked at the two quite closely, and the only thing I can detect is an additional 'NODE' layer wrapping around the skeleton description. I'm sure there are other subtleties, but I'm new to the file format. I tried a bit of hacking but the only success I've had is to crash Maya!

![maya_anim_issue_v002_via_blender](https://cloud.githubusercontent.com/assets/28796400/26236577/62dc6d7e-3cb4-11e7-8537-6c14e38d23da.jpg)

**Comment by NewHolland** [comment]
Hi Remi

I wonder if you had any additional thoughts about the Blender DAE file and how it compares to the Maya file?

My efforts on modifying the Maya DAE are yet to bear any fruit.

**Comment by RemiArnaud** [comment]
I took a look in the Anima exported file, and it has several issues:

the order of elements inside <animation> is strict
it has to be all the <source> then <sampler> and then <channel>

any xml schema validation tools would tell you that there is a problem
I use https://sourceforge.net/projects/colladarefinery/files/COLLADA%20Coherency%20Test/Collada%20Coherency%20Test%201.3/

It looks like the exporter as concatenated several animations into a single <animation> element (there is no 's' in <animation>). So you would have to split the <animation> element into multiples (like in the blender exported document.

Also, noticed the size of 'INTERPOLATION' is wrong, it should be 10 elements

can you report those bugs to Anima author ?

Note that the blender exported file also has problems : 

ERROR: CHECK_schema Error   msg=Element '{http://www.collada.org/2005/11/COLLADASchema}library_images': Missing child element(s). Expected is one of ( {http://www.collada.org/2005/11/COLLADASchema}asset, {http://www.collada.org/2005/11/COLLADASchema}image ).

**Comment by NewHolland** [comment]
Hi Remi

Thanks for your valuable input. I'll report these bugs to the developer of Anima. I understand they are intending to make a point release very shortly, so hopefully this can make it in there.

Much appreciated.
