### ISSUE TITLE
Exporter fails to load in 3ds Max 2018 64bits

### ISSUE THREAD

**Issue by xtassin** [KhronosGroup/OpenCOLLADA#525]
Plugin fails to load with error "procedure could not be found".

**Comment by RemiArnaud** [comment]
Please use supported version. 2018 not yet supported

Regards
-- Rémi

**Comment by ufoxp** [comment]
Is this still crashing with https://github.com/KhronosGroup/OpenCOLLADA/releases/tag/v1.6.59?

**Comment by RemiArnaud** [comment]
Thank you @ufoxp !

**Comment by RemiArnaud** [comment]
no feedback - considering this fixed. please open new bug if max2018 is still an issue
