### ISSUE TITLE
Bundles vulnerable copy of Expat - please update to 2.2.5

### ISSUE THREAD

**Issue by hartwork** [KhronosGroup/OpenCOLLADA#535]
Hi!

This repository [bundles an outdated vulnerable copy of Expat 2.0.1](https://github.com/KhronosGroup/OpenCOLLADA/tree/master/Externals/expat/lib). Please update your copy to version 2.2.4 with the latest security fixes. A change log with details is available at https://github.com/libexpat/libexpat/blob/master/expat/Changes . Thank you!

Best

&nbsp;
Sebastian

**Comment by hartwork** [comment]
Any news or issues with updating?

**Comment by RemiArnaud** [comment]
Is there a pull request?

**Comment by hartwork** [comment]
Not that I knew, no. For someone to make some, understanding of OpenCOLLADAs build system and the list of supported platforms and compilers is needed.

**Comment by RemiArnaud** [comment]
Nope you don't need to compile anything yourself. 

You can submit a PR and jenkins will build for us. It would be way to much work for anybody to compile for all those versions of all those tools for all those platforms....

Hopefully upgrading the library won't break the build. Otherwise, we'd have something to start with.

**Comment by hartwork** [comment]
You would still need to inspect the build system so that detection of high entropy sources like `getrandom` is done somewhere if you don't use nested configure and so on, the new `EXPAT_ENTROPY_DEBUG=1` may be handy for debugging. I'm happy to help with any issues or questions that you run into in the process.

**Comment by hartwork** [comment]
Closing to keep https://github.com/issues clean for myself…
