### ISSUE TITLE
Transparency help

### ISSUE THREAD

**Issue by recp** [KhronosGroup/OpenCOLLADA#537]
Actually COLLADA spec provides transparency formulas in "Getting Started with FX" section, 
I'm going to render the imported transparency enum but not sure how to do that with SINGLE PASS. 

For example:
```text
In A_ONE opaque mode:
result.r = fb.r * (1.0f - transparent.a * transparency) + mat.r * (transparent.a * transparency)
result.g = fb.g * (1.0f - transparent.a * transparency) + mat.g * (transparent.a * transparency)
result.b = fb.b * (1.0f - transparent.a * transparency) + mat.b * (transparent.a * transparency)
result.a = fb.a * (1.0f - transparent.a * transparency) + mat.a * (transparent.a * transparency)

In RGB_ONE opaque mode:
result.r = fb.r * (1.0f - transparent.r * transparency) + mat.r * (transparent.r * transparency)
result.g = fb.g * (1.0f - transparent.g * transparency) + mat.g * (transparent.g * transparency)
result.b = fb.b * (1.0f - transparent.b * transparency) + mat.b * (transparent.b * transparency)
result.a = fb.a * (1.0f - luminance(transparent.rgb) * transparency) + mat.a  (luminance(transparent.rgb) * transparency)

luminance = (color.r * 0.212671) + (color.g * 0.715160) + (color.b * 0.072169)
...
```
I have found a cool web tool about blending (http://www.andersriggelsen.dk/glblendfunc.php)
but I couldn't map formulas in COLLADA to any of these blending equations.

Can we achieve transparency by something like this, by mapping fourmulas in COLLADA to appropriate functions and parameters:
```C
glEnable(GL_BLEND);
glBlendFuncSeparate(GL_SRC_ALPHA, 
                    GL_ONE_MINUS_SRC_ALPHA, 
                    GL_SRC_ALPHA, 
                    GL_ONE_MINUS_SRC_ALPHA);
glBlendEquation(GL_FUNC_ADD);
```

(1) Is it possible to do the COLLADA transparency with OpenGL blending facilities like above
or
(2) Should I first render a frame into image then get it as texture and apply this formula in separate shader manually as second rendering pass? 

(1) or (2) ? 

Thanks

**Comment by RemiArnaud** [comment]
Nowadays programmers do not use OpenGL fixed function to write rendering engines. Even if you stick to those obsolete APIs, you still have to sort objects between transparent and opaque to render correcly.
