### ISSUE TITLE
dae image parser

### ISSUE THREAD

**Issue by pasu** [KhronosGroup/OpenCOLLADA#538]
hi, here is my issue：

when I convert osgb to dae, there is no "library_images" element, but under "library_effects"- "effect" - "profile_COMMON", you can find "image" element.

I can open this dae through SimLab, and I debug and find OpenCOLLADA does not consider this condition, so I fixed it.

Attachments are the original dae file and related source codes. Thanks for your suggestion.
[Tile_001_001.dae.txt](https://github.com/KhronosGroup/OpenCOLLADA/files/1114447/Tile_001_001.dae.txt)

[COLLADASaxFWLLibraryEffectsLoader.cpp.txt](https://github.com/KhronosGroup/OpenCOLLADA/files/1114448/COLLADASaxFWLLibraryEffectsLoader.cpp.txt)
[COLLADASaxFWLLibraryEffectsLoader.h.txt](https://github.com/KhronosGroup/OpenCOLLADA/files/1114450/COLLADASaxFWLLibraryEffectsLoader.h.txt)
[COLLADASaxFWLLibraryEffectsLoader14.cpp.txt](https://github.com/KhronosGroup/OpenCOLLADA/files/1114449/COLLADASaxFWLLibraryEffectsLoader14.cpp.txt)

**Comment by pasu** [comment]
[COLLADASaxFWLLibraryEffectsLoader14.h.txt](https://github.com/KhronosGroup/OpenCOLLADA/files/1114460/COLLADASaxFWLLibraryEffectsLoader14.h.txt)

**Comment by recp** [comment]
In COLLADA 1.4 spec image's parents are:

library_images, 
effect, 
profile_CG, 
profile_GLSL, 
profile_COMMON, 
profile_GLES, 
technique (FX) (in profile_CG, profile_COMMON, profile_GLES, profile_GLSL)

1.5 allows image existence only in library_images which may confuse you

**Comment by pasu** [comment]
well ,as you say, I find "image" node whose parents are effect, but EffectsLoader14 does not parser "image".
Am I right?
I think it could be better to consider this situation in version 1.4
so we can bridge the gap between osg and gltf, and that is the basis of 3dtiles
Finally, thanks for your explanation, Have a good weekend :+1:

**Comment by pasu** [comment]
@recp :+1:
