### ISSUE TITLE
Maya 2011 on OSX crashes on export with 1.3 osx beta

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#54]
Beta contents of COLLADAMaya_1_3_0.tar.bz2 that was going around, 
Snow Leopard 10.6.3, Macbook pro 2.66 i7, 4GB Ram.
Maya 2011 hotfix 3

<b>What steps will reproduce the problem?</b>
1. I create and texture a model.
2. I export my selection with basic options for a model (polys, normals, textures, relative paths).
3. I choose the path for my files and go. Spinning beachball of death. Consistently reproducable. Also happened before hotfix application.

<b>What is the expected output? What do you see instead?</b>

Expect completion of export. See app freeze with beachball and need to force quit.

<b>What version of the product are you using? On what operating system?</b>
COLLADAMaya_1_3_0.tar.bz2, Maya 2011 hotfix 3 on OSX 10.6.3

<b>Please provide any additional information below.</b>

Thanks guys!<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=103</p><hr/><h2>earlier comments</h2>
<p><strong>marriner...@gmail.com said, at 2010-12-15T15:42:54.000Z:</strong></p>
<p>I am also having this same issue.  On the very rare occasion it will export the .dae file before crashing Maya.</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
