### ISSUE TITLE
Download links are broken for latest Binaries

### ISSUE THREAD

**Issue by Decency2** [KhronosGroup/OpenCOLLADA#541]
Link  just goes here "http://opencollada.fl4re.com/" which is down.  Anywhere else we can locate these files, or can the links be fixed?

**Comment by RemiArnaud** [comment]
https://www.dropbox.com/sh/wozct8jvzoa6rn8/AAC95Q0D5fNA-42FME4nEAz6a

**Comment by RemiArnaud** [comment]
@mbarnes-sb @krunal-patel-fl4re the dns is broken.

**Comment by Decency2** [comment]
Thanks, that does work.  Has anyone had luck exporting one of these files from 3ds Max and importing into Sketchup?  Just won't work on my machine no matter what settings I select.

**Comment by RemiArnaud** [comment]
download links have been replaced with packages stored in the github release tab
https://github.com/KhronosGroup/OpenCOLLADA/releases
