### ISSUE TITLE
Can't install 1.2.2 on Snow Leopard 10.6.3

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#55]
<b>What steps will reproduce the problem?</b>
1. Download 1.2.2 from the opencollada website as the google code project has no link for OSX 
2. I have 2011 and 2010 installed on 10.6.3. I double click COLLADAMayaPlugins.mpkg
3. Install button is greyed out, so i click change install location and choose my hard drive

<b>What is the expected output? What do you see instead?</b>

An active install button. Instead, it's greyed out.

<b>What version of the product are you using? On what operating system?</b>
1.2.2 on Snow Leopard 10.6.3. Maya 2010 and 2011 installed.

<b>Please provide any additional information below.</b>

<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=104</p><hr/><h2>earlier comments</h2>
<p><strong>2ofheart...@gmail.com said, at 2011-01-26T18:52:52.000Z:</strong></p>
<p>Also having this issue, any resolution?</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
