### ISSUE TITLE
Exported DAE model part of it became transparent.

### ISSUE THREAD

**Issue by xieweizhi** [KhronosGroup/OpenCOLLADA#551]
Here is the model. As you can see, the right side of the sofa becomes transparent.

<img width="1091" alt="screen shot 2017-10-11 at 12 27 22 pm" src="https://user-images.githubusercontent.com/1779863/31422406-f42e065a-ae12-11e7-970c-5e96c68038d2.png">

**Comment by RemiArnaud** [comment]
hum, there are no models attached. also no information about what tools was used, (max?maya?) what operating system, what version and how the model was opened with.

**Comment by xieweizhi** [comment]
@RemiArnaud , Thanks for your time. I think it's fixed. It relates to some settings when it's exported.
