### ISSUE TITLE
Tangents and binormals set start at 1

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#56]
I see texture coordinate sets start at 0 now, see this change:

http://code.google.com/p/opencollada/source/detail?r=750

However, the sets for TEXTANGENT and TEXBINORMAL still start at 1, not 0. The fix is trivial if you look at the change already made for the TEXCOORD sets.<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=106</p><hr/><h2>earlier comments</h2>
<p><strong>Marcus.C...@gmail.com said, at 2010-08-24T10:30:07.000Z:</strong></p>
<p>The starting value of the set attributes is irrelevant as long as they are consistent within the content, i.e. if inputs of TEXCOORD and TEXTANGENT belong together then they must have the same set attribute value. There are enough open bugs on this issue to imply that vertex attributes are being mixed up by the code.</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
