### ISSUE TITLE
Exporting collada from blender with embedded textures (normal map)

### ISSUE THREAD

**Issue by Ninjabdou** [KhronosGroup/OpenCOLLADA#564]
Hi all, 
I'm trying to export files  from blender with textures: diffuse, specular and normal, when I import the model back in blender to check it, only diffuse and specular textures are included and not the normal.
Tried a trick found on stackexchange: changing the <bump> to <bump bumptype="NORMALMAP"> would solve the issue but unfortunately it did nothing.
I even tried exporting the model with only the normal  map without success.
Is there any way to make it work.
Thank you in advance

**Comment by RemiArnaud** [comment]
the blender import / export is a different product.

I searched the web to see where to report Blender bugs, and I found that link: https://developer.blender.org/maniphest/task/edit/form/1/
