### ISSUE TITLE
Clarification of "fx_common_color_or_texture_type" type

### ISSUE THREAD

**Issue by recp** [KhronosGroup/OpenCOLLADA#567]
Until now, I was assumed that **fx_common_color_or_texture_type** object can only contain COLOR or TEXTURE not both. Is it valid to have both color and texture  in **fx_common_color_or_texture_type** object e.g. **diffuse**, **emission**, **specular**... ?

If it is valid to have both then what should render engines do? Should I multiply color with texture like this:
```glsl
diffuse = diffuse.tex * diffuse.color
``` 

if only one of them can exists then I don't need to do anything because in shader there is something like this:

```glsl
\n#ifdef DIFFUSE_TEX\n
uniform sampler2D uDiffuseTex;
\n#elif defined(DIFFUSE_COLOR)\n
uniform vec4      uDiffuse;
\n#endif\n

/* ... */

\n#ifdef DIFFUSE_TEX\n
  diffuse = lightc * texture(uDiffuseTex, DIFFUSE_TEXCOORD) * Ld
\n#elif defined(DIFFUSE_COLOR)\n
  diffuse = lightc * uDiffuse * Ld
\n#else\n
  diffuse = lightc * vec4(1, 1, 1, 1) * Ld /* default diffuse */
\n#endif\n
```

otherwise I need minor changes 

I'm asking this because in glTF both baseColor and baseColorTexture can exists, they are multiplied in shader... 

thanks for clarification

**Comment by mbarnes-sb** [comment]
> If it is valid to have both then [...]?

No. See page 8-25 of the 1.4 spec

**Comment by recp** [comment]
@mbarnes-sb  thank you
