### ISSUE TITLE
mesh without primitives clarification

### ISSUE THREAD

**Issue by recp** [KhronosGroup/OpenCOLLADA#568]
Both 1.4 and 1.5 spec says:

>...  the <mesh> element may contain zero or more of the primitive elements `<lines>`, `<linestrips>`, `<polygons>`, `<polylist>`, `<triangles>`, `<trifans>`, and `<tristrips>`.

it says that "may contain zero" which means that mesh may not contain any primitives. 

if mesh has vertices and doesnt have any primitives, how can I render it then? 

For instance:

```xml
<mesh>
  <source id="box-Pos"/> 
  <vertices id="box-Vtx">
    <input semantic="POSITION" source="#box-Pos">
  </vertices>
</mesh>
```

Can I assume that if there is no primitives in mesh then it must be render as `<triangles>` like below?

```xml
<mesh>
  <source id="box-Pos"/>
  <vertices id="box-Vtx">
    <input semantic="POSITION" source="#box-Pos">
  </vertices>

  <!-- Can I assume that this primitive is default? -->
  <triangles>
    <input semantic="VERTEX" offset="0" />
  </triangles>
</mesh>
```

**Comment by RemiArnaud** [comment]
That would be a point cloud then.

**Comment by recp** [comment]
@RemiArnaud thanks for clarification, 

`<mesh>` doesn't have point primitives, by this way points will also be supported, great 🎉, I didn't know. This will help me to convert points in another format to COLLADA. 

According to 1.5 spec pdf,`symbol` attribute is required in `<instance_material> (geometry)` so current spec[s] cannot assign a `<material>` to points. The only way to set materials to points cloud is setting VERTEX colors right? If `symbol` would be valid in `<mesh>` we could assign a material to points or to whole mesh.
