### ISSUE TITLE
COLLADAFW::IWriter::writeImage() not being called for image declared in profile_COMMON

### ISSUE THREAD

**Issue by lasalvavida** [KhronosGroup/OpenCOLLADA#571]
From: https://github.com/KhronosGroup/COLLADA2GLTF/issues/129

```xml
<library_effects>
	<effect id="material_effect">
		<profile_COMMON>
			<image id="material_effect-image">
				<init_from>Tile.jpg</init_from>
			</image>
			...
		</profile_COMMON>
	</effect>
</library_effects>
```

Should create an image, but it does not. I believe this should be valid COLLADA:

![image](https://user-images.githubusercontent.com/2489570/39103354-4a9cad0e-4678-11e8-9ae0-2d7fa7240e45.png)

**Comment by RemiArnaud** [comment]
fixed in v1.6.63
