### ISSUE TITLE
Request: Export options could be stored in the registry

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#58]
Every time you export with OpenCOLLADA, the user options are reset to defaults. This is a minor irritation, since I don't find &quot;copy images&quot; particularly useful, and always want to use &quot;relative paths&quot;, for instance.

Could the dialogue box write its settings to the HKCU registry hive, or wherever is appropriate for plugins? That way we wouldn't have to change them each time.<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=108</p><hr/><h2>earlier comments</h2>
<p><strong>opencollada2@gmail.com said, at 2011-01-25T12:36:14.000Z:</strong></p>
<p>This feature is planed but not fully implemented yet.</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
