### ISSUE TITLE
3ds max, skin, pivots

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#59]
There's a problem with the ColladaMax exporter. It manifests when you have a mesh with a pivot point (doing $myobj.objectoffsetpos in maxscript gives something other than [0,0,0]).

The pivot is exported in the node graph, but it's also present in the skin's bind_shape_matrix. This leads to wrong transforms.

After I decided how to solve the problem, I will likely contribute another patch for this (in the next days).<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=109</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
