### ISSUE TITLE
New lines for source input on stride

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#60]
Source control programs (svn,mercurial,perforce) deal better with short lines, especially when it comes to changes.

Also short lines make eyeballing dae files easier.

To get round these shortcomings in source control and my eyeballs, it would  be nice to have source input arrays split on stride.

So instead of:

&lt;float_array id=&quot;geom-house-positions-array&quot; count=&quot;11616&quot;&gt;-8.148731 -6.126873 -1.801367 -8.088627 -6.126873 -1.720049 ----&gt; one long long line
&lt;technique_common&gt;
  &lt;accessor source=&quot;#geom-house-positions-array&quot; count=&quot;3872&quot; stride=&quot;3&quot;&gt;
    &lt;param name=&quot;X&quot; type=&quot;float&quot;/&gt;
    &lt;param name=&quot;Y&quot; type=&quot;float&quot;/&gt;
    &lt;param name=&quot;Z&quot; type=&quot;float&quot;/&gt;

We get:
&lt;float_array id=&quot;geom-house-positions-array&quot; count=&quot;11616&quot;&gt;
  -8.148731 -6.126873 -1.801367
  -8.088627 -6.126873 -1.720049
etc...

That is how the inbuilt max collada exporter separates it and I'm sure it's no coincidence but that is how fcollada separated it as well.

I'm sure it is still legal xml, only downside I can think of is it adds extra characters.

Any objections? <p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=112</p><hr/><h2>earlier comments</h2>
<p><strong>opencollada2@gmail.com said, at 2011-01-25T12:44:01.000Z:</strong></p>
<p>I think this would only be useful if it is made optional. In general COLLADA files are not read by humans. :) 

This has very low priority for us. Probably somebody wants to provide a patch? </p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
