### ISSUE TITLE
Wrong texture data exporting on Maya 2008

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#61]
<b>What steps will reproduce the problem?</b>
1.Open Maya 2008.
2.Create 2 planes on the scene.
3.Create a material with a cgFX with a diffuse texture on it.
4.Assign that material to one of the planes.
5.Create a material with the same cgFX (or a different one) with different diffuse texture on it. 
6.Assign this new material to the other plane.
7.Export the scene with the OpenCollada Exporter, version 1.3.0.741M

<b>What is the expected output? What do you see instead?</b>
The two planes are exported with different materials, but the texture is the same. The texture should be different, because we assigned different textures.

<b>What version of the product are you using? On what operating system?</b>
I'm using Maya 2008 with the OpenCollada exporter 1.3.0.741M on Windows XP.
The cgfxShader plugin version is 4.4 for Maya 2008.0 (Aug 3 2007)

<b>Please provide any additional information below.</b>
I have attached the maya file with the scene that I used to reproduce the bug.

Maybe I'm wrong, but looking to the source code of the exporter I think that the problem is in the function HwShaderExporter::setTexture inside the if:
if ( DagHelper::getPlugConnectedTo( shaderNode, attributeName, plug ) )

I believe this, because if I export the material with no texture linked and having a default texture in the cgFX, the exporter takes the default texture. 

<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=113</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
