### ISSUE TITLE
library_images does not contain every texture used in a CGFX shader

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#62]
<b>What steps will reproduce the problem?</b>
1. Create a material with a CGFX file that uses more than one absolute path texture.
2. Apply to an object
3. Export

<b>What is the expected output? What do you see instead?</b>

I expect to see each texture used have an entry in the library_images, and be correctly referenced from the appropriate material/effect/shader.

I see a single entry in library_images, and every material/effect references this one image.
EXCEPTION: if copy textures is set, then all textures correctly appear, however, they are not copied and so the path name is then wrong.

<b>What version of the product are you using? On what operating system?</b>

openCollada Maya ReleasePlugin2011 under windows XP
OpenCOLLADA_Maya_1.3.0rc1.7z

<b>Please provide any additional information below.</b>

it looks like the error is introduced on or around line 1130 of COLLADAMayaHwShaderExporter.cpp
Changing 

       COLLADASW::URI sourceFileUri ( shaderFxFileUri, fileName );
to

	COLLADASW::URI sourceFileUri (COLLADASW::URI::nativePathToUri (fileName));

somewhat alleviates the problem, but the resulting paths are wrong =\
(but at least every image now gets exported)

I have attached a CGFX file that exhibits these problems.
The textures are not included and will need to be remapped to existing textures before export.

<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=114</p><hr/><h2>earlier comments</h2>
<p><strong>martin.b...@gmail.com said, at 2010-09-30T16:40:00.000Z:</strong></p>
<p>Additionally, once you have all the textures coming out in the library_images, in ColladaMayaEffectTextureExporter.cpp, line 541, you need to pass true to the ignoreCase parameter, like so:

 COLLADASW::URI targetUri = sourceUri.getRelativeTo ( targetColladaUri, success, true );

in order to get a properly relative path.
</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.

**Comment by dgbiggs** [comment]
Bump on this,  I'd like CGFX materials to export images proplerly,   currently they're ignored.
