### ISSUE TITLE
release links dead

### ISSUE THREAD

**Issue by rgdev** [KhronosGroup/OpenCOLLADA#620]
I just tried to download the latest (1.6.68) version of OpenCollada for Max 2019 and the link isn't working.

Here's the response from AWS : 
```
https://s3-us-west-2.amazonaws.com/opencollada-promotion-artifacts/COLLADA-MAX-PC_Max2019_v1.6.68.zip

<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
<BucketName>opencollada-promotion-artifacts</BucketName>
<RequestId>CD3897A85F2434B0</RequestId>
<HostId>
nQmpEbpXGv2gdye0nepkgISQzqkim5vXjvy3/afCZIjrQx6v5Bz4+m0PF0oLQ/5iGV3PkgAk/qg=
</HostId>
</Error>
```

In fact, I tried a dozen of links from this release and previous releases and none seems to work.

**Comment by daemeh** [comment]
Yes, same here. But you can still download it using archive.org https://web.archive.org/web/20190430122323/https://s3-us-west-2.amazonaws.com/opencollada-promotion-artifacts/COLLADA-MAX-PC_Max2019_v1.6.68.zip

**Comment by Anjiu464** [comment]
fix

**Comment by thunderysteak** [comment]
I have reached out to Khronos Group on [social media](https://twitter.com/ThunderySteak/status/1225814695887724548) and emailed them about the issue.
Still waiting for them to reply but they did acknowledge that I sent it.

Will update if they get back to me

**Comment by RemiArnaud** [comment]
See https://github.com/RemiArnaud/OpenCOLLADA
