### ISSUE TITLE
'transparent' and 'transparency' elements are not available when importing a COLLADA file

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#64]
<b>What steps will reproduce the problem?</b>
1. Examine COLLADAFWEffectCommon.h from the head of the code (r7679).
2. Notice that 'mTransparent' and 'mTransparency' are commented out.

<b>What is the expected output? What do you see instead?</b>

'mTransparent' and 'mTransparency' should be available for access when importing a COLLADA file.  See 'lambert' in profile 'COMMON'.

<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=118</p><hr/><h2>earlier comments</h2>
<p><strong>opencollada2@gmail.com said, at 2011-01-25T13:08:19.000Z:</strong></p>
<p>Currently only mOpacity is accessible, which is a combination of mTransparency and mTransparent. But we should change this in future to provide access to the raw COLLADA data.</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
