### ISSUE TITLE
Maya's Extra Attributes not exported

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#65]
1. Using MelScript add a user attribute to a scene node
addAttr -dt &quot;string&quot; -ln &quot;UserAttributeLongName&quot; -sn &quot;UserAttribute&quot; $node;

2. Assign a value to the user attribute
setAttr -lock off ( $node + &quot;.UserAttribute&quot; );
setAttr -type &quot;string&quot; ( $node + &quot;.UserAttribute&quot; ) &quot;UserAttributeValue&quot;;		
setAttr -lock on ( $node + &quot;.UserAttribute&quot; );

2. Export the scene using OpenCOLLADA

3. Note how the attribute information is not exported

In previous version of COLLADAMaya these would have been exported into the DAE using the &lt;extra&gt; tag and we have used it extensively to tag on user data to scene and material nodes.
<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=124</p><hr/><h2>earlier comments</h2>
<p><strong>davidsr...@gmail.com said, at 2010-10-20T18:11:22.000Z:</strong></p>
<p>I have attached a simple Maya scene. 
The box has a user attribute applied, found under 'Extra Attributes' on pCube1</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
