### ISSUE TITLE
Object properties are not imported correctly in 3ds Max

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#66]
<b>What steps will reproduce the problem?</b>
1. Export an object with object properties in max using OpenCollada
2. Import the object to another max file with OpenCollada. 
3. -

<b>What is the expected output? What do you see instead?</b>
I expect that the OpenCollada importer imports the saved object properties, but the properties are not imported. (However, are saved, they are available in &lt;extra&gt;/&lt;technique profile=&quot;OpenCOLLADA&quot;&gt;/&lt;user_properties&gt; )

<b>What version of the product are you using? On what operating system?</b>
OpenCOLLADA_3ds_Max_1.3.0.rc, Windows XP 64-bit

<b>Please provide any additional information below.</b>
3ds Max 2009 64-bit

<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=127</p><hr/><h2>earlier comments</h2>
<p><strong>opencollada2@gmail.com said, at 2011-01-25T13:28:29.000Z:</strong></p>
<p>Import of extra data is currently not supported.</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
