### ISSUE TITLE
MAYA. library_animation_clips are not exported when joint visibilty channel is not keyed

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#68]
<b>What steps will reproduce the problem?</b>
If you create a bones animation and clips in Maya and don't key the visibilty channel on the bone. 
The  &lt;library_animation_clips&gt; are not exported.

<b>What version of the product are you using? On what operating system?</b>
OpenCOLLADA_Maya_1.3.0rc1.7z
Maya2009

<b>Please provide any additional information below.</b>

<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=129</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
