### ISSUE TITLE
colladamaya: wrong transformation on (some) imported nodes

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#69]
<b>What steps will reproduce the problem?</b>
- import attached collada file into maya2009/2011 with colladamaya 1.2 or 1.3rc1

<b>What is the expected output? What do you see instead?</b>
- locate node &quot;Modillion_12&quot;
- observe how Rotate.z = 180 is wrong, it should be 0
- with maya2009 and fcollada plugin the value of Rotate.z is correct (compare attached screenshots)

<b>What version of the product are you using? On what operating system?</b>
- the bug appears with maya2009/2011 and opencollada 1.2 and 1.3rc1
- windows vista x86_64

<b>Please provide any additional information below.</b>
- see attached zip file for collada model
- see attached screenshots<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=130</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
