### ISSUE TITLE
_HAS_ITERATOR_DEBUGGING=0 to improve performance

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#7]
I suggest defining _HAS_ITERATOR_DEBUGGING=0 in both debug and release
project settings to improve performance

Since most people will do that anyway, it would be nice if it was
configured by default so we don't have to change the settings every time.

Note : beware that all projects must have the same flag (either 0 or 1).
You cannot have one libray with this flag off and another one with the flag
on. Otherwise it will crash
<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=6</p><hr/><h2>earlier comments</h2>
<p><strong>opencollada said, at 2009-10-06T09:37:58.000Z:</strong></p>
<p>_HAS_ITERATOR_DEBUGGING is not evaluated in Release mode at all. We'll test against
possible side effects first. Thanks for the hint.</p><p><strong>christop...@gmail.com said, at 2009-10-06T12:16:10.000Z:</strong></p>
<p>Yes you are right, _HAS_ITERATOR_DEBUGGING only applies to debug builds. In our
applications, we noticed that the performance is hugely decreased when this flag is on. 
Since OpenCollada makes heavy use of STL vectors and maps, it should be best to turn
it off so that developers can work faster.

In addition, i also recommend setting _SECURE_SCL=0 in *both* release and debug
builds. This is also a cpu eater. 
Again, this flag should be consistent in all projects 
</p><p><strong>the.pro...@gmail.com said, at 2010-07-27T20:55:22.000Z:</strong></p>
<p>_SECURE_SCL=0 is the same if you are using /O2 compile setting. I believe a good idea to check that is to see /O2 internal configuration in Visual Studio.</p><p><strong>the.pro...@gmail.com said, at 2010-07-27T20:58:42.000Z:</strong></p>
<p>Aditional info from Microsoft:
http://connect.microsoft.com/VisualStudio/feedback/details/524141/serious-bug-when-using-secure-scl-0-c

"Additionally, _SECURE_SCL defaults to 0 in release mode in VC10."</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
