### ISSUE TITLE
Mix map materials no longer exported properly

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#70]
If you create a mix map with two bitmap textures to combine it only exports one of the textures.
This happens for Max 2011. For the old version of the plugin for Max 8 this worked fine.
So, basically, now there is no way to export light mapping.

How to reproduce:
Select a new material, click on the map button for diffuse. For the material type choose &quot;Mix&quot;. For colour #1 select a bitmap texture, for Mix Amount, select the light map texture. 
When you export only the light map texture is exported, the other texture is ignored. 
This is what is exported:

&lt;effect id=&quot;farGround&quot;&gt;
      &lt;profile_COMMON&gt;
        &lt;newparam sid=&quot;ground_png-surface&quot;&gt;
          &lt;surface type=&quot;2D&quot;&gt;
            &lt;init_from&gt;ground_png&lt;/init_from&gt;
          &lt;/surface&gt;
        &lt;/newparam&gt;
        &lt;newparam sid=&quot;ground_png-sampler&quot;&gt;
          &lt;sampler2D&gt;
            &lt;source&gt;ground_png-surface&lt;/source&gt;
          &lt;/sampler2D&gt;
        &lt;/newparam&gt;
        &lt;technique sid=&quot;common&quot;&gt;
          &lt;blinn&gt;
            &lt;emission&gt;
              &lt;color&gt;0 0 0 1&lt;/color&gt;
            &lt;/emission&gt;
            &lt;ambient&gt;
              &lt;color&gt;0.588 0.588 0.588 1&lt;/color&gt;
            &lt;/ambient&gt;
            &lt;diffuse&gt;
              &lt;texture texture=&quot;ground_png-sampler&quot; texcoord=&quot;CHANNEL1&quot;/&gt;
            &lt;/diffuse&gt;
            &lt;specular&gt;
              &lt;color&gt;0.9 0.9 0.9 1&lt;/color&gt;
            &lt;/specular&gt;
            &lt;shininess&gt;
              &lt;float&gt;10&lt;/float&gt;
            &lt;/shininess&gt;
            &lt;reflective&gt;
              &lt;color&gt;0 0 0 1&lt;/color&gt;
            &lt;/reflective&gt;
            &lt;transparent opaque=&quot;A_ONE&quot;&gt;
              &lt;color&gt;1 1 1 1&lt;/color&gt;
            &lt;/transparent&gt;
            &lt;transparency&gt;
              &lt;float&gt;1&lt;/float&gt;
            &lt;/transparency&gt;
          &lt;/blinn&gt;
        &lt;/technique&gt;
      &lt;/profile_COMMON&gt;
      &lt;extra&gt;
        &lt;technique profile=&quot;OpenCOLLADA3dsMax&quot;&gt;
          &lt;extended_shader&gt;
            &lt;apply_reflection_dimming&gt;0&lt;/apply_reflection_dimming&gt;
            &lt;dim_level&gt;0&lt;/dim_level&gt;
            &lt;falloff_type&gt;0&lt;/falloff_type&gt;
            &lt;index_of_refraction&gt;1.5&lt;/index_of_refraction&gt;
            &lt;opacity_type&gt;0&lt;/opacity_type&gt;
            &lt;reflection_level&gt;3&lt;/reflection_level&gt;
            &lt;wire_size&gt;1&lt;/wire_size&gt;
            &lt;wire_units&gt;0&lt;/wire_units&gt;
          &lt;/extended_shader&gt;
          &lt;shader&gt;
            &lt;ambient_diffuse_lock&gt;1&lt;/ambient_diffuse_lock&gt;
            &lt;ambient_diffuse_texture_lock&gt;1&lt;/ambient_diffuse_texture_lock&gt;
            &lt;diffuse_specular_lock&gt;0&lt;/diffuse_specular_lock&gt;
            &lt;soften&gt;0.1&lt;/soften&gt;
            &lt;use_self_illum_color&gt;0&lt;/use_self_illum_color&gt;
          &lt;/shader&gt;
        &lt;/technique&gt;
      &lt;/extra&gt;
    &lt;/effect&gt;

This is what should be exported (i.e produced by old exporter for Max 8):
&lt;effect id=&quot;orig_floor2-fx&quot; name=&quot;orig_floor2&quot;&gt;
      &lt;profile_COMMON&gt;
        &lt;newparam sid=&quot;ground_png-surface&quot;&gt;
          &lt;surface type=&quot;2D&quot;&gt;
            &lt;init_from&gt;ground.png&lt;/init_from&gt;
            &lt;format&gt;A8R8G8B8&lt;/format&gt;
          &lt;/surface&gt;
        &lt;/newparam&gt;
        &lt;newparam sid=&quot;ground_png-sampler&quot;&gt;
          &lt;sampler2D&gt;
            &lt;source&gt;ground_png-surface&lt;/source&gt;
            &lt;wrap_s&gt;WRAP&lt;/wrap_s&gt;
            &lt;wrap_t&gt;WRAP&lt;/wrap_t&gt;
            &lt;minfilter&gt;NONE&lt;/minfilter&gt;
            &lt;magfilter&gt;NONE&lt;/magfilter&gt;
            &lt;mipfilter&gt;NONE&lt;/mipfilter&gt;
          &lt;/sampler2D&gt;
        &lt;/newparam&gt;
        &lt;newparam sid=&quot;groundLightingMap2_tga-surface&quot;&gt;
          &lt;surface type=&quot;2D&quot;&gt;
            &lt;init_from&gt;groundLightingMap2.tga&lt;/init_from&gt;
            &lt;format&gt;A8R8G8B8&lt;/format&gt;
          &lt;/surface&gt;
        &lt;/newparam&gt;
        &lt;newparam sid=&quot;groundLightingMap2_tga-sampler&quot;&gt;
          &lt;sampler2D&gt;
            &lt;source&gt;groundLightingMap2_tga-surface&lt;/source&gt;
            &lt;wrap_s&gt;WRAP&lt;/wrap_s&gt;
            &lt;wrap_t&gt;WRAP&lt;/wrap_t&gt;
            &lt;minfilter&gt;NONE&lt;/minfilter&gt;
            &lt;magfilter&gt;NONE&lt;/magfilter&gt;
            &lt;mipfilter&gt;NONE&lt;/mipfilter&gt;
          &lt;/sampler2D&gt;
        &lt;/newparam&gt;
        &lt;technique sid=&quot;common&quot;&gt;
          &lt;blinn&gt;
            &lt;ambient&gt;
              &lt;color&gt;0.588 0.588 0.588 1&lt;/color&gt;
            &lt;/ambient&gt;
            &lt;diffuse&gt;
              &lt;texture texture=&quot;ground_png-sampler&quot; texcoord=&quot;CHANNEL1&quot;&gt;
                &lt;extra&gt;
                  &lt;technique profile=&quot;MAYA&quot;&gt;
                    &lt;mirrorU&gt;0&lt;/mirrorU&gt;
                    &lt;mirrorV&gt;0&lt;/mirrorV&gt;
                    &lt;wrapU&gt;1&lt;/wrapU&gt;
                    &lt;wrapV&gt;1&lt;/wrapV&gt;
                    &lt;repeatU&gt;1&lt;/repeatU&gt;
                    &lt;repeatV&gt;1&lt;/repeatV&gt;
                    &lt;offsetU&gt;0&lt;/offsetU&gt;
                    &lt;offsetV&gt;0&lt;/offsetV&gt;
                    &lt;rotateUV&gt;0&lt;/rotateUV&gt;
                  &lt;/technique&gt;
                  &lt;technique profile=&quot;MAX3D&quot;&gt;
                    &lt;amount&gt;1&lt;/amount&gt;
                  &lt;/technique&gt;
                &lt;/extra&gt;
              &lt;/texture&gt;
              &lt;texture texture=&quot;groundLightingMap2_tga-sampler&quot; texcoord=&quot;CHANNEL1&quot;&gt;
                &lt;extra&gt;
                  &lt;technique profile=&quot;MAYA&quot;&gt;
                    &lt;mirrorU&gt;0&lt;/mirrorU&gt;
                    &lt;mirrorV&gt;0&lt;/mirrorV&gt;
                    &lt;wrapU&gt;1&lt;/wrapU&gt;
                    &lt;wrapV&gt;1&lt;/wrapV&gt;
                    &lt;repeatU&gt;1&lt;/repeatU&gt;
                    &lt;repeatV&gt;1&lt;/repeatV&gt;
                    &lt;offsetU&gt;0&lt;/offsetU&gt;
                    &lt;offsetV&gt;0&lt;/offsetV&gt;
                    &lt;rotateUV&gt;0&lt;/rotateUV&gt;
                  &lt;/technique&gt;
                  &lt;technique profile=&quot;MAX3D&quot;&gt;
                    &lt;amount&gt;0&lt;/amount&gt;
                  &lt;/technique&gt;
                &lt;/extra&gt;
              &lt;/texture&gt;
            &lt;/diffuse&gt;
            &lt;specular&gt;
              &lt;color&gt;0.9 0.9 0.9 1&lt;/color&gt;
            &lt;/specular&gt;
            &lt;shininess&gt;
              &lt;float&gt;1.46862&lt;/float&gt;
            &lt;/shininess&gt;
            &lt;reflective&gt;
              &lt;color&gt;0 0 0 1&lt;/color&gt;
            &lt;/reflective&gt;
            &lt;reflectivity&gt;
              &lt;float&gt;1&lt;/float&gt;
            &lt;/reflectivity&gt;
            &lt;transparent opaque=&quot;A_ONE&quot;&gt;
              &lt;color&gt;1 1 1 1&lt;/color&gt;
            &lt;/transparent&gt;
            &lt;transparency&gt;
              &lt;float&gt;1&lt;/float&gt;
            &lt;/transparency&gt;
          &lt;/blinn&gt;
          &lt;extra&gt;
            &lt;technique profile=&quot;FCOLLADA&quot;&gt;
              &lt;spec_level&gt;
                &lt;float&gt;0&lt;/float&gt;
              &lt;/spec_level&gt;
              &lt;emission_level&gt;
                &lt;float&gt;0&lt;/float&gt;
              &lt;/emission_level&gt;
            &lt;/technique&gt;
          &lt;/extra&gt;
        &lt;/technique&gt;
      &lt;/profile_COMMON&gt;
      &lt;extra&gt;
        &lt;technique profile=&quot;MAX3D&quot;&gt;
          &lt;faceted&gt;0&lt;/faceted&gt;
          &lt;double_sided&gt;0&lt;/double_sided&gt;
          &lt;wireframe&gt;0&lt;/wireframe&gt;
          &lt;face_map&gt;0&lt;/face_map&gt;
        &lt;/technique&gt;
      &lt;/extra&gt;
    &lt;/effect&gt;<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=134</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
