### ISSUE TITLE
Fix for color sets not exporting in colladaMaya

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#71]
<b>What steps will reproduce the problem?</b>
1. Make a mesh with per-vertex colors
2. export it
3. note that the color indices are all 0

I made the following changes to my local source and it now exports them correctly. Probably only the first change is needed:

in ColladaMayaGeometryExporter.cpp, exportColorSets.
The SourceInput was being constructed with the default index, -1.
This made the color index lookup later fail, since there is not a color set name for index -1.

			//-------------------------------------------------------------------------------
			// PMS BEGIN EDIT
			// MJB: Added ,i to the end of each input definitions
            if ( perVertexColor )
            {
                // Insert a per-vertex color set input
                mVertexSources.push_back ( SourceInput ( colorSource, COLLADASW::COLOR, i ) );
            }
            else
            {
                // Insert a per-face-vertex color set input
                mPolygonSources.push_back ( SourceInput ( colorSource, COLLADASW::COLOR, i ) );
            }
			// PMS END EDIT
			//-------------------------------------------------------------------------------

in colladaMayaGeometryPolygonExporter.cpp, writeVertexIndices
I changed the API used to match the API for the UV's, in the preceding switch case.

            case COLLADASW::COLOR:
                {
                    MString&amp; colorSetName = mColorSetNames[vertexAttributes.getIdx()];
                    int colorIndex = 0;
                    {
						//----------------------------------------------------------
						// PMS BEGIN EDIT
						// MJB: The API functions they use aren't working
						// MJB: Try the same API as for texture co-ordinates, above
						if( meshPolygonsIter.getColorIndex ( iteratorVertexIndex, colorIndex, &amp;colorSetName )!= MStatus::kSuccess )
						{
							std::cerr &lt;&lt; &quot;Could not get color index for vertex &quot; &lt;&lt; iteratorVertexIndex &lt;&lt; &quot;in color set &quot; &lt;&lt; colorSetName &lt;&lt; std::endl;
						}
//#if MAYA_API_VERSION &gt;= 700
//                        fnMesh.getColorIndex ( polyIndex, iteratorVertexIndex, colorIndex, &amp;colorSetName );
//#else
//                        fnMesh.getFaceVertexColorIndex ( polyIndex, iteratorVertexIndex, colorIndex );
//#endif
						// PMS END EDIT
						//----------------------------------------------------------
                    }
                    primitivesBasePoly-&gt;appendValues ( colorIndex );
                }
                break;

<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=136</p><hr/><h2>earlier comments</h2>
<p><strong>opencollada2@gmail.com said, at 2010-11-22T08:38:18.000Z:</strong></p>
<p>Thanks for providing this fix. I have applied the first change in revision 784. I'm not sure if the second works for all maya API versions. This would require additional testing I currently do not have the time for.</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
