### ISSUE TITLE
CgFX RenderStates other than generic tests come through as UNKNOWN INPUT ERROR

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#72]
<b>What steps will reproduce the problem?</b>
1. Create a CgFX file that uses a renderstate eg blendfunc
2. Make a mesh that uses this CgFX file
3. export the mesh

<b>What is the expected output? What do you see instead?</b>

This is what I see:

          &lt;pass sid=&quot;p0&quot;&gt;
            &lt;UNKNOWN INPUT ERROR value=&quot;true&quot;/&gt;
            &lt;blend_equation_separate value=&quot;UNKNOWN INPUT ERROR&quot; value=&quot;UNKNOWN INPUT ERROR&quot;/&gt;
            &lt;blend_func_separate value=&quot;UNKNOWN INPUT ERROR&quot; value=&quot;UNKNOWN INPUT ERROR&quot; value=&quot;UNKNOWN INPUT ERROR&quot; value=&quot;UNKNOWN INPUT ERROR&quot;/&gt;
            &lt;cull_face_enable value=&quot;false&quot;/&gt;
            &lt;depth_mask value=&quot;true&quot;/&gt;
            &lt;depth_test_enable value=&quot;true&quot;/&gt;
            &lt;depth_func value=&quot;LEQUAL&quot;/&gt;
          &lt;/pass&gt;

This is the CgFX input:

    AlphaBlendEnable = true;
    BlendEquationSeparate = int2(ADD,ADD);
    BlendFuncSeparate = int4(SRCALPHA,INVSRCALPHA,ONE,ZERO);
    CullFaceEnable = false;
    DepthMask = true;
    DepthTestEnable = true;
    DepthFunc = LESSEQUAL;

<b>What version of the product are you using? On what operating system?</b>

openColladaMaya 64 bit, head revision, Maya 2011, Win7 64.

<b>Please provide any additional information below.</b>

The missing state is AlphaBlendEnable.
Looking at the code it seems like you only compare the renderstate value against the strings for the simple tests (used in, say, DepthFunc) and not the other states (used in, say, BlendFunc).

I have to ask why this information is even output since it lives in the CgFX file? Is there a rationale for duplicating it in the output?
<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=138</p><hr/><h2>earlier comments</h2>
<p><strong>daniele....@gmail.com said, at 2011-02-21T13:23:49.000Z:</strong></p>
<p>I'm experiencing this issue too when using BlendFunc. I've resolved just inserting a break when case checking for INT1,2,3,4 etc., so that the tag is not even opened, but this is quite serious in my opinion, since it prevents also basic shaders to work properly when exported. Also, the cause of the error isn't so clear when inspecting the file.</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
