### ISSUE TITLE
patch: changed cmake file to be used as subproject

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#73]
I changed the cmake file a little to support being used as a subproject. I don't have much experience with cmake but it seems to work

PS: Is there a better place top propose patches, than this tracker?
<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=140</p><hr/><h2>earlier comments</h2>
<p><strong>opencollada2@gmail.com said, at 2011-01-18T15:21:15.000Z:</strong></p>
<p>Thanks for providing this patch.

I have not much experience with cmake, either, especially when creating sub projects is concerned. 

It would be nice if some with more knowledge could review this patch! 

PS: This bug tracker is the best place to propose patches. :) </p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
