### ISSUE TITLE
Wrong 'emission' exporting from 3dsmax

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#74]
<b>What steps will reproduce the problem?</b>
1.Setting self-illumination strength (not color), in standard material properties
2.Export as OpenCollada

<b>What is the expected output? What do you see instead?</b>
I expected to see some valid color (diffuse*emissionStrength) in Collada file. but it's either zero (black) or previous emissive color (not strength) which was set in max.

<b>What version of the product are you using? On what operating system?</b>
3dsmax 2011

<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=141</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
