### ISSUE TITLE
Maya 2011 - Fail to correctly load a model

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#76]
<b>What steps will reproduce the problem?</b>
1. Import a model with data set as below

&lt;vertices id=&quot;Geometry-vertices&quot;&gt;
&lt;input semantic=&quot;POSITION&quot; source=&quot;#GeometrySource&quot; /&gt; 
&lt;input semantic=&quot;NORMAL&quot; source=&quot;#GeometrySource1&quot; /&gt; 
&lt;input semantic=&quot;TEXCOORD&quot; source=&quot;#GeometrySource2&quot; /&gt; 
&lt;input semantic=&quot;COLOR&quot; source=&quot;#GeometrySource3&quot; /&gt; 
&lt;/vertices&gt;
&lt;triangles material=&quot;VisualMaterial0&quot; count=&quot;1019&quot;&gt;
&lt;input semantic=&quot;VERTEX&quot; source=&quot;#Geometry-vertices&quot; offset=&quot;0&quot; /&gt; 
&lt;p&gt;[data]&lt;/p&gt;

<b>What is the expected output? What do you see instead?</b>
model loaded.
model loads but UV's arn't loaded, it also affects any skinning working correctly.

<b>What version of the product are you using? On what operating system?</b>
OpenCollada 1.3rc Maya 2011 64bit, Win7 Ultimate 64bit

<b>Please provide any additional information below.</b>
model file has been exported using Fcollada
<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=147</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
