### ISSUE TITLE
"image" is legal child of "effect" but not supported by OpenCollada

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#77]
The &quot;image&quot; tag, usually found in &quot;library_images&quot; is also a legal child of &quot;effect&quot; according to the specification.  Unfortunately, OpenCollada does not recognize when &quot;image&quot; shows up under &quot;effect&quot; and as a result the importer fails to load any textures that appear inside &quot;effect&quot;.
<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=149</p><hr/><h2>earlier comments</h2>
<p><strong>opencollada2@gmail.com said, at 2011-01-10T13:18:01.000Z:</strong></p>
<p>Thanks for pointing out this issue. It is a known limitation of OpenCOLLADA.</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.

**Comment by mingweiLIU** [comment]
I'd like to see this bug to be fixed, since we really need it!

**Comment by RemiArnaud** [comment]
@mycheckgithub @jerome-jacob  - could you take a look at this request please ? please let me know by email
