### ISSUE TITLE
Export flips normals

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#78]
<b>What steps will reproduce the problem?</b>
1.load coat_chef_cucumber_f.max into 3DS MAX
2.inspect normals (eg, render it)
3.export using opencollada with normals and triangulate checked
4.drag and drop DAE file back into 3DS MAX
5.inspect normals (eg, render it)

<b>What is the expected output? What do you see instead?</b>
normals should be the same. instead the normals are flipped and the object does not render correctly.

<b>What version of the product are you using? On what operating system?</b>
3ds max 2011 64bit with opencollada 1.2.5
      &lt;authoring_tool&gt;OpenCOLLADA for 3ds Max;  Version: 1.2.5;  Revision: 734:737M;  Platform: x64;  Configuration: Release_Max2011_static&lt;/authoring_tool&gt;

<b>Please provide any additional information below.</b>
This only happens on some max files (not all). Very interested in bug fix or work around.<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=150</p><hr/><h2>earlier comments</h2>
<p><strong>dave.mcc...@gmail.com said, at 2011-01-04T22:10:12.000Z:</strong></p>
<p>The render should look like this. If there is something special about this max file that causes the problem, and there is a work around, that would be as good as a bug fix.</p><p><strong>dave.mcc...@gmail.com said, at 2011-01-07T18:58:02.000Z:</strong></p>
<p>We think this happens because the model was skinned without first doing a reset transform on the root node.  Because when we collapsed the stack and use the reset transform tool the normals flip. Then if you flip them back and re-add the skin modifier and export and then open up the dae the normals are fine.

So that appears to be the work-around. Nevertheless, I think this is still a bug in the exporter?? And the work-around is a time killer.</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
