### ISSUE TITLE
Wrong validation code generated for <xs:choice maxOccurs="unbounded">

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#79]
For an element of type &lt;xs:choice maxOccurs=&quot;unbounded&quot;&gt; the following validation code is generated:

if ( parentValidationData-&gt;rotate &gt;= 1 ) // maxOccurs
{
    if ( handleError ( ParserError::SEVERITY_ERROR_NONCRITICAL, ParserError::ERROR_VALIDATION_MAX_OCCURS_EXCEEDED, HASH_ELEMENT_ROTATE, (const ParserChar*)0, 0 ) )
        return false;
}
...

However, no validation concerning the number of child elements is required in this case.

<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=154</p><hr/><h2>earlier comments</h2>
<p><strong>opencollada2@gmail.com said, at 2011-01-18T11:44:48.000Z:</strong></p>
<p>Similar problem occurs for 

<xs:choice minOccurs="0" maxOccurs="unbounded">

if ( validationData->translate == 0 && validationData->rotate == 0 ) // no child present
  if ( handleError ( ParserError::SEVERITY_ERROR_NONCRITICAL, ParserError::ERROR_VALIDATION_CHOICE_NO_CHILD_PRESENT, HASH_ELEMENT_FRAME_ORIGIN, (const ParserChar*)0, 0 ) )
    return false;

in ColladaParserAutoGen15Private::_validateEnd__frame_origin
 </p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
