### ISSUE TITLE
Animation: GlobalTracks/Notes not saved under Max

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#8]
<b>What steps will reproduce the problem?</b>
1. Load a Max model with notes in its global tracks
2. Export it

<b>What is the expected output? What do you see instead?</b>
A dae file with the notes attached to its animations.

<b>What version of the product are you using? On what operating system?</b>
XP, Max 2010, OpenCollada 1.2.3

<b>Please provide any additional information below.</b>
I don't know whether Collada supports it, but since Max doesn't support
multiple animations we used to use the notes to &quot;label&quot; the animtracks.

<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=10</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
