### ISSUE TITLE
[3dsmax] Add MAXScript interface for export options setup

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#80]
Currently the only way to specify export options programmatically in 3dsmax (I'm talking about batch export) is to write a ColladaMax.ini file.

This is certainly doable from a MAXScript, but it changes the default options, so it's inconvenient if both batch and manual export are used.

FBX provides a set of MAXScript functions that allow clean export options setup: http://www.kxcad.net/autodesk/Autodesk_MAXScript_Reference_9/FBX_Export_Dialog_Access.htm

It would be great if OpenCOLLADA had this functionality.<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=155</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
