### ISSUE TITLE
error compiling on ubuntu linux ('COLLADABU_ASSERT' was not declared in this scope)

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#81]
scons: *** [dae2ogre/obj/posix/x86_64/debuglibxml/src/DAE2OgreMeshWriter.o] Error 1
In file included from COLLADAFramework/include/COLLADAFWArrayPrimitiveType.h:15,
                 from COLLADAFramework/include/COLLADAFWTypes.h:15,
                 from COLLADAFramework/include/COLLADAFWUniqueId.h:15,
                 from dae2ogre/include/DAE2OgreOgreWriter.h:17,
                 from dae2ogre/include/DAE2OgreBaseWriter.h:15,
                 from dae2ogre/src/DAE2OgreBaseWriter.cpp:12:
COLLADAFramework/include/COLLADAFWArray.h: In member function 'Type&amp; COLLADAFW::Array&lt;Type&gt;::operator[](size_t) [with Type = COLLADAFW::TextureCoordinateBinding]':
COLLADAFramework/include/COLLADAFWArray.h:179:   instantiated from 'void COLLADAFW::Array&lt;Type&gt;::cloneArray(COLLADAFW::Array&lt;Type&gt;&amp;) const [with Type = COLLADAFW::TextureCoordinateBinding]'
COLLADAFramework/include/COLLADAFWMaterialBinding.h:81:   instantiated from here
COLLADAFramework/include/COLLADAFWArray.h:161: error: 'COLLADABU_ASSERT' was not declared in this scope
COLLADAFramework/include/COLLADAFWArray.h: In member function 'Type&amp; COLLADAFW::Array&lt;Type&gt;::operator[](size_t) [with Type = COLLADAFW::MaterialBinding]':
COLLADAFramework/include/COLLADAFWArray.h:179:   instantiated from 'void COLLADAFW::Array&lt;Type&gt;::cloneArray(COLLADAFW::Array&lt;Type&gt;&amp;) const [with Type = COLLADAFW::MaterialBinding]'
COLLADAFramework/include/COLLADAFWInstanceBindingBase.h:60:   instantiated from 'COLLADAFW::InstanceBindingBase&lt;classId&gt;::InstanceBindingBase(const COLLADAFW::InstanceBindingBase&lt;classId&gt;&amp;) [with COLLADAFW::COLLADA_TYPE::ClassId classId = (COLLADAFW::COLLADA_TYPE::ClassId)437u]'
COLLADAFramework/include/COLLADAFWInstanceBindingBase.h:45:   instantiated from 'COLLADAFW::InstanceBindingBase&lt;classId&gt;* COLLADAFW::InstanceBindingBase&lt;classId&gt;::clone() const [with COLLADAFW::COLLADA_TYPE::ClassId classId = (COLLADAFW::COLLADA_TYPE::ClassId)437u]'
COLLADAFramework/include/COLLADAFWPointerArray.h:86:   instantiated from 'void COLLADAFW::PointerArray&lt;T&gt;::cloneContents(const COLLADAFW::PointerArray&lt;T&gt;&amp;) [with T = COLLADAFW::InstanceBindingBase&lt;(COLLADAFW::COLLADA_TYPE::ClassId)437u&gt;]'
COLLADAFramework/include/COLLADAFWPointerArray.h:50:   instantiated from 'COLLADAFW::PointerArray&lt;T&gt;::PointerArray(const COLLADAFW::PointerArray&lt;T&gt;&amp;) [with T = COLLADAFW::InstanceBindingBase&lt;(COLLADAFW::COLLADA_TYPE::ClassId)437u&gt;]'
COLLADAFramework/include/COLLADAFWNode.h:46:   instantiated from here
COLLADAFramework/include/COLLADAFWArray.h:161: error: 'COLLADABU_ASSERT' was not declared in this scope
scons: *** [dae2ogre/obj/posix/x86_64/debuglibxml/src/DAE2OgreBaseWriter.o] Error 1
scons: building terminated because of errors.

opencollada svn r833 on Ubuntu Lucid 10.04 AMD64
gcc version 4.4.3 (Ubuntu 4.4.3-4ubuntu5) 

<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=156</p><hr/><h2>earlier comments</h2>
<p><strong>freaka...@gmail.com said, at 2011-02-12T10:10:37.000Z:</strong></p>
<p>I believe the recent change from simply using assert to using COLLADABU_ASSERT wasn;t reflected in one particular file. I have attached the patch here.

Index: COLLADAFramework/include/COLLADAFWArray.h
===================================================================
--- COLLADAFramework/include/COLLADAFWArray.h	(revision 833)
+++ COLLADAFramework/include/COLLADAFWArray.h	(working copy)
@@ -12,6 +12,7 @@
 #define __COLLADAFW_ARRAY_H__
 
 #include "COLLADAFWPrerequisites.h"
+#include "COLLADABUPlatform.h"
 #include <cassert></p><p><strong>Alexey.Z...@gmail.com said, at 2011-05-17T10:08:29.000Z:</strong></p>
<p>I have similar issue in revision 839.

here is the error

In file included from /home/alexey/workspace/opencollada/common/libBuffer/src/CommonCharacterBuffer.cpp:11:0:
/home/alexey/workspace/opencollada/common/libBuffer/include/CommonCharacterBuffer.h: In member function ‘bool Common::CharacterBuffer::copyToBufferAsChar(IntegerType)’:
/home/alexey/workspace/opencollada/common/libBuffer/include/CommonCharacterBuffer.h:97:55: error: there are no arguments to ‘COLLADABU_ASSERT’ that depend on a template parameter, so a declaration of ‘COLLADABU_ASSERT’ must be available
/home/alexey/workspace/opencollada/common/libBuffer/include/CommonCharacterBuffer.h:97:55: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
make[2]: *** [common/libBuffer/CMakeFiles/buffer_shared.dir/src/CommonCharacterBuffer.cpp.o] Error 1
make[1]: *** [common/libBuffer/CMakeFiles/buffer_shared.dir/all] Error 2
make: *** [all] Error 2
</p><p><strong>Alexey.Z...@gmail.com said, at 2011-05-17T11:57:07.000Z:</strong></p>
<p>the problem is in the libBuffer in CommonCharacterBuffer.h

Here is the problem part:

bool CharacterBuffer::copyToBufferAsChar( IntegerType i)
	{
		size_t maxIntLength = Itoa<IntegerType>::MINIMUM_BUFFERSIZE_10;

		if ( getBytesAvailable() < maxIntLength )
		{
			//The int might not fit into the buffer. We need to flush first.
			flushBuffer();
		}

		// Check if the buffer size is large enough
		COLLADABU_ASSERT(getBytesAvailable() >= maxIntLength);
		if ( getBytesAvailable() < maxIntLength )
		{
			//No chance to convert the double with this buffer
			return false;
		}

		increaseCurrentPosition( itoa( i, getCurrentPosition(), 10) );

		return true;
	}

Correct me if I am wrong, COLLADABU_ASSERT shouldn't be in libBuffer. Since libBuffer is independent from ColladaBaseUtils.

My solution is to comment this line out.</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
