### ISSUE TITLE
non-conformant <accessor>

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#82]
<b>What steps will reproduce the problem?</b>
1.Import or export any data

<b>What is the expected output? What do you see instead?</b>
&lt;accessor&gt; where &lt;param&gt;'s are of type float. I see float4x4

<b>What version of the product are you using? On what operating system?</b>
r827 built on Windows 7

-------

OpenCOLLADA seems to be using types for &lt;param&gt; that are not allowed according specs. See http://www.khronos.org/collada/public-mailing-list/archives/1101/msg00008.html for more information on the nature of the issue.<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=157</p><hr/><h2>earlier comments</h2>
<p><strong>mikkels...@gmail.com said, at 2011-02-03T20:16:17.000Z:</strong></p>
<p>Actually, the type in the param is intended as pass through to the application. It is not supposed to affect what data actually gets flushed out of the source.
The only thing that is supposed to affect that is the sequence of named and unnamed params. These according to the spec are supposed to dictate how the source gets flushed. It appears OpenCOLLADA does not flush its sources according to spec.

Details on the accessor:

The number and order of <param> elements define the output of the <accessor> element. Parameters 
are bound to values in the order in which both are specified. No reordering of the data can occur. A 
<param> element without a name attribute indicates that the value is not part of the output, so the element 
is unbound.
The stride attribute must have a value equal to or greater than the number of <param> elements. If 
there are fewer <param> elements than indicated by the stride value, the unbound array data source 
values are skipped.

Additional information is in one of the examples where it says:

To properly read a source through an <accessor>, the program has to consider the data expected by a 
particular semantic and compare it to stride, offset, and the number of params with nonnull names to 
decide how many values to read. Then, when reading, it has to skip over the data that corresponds to 
<param>s with no name. </p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
