### ISSUE TITLE
Some 3ds Max material attributes are not exported: wire, 2-sided, faceted, face map

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#83]
I used these attributes which were exported by the Feeling Software plugin. Now I moved to OpenCOLLADA and they are not supported anymore. 2-sided is especially important to me, I use it to disable back-face culling for some bad assets in my engine.

Old FCollada plugin output:

&lt;effect&gt;
  &lt;extra&gt;
    &lt;technique profile=&quot;MAX3D&quot;&gt;
      &lt;faceted&gt;0&lt;/faceted&gt;
      &lt;double_sided&gt;0&lt;/double_sided&gt;
      &lt;wireframe&gt;0&lt;/wireframe&gt;
      &lt;face_map&gt;0&lt;/face_map&gt;
    &lt;/technique&gt;
  &lt;/extra&gt;
&lt;/effect&gt;
<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=158</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
