### ISSUE TITLE
Problem with kinematics

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#84]
Hello, All.

I am working with kinematics part of COLLADA.
In COLLADAFW's kinematics related classes I am not able to find
a field with initial position value of the joint.

To make things clear here is part of COLLADA file,
I am interested to know a value of the filed &lt;float&gt;&lt;/float&gt;

&lt;!--part of the kr150.dae-&gt;
&lt;library_kinematics_scenes id=&quot;libkinscenes&quot;&gt;
  &lt;kinematics_scene id=&quot;libkinscenes.kinScene&quot;&gt;
     &lt;instance_kinematics_model url=&quot;#kinmodel.0&quot; sid=&quot;inst_kinmodel.0&quot;&gt;
     ...
       &lt;newparam sid=&quot;libkinscenes.kinScene_libkinscenes.kinScene_inst_kinmodel.0_joint_1_axis0_value&quot;&gt;
	 &lt;float&gt;-90&lt;/float&gt;   &lt;!--THIS FIELD--&gt;&gt;
       &lt;/newparam&gt;
...

I attached a complete model, which I am importing.

Best regards,
Alexey<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=159</p><hr/><h2>earlier comments</h2>
<p><strong>Alexey.Z...@gmail.com said, at 2011-03-13T20:22:06.000Z:</strong></p>
<p>I dig a code a little. 

the value has been parsed in COLLADASaxParser:

void KinematicsInstanceKinematicsModel::addKinematicsNewParam( KinematicsNewParam* newParam )
	{
		const String& name = newParam->getName();
		double value = newParam->getDoubleValue();
		mKinematicsNewParams.insert(std::make_pair(name, newParam));
	}

Later in COLLADASaxFrameworkLoader/src/COLLADASaxFWLKinematicsSceneCreator.cpp, when mapping to COLLADAFW data structures happens, KinematicsNewParams is used only to resolve a joint instance, but its initial value from the field <FLOAT> is ignored and not mapped. At least this is, how I understood it. :)	</p><p><strong>Alexey.Z...@gmail.com said, at 2011-03-18T13:46:52.000Z:</strong></p>
<p>looks like everyone is on vocation :( </p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
