### ISSUE TITLE
Can't tell if effect does not specify transparency / transparent

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#85]
<b>What steps will reproduce the problem?</b>
Using getOpacity() from an effect wont return unspecified even if the file doesn't specify either transparency / transparent. This means there is no good way to trigger a transparent drawing path.

In the example file commonEffects[0]-&gt;getOpacity().isValid() is true for both effects.<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=160</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
