### ISSUE TITLE
Need access to entire sampler array

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#86]
Only samplers that are known to be used are stored in the CommonEffect sampler array. This is a problem when samplers are needed for extra aspects of an effect. The specific issue is supporting the FCOLLADA bump extension (http://www.collada.org/mediawiki/index.php/Bump_texture_FCOLLADA_extension).

It's a relatively easy fix to change LibraryEffectsLoader::fillSamplerArray to iterate mEffectProfileSidSamplerInfoMap instead of mEffectProfileSamplersMap, but I suspect that has side-effects.<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=161</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
