### ISSUE TITLE
opencollada autorename mesh

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#87]
<b>What steps will reproduce the problem?</b>
1.in 3dsmax 2011, select bones and meshes of a character
2.export with opencollada
3.one in assimp viewer and see that mesh (node) are renamed, instead of bones that have correct names.

<b>What is the expected output? What do you see instead?</b>

I expeted that mesh names are correct

<b>What version of the product are you using? On what operating system?</b>

3dsmax 2011 64bit on windows 7 64bit with opencollada 1.3.0

<b>Please provide any additional information below.</b>

<b>If possible, please provide a sample file that can be used to reproduce the</b>
<b>problem.</b>

<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=162</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
