### ISSUE TITLE
Maya blinn eccentricity exported as shininess without conversion

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#88]
<b>What steps will reproduce the problem?</b>
1. Create a object with a blinn shader, defaults to 0.3 spec. eccentricity
2. Export using OpenCollada Maya

<b>What is the expected output? What do you see instead?</b>
- Expected result: convert eccentricity to shininess
From trial and error I found the relationship to be something like:
shininess = (1.0 - eccentricity) * 128

It seems maya's blinn is actually Torrance-Sparrow, see http://forums.cgsociety.org/showthread.php?t=811124

- Actual result: The dae file has shininess directly as 0.3

<b>What version of the product are you using? On what operating system?</b>
1.3.0.788M

<b>Please provide any additional information below.</b>

<b>If possible, please provide a sample file that can be used to reproduce the</b>
<b>problem.</b>

<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=163</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
