### ISSUE TITLE
UV coords problem

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#9]
I'm using the 3dsmax2009 plugin

the coordinate paramters of the material (UV offset and UV tiling, etc.) 
does not get exported, unlike the fcollada colladamax exporter which 
exports them correctly

so If you make a box, and define e material with 2.0 U tiling, and assign 
it to the box, you won't have the correct data in the COLLADA file

<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=14</p><hr/><h2>earlier comments</h2>
<p><strong>opencollada2@gmail.com said, at 2009-10-20T09:18:31.000Z:</strong></p>
<p>The information (UV offset and UV tiling, etc.) you are missing is not supported by
COLLADA. The only way to export such information is within an extra tag. However,
using extra tags is bad practice and therefore has very low priority for us.
We might export this data later, but cannot tell if and when, yet.</p><p><strong>Marcus.C...@gmail.com said, at 2009-10-23T17:02:29.000Z:</strong></p>
<p>I don't agree that using extra tags is bad practice. Extensibility is a vitally
important feature of COLLADA. See https://collada.org/mediawiki/index.php/Extension
</p><p><strong>opencollada said, at 2009-10-29T08:32:31.000Z:</strong></p>
<p>I've to agree with Robert: the better way of exporting data would be to bake the
tiling into the texture or the UV sets (or even better: not to use that functionality
in max). We'll discuss that internally.</p><p><strong>erwin.co...@gmail.com said, at 2009-11-17T19:34:13.000Z:</strong></p>
<p>
perhaps you can leave the option to the user and add a button?

(UV tiling/offset baking or extras)</p>

**Comment by RemiArnaud** [comment]
closing old issue. 
if needed please submit PR with extra information as extension
