### ISSUE TITLE
COLLADAFWKinematicsController copy constructor doesn't copy AxisInfos and KinematicsModelUniqueIds

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#90]
<b>What steps will reproduce the problem?</b>
- Load a kinematics model with the tag &lt;articulated_system&gt;, could use the one I attached below.

- Try to execute following code:

bool writeKinematicsScene( const COLLADAFW::KinematicsScene* kinematicsScene )
{
  COLLADAFW::KinematicsControllerArray controllers = kinematicsScene-&gt;getKinematicsControllers();
  COLLADAFW::AxisInfoArray&amp; axisInfos = controllerPtr-&gt;getAxisInfos();
  cout &lt;&lt; &quot;found &quot; &lt;&lt; axisInfos.getCount() &lt;&lt; &quot; axis_info tags&quot; &lt;&lt; endl;
}

- The output will be 0.

- If you use a reference instead of the copying object:
{
  const COLLADAFW::KinematicsControllerArray&amp; controllers =   kinematicsScene-&gt;getKinematicsControllers();
  COLLADAFW::AxisInfoArray&amp; axisInfos = controllerPtr-&gt;getAxisInfos();
  cout &lt;&lt; &quot;found &quot; &lt;&lt; axisInfos.getCount() &lt;&lt; &quot; axis_info tags&quot; &lt;&lt; endl;
}

You get the correct number of axisInfo tags, which 8 for this example.

This happens because in KinematicsController copy constructor fields mAxisInfos
and mKinematicsModelUniqueIds are initialized with default values, instead of
the values from the original KinematicsController instance (pre).

Here is this copy constructor:

KinematicsController::KinematicsController( const KinematicsController&amp; pre )
		: ObjectTemplate&lt;COLLADA_TYPE::KINEMATICS_CONTROLLER&gt;(pre)
		, mKinematicsModelUniqueIds(UniqueIdArray::OWNER)
		, mAxisInfos(AxisInfoArray::OWNER)
		, mLinearMotionProfile(pre.mLinearMotionProfile)
		, mAngularMotionProfile(pre.mAngularMotionProfile)
	{
	   

	}

solution I guess is easy, just add following lines in the copy constructor:

pre.mKinematicsModelUniqueIds.cloneArray(mKinematicsModelUniqueIds);
pre.mAxisInfos.cloneArray(mAxisInfos);

as it is done in KinematicsController::operator=( const KinematicsController&amp; pre ) method.

best regards,
Alexey<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=165</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
