### ISSUE TITLE
<texture> in <diffuse> causes abort of parsing

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#92]
<b>What steps will reproduce the problem?</b>
1. Load .dae with &lt;texture&gt; inside &lt;diffuse&gt;
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
I expect the document to be properly parsed. Instead I see abortion of the parse process on the first occurrence.

<b>What version of the product are you using? On what operating system?</b>
r839

<b>Please provide any additional information below.</b>

See bug report attachments in http://projects.blender.org/tracker/?func=detail&amp;aid=27776&amp;group_id=9&amp;atid=498 and http://projects.blender.org/tracker/?func=detail&amp;aid=28143&amp;group_id=9&amp;atid=498

Report #27776 contains 1.DAE. This file causes in the validator the message:

Sax FWL Error: Texture with sid &quot;Map__4-image&quot; not found in effect with id &quot;textures_human_skin_dark-fx&quot;.

<b>If possible, please provide a sample file that can be used to reproduce the</b>
<b>problem.</b>

<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=170</p><hr/><h2>earlier comments</h2>
<p><strong>aaronfli...@gmail.com said, at 2012-01-21T14:59:05.000Z:</strong></p>
<p>Any progress on this issue? I can also provide a sample if needed.</p>

**Comment by gaiaclary** [comment]
Does it make sense to treat this as a warning instead of aborting the parsing of this object?

**Comment by RemiArnaud** [comment]
it is not always possible to recover from parsing invalid / broken files.
Also the side effects of recovery is not easily predictable. 
So by default its the right behavior to reject invalid content.

This said I can imagine an option could be added to recover from invalid content and print warning instead. I'll go ahead and close this bug as openCOLLADA behavior is as expected. 

Open to a PR with 'optional automatic recovery from invalid documents' contribution...
