### ISSUE TITLE
r846 UTF convertion functionality fails compilation on Linux (possibly OS X to)

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#93]
<b>What steps will reproduce the problem?</b>
1. checkout r846 on linux
2. try to compile
3. opencollada/common/libBuffer/src/CommonCharacterBuffer.cpp:18:24: fatal error: ConvertUTF.h: No such file or directory
compilation terminated.

<b>What is the expected output? What do you see instead?</b>
UTF16 to UTF8 conversion headers not present on linux, also they are not needed. not sure but compilation does not work with r846. I also think it wont work on OS X or any non windows platform for that matter.

<b>What version of the product are you using? On what operating system?</b>
opencollada r846. On Ubuntu 11.10, gcc 4.6.1 

<b>Please provide any additional information below.</b>

<b>If possible, please provide a sample file that can be used to reproduce the</b>
<b>problem.</b>

<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=171</p><hr/><h2>earlier comments</h2>
<p><strong>Alexey.Z...@gmail.com said, at 2011-09-08T19:39:26.000Z:</strong></p>
<p>Hi. I just got similar problem.

here is what you can do

Solution: add include path to UTF cmake
 - open ./Externals/UTF/CMakeLists.txt
 - add ${libUTF_include_dirs} global variable to INCLUDE_DIRECTORIES
 - open main CMakeLists.txt
 - change the order of subproject compilation, UTF should be before libBuffer. correct order: ADD_SUBDIRECTORY(${EXTERNAL_LIBRARIES}/UTF)
ADD_SUBDIRECTORY(${EXTERNAL_LIBRARIES}/MathMLSolver)
ADD_SUBDIRECTORY(common/libftoa)
ADD_SUBDIRECTORY(common/libBuffer)	</p><p><strong>Alexey.Z...@gmail.com said, at 2011-09-08T21:25:35.000Z:</strong></p>
<p>hi. I spent some time fixing issues in linux. here what i got http://code.google.com/p/opencollada/issues/detail?id=172&colspec=ID%20Defect%20Type%20Status%20Priority%20Owner%20Summary</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
