### ISSUE TITLE
(enhancement) gentoo live ebuild

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#95]
(put here in lack of a better place)

for the gentoo users out there:

just wanted to share a live ebuild for opencollada i put together for my own development purposes:
http://code.google.com/p/mistafunk-gentoo-overlay/source/browse/#git%2Fmedia-libs%2Fopencollada<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=175</p><hr/><h2>earlier comments</h2>
<p><strong>ideasma...@gmail.com said, at 2011-10-14T01:08:22.000Z:</strong></p>
<p>You may want to update this since CMake now has a make install target.</p><p><strong>simon.ha...@gmail.com said, at 2011-10-14T08:00:44.000Z:</strong></p>
<p>thanks for this, appreciated. i updated the ebuild.
maybe it would be useful if the makefile also installs bin/OpenCOLLADAValidator?</p><p><strong>RoamingA...@gmail.com said, at 2011-10-18T03:47:14.000Z:</strong></p>
<p>Here is a patch to install the Validator. If you want you could disregard this and create a macro like you have to the libraries. </p><p><strong>simon.ha...@gmail.com said, at 2011-10-18T14:37:40.000Z:</strong></p>
<p>thanks. i'll keep the macro in the ebuild until the validator is installed by default.</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
