### ISSUE TITLE
fseeko64/ftello64 not available on osx

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#96]
the following patch was necessary to get the current trunk compiling on osx (gcc version 4.2.1 (Apple Inc. build 5666))&quot;

sed -i -e s/ftello64/ftell/g trunk/common/libBuffer/src/CommonFWriteBufferFlusher.cpp
sed -i -e s/fseeko64/fseek/g trunk/common/libBuffer/src/CommonFWriteBufferFlusher.cpp

<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=177</p><hr/><h2>earlier comments</h2>
<p><strong>simon.ha...@gmail.com said, at 2011-10-24T15:00:55.000Z:</strong></p>
<p>this was on the latest osx snow leopard, i should add</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
