### ISSUE TITLE
Unexpected removal of unused joint's data (joint name and joint indexes)

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCOLLADA#99]
<b>What steps will reproduce the problem?</b>
1. Create model.
2. Create joints, weight map and animation in MAYA.
3. export data via opencollada.

<b>What is the expected output? What do you see instead?</b>

In &lt;library_controller&gt;-&lt;controller&gt;-&lt;skin&gt;-&lt;source&gt;-&lt;Name array&gt;,
some of un-referrenced-joints by weight-map is removed from this list.
Also, joint-index of vertex attribute is changed.
I expected raw joint-indexes.

<b>What version of the product are you using? On what operating system?</b>
Windows7 64bit
MAYA2009
OpenCollada 1.3.0 2011-01-31

<b>Please provide any additional information below.</b>
FCOLLADA provides raw joint-indexes. FCOLLADA does not remove any joint-index.
I can understand if exporter removes some joints data, file-size will be reduced.
But developer sometimes would like to treat animation data with fixed joint-index data.
If it's possible, I wish open collada exporter does not remove unused joint-indexes.
Or, I wish this could be selectable in export option.
Remove unused joints, or not.

If possible, please provide a sample file that can be used to reproduce the problem.

<p>Migrated from http://code.google.com/p/opencollada/issues/detail?id=180</p>

**Comment by RemiArnaud** [comment]
old request, closing as probably not relevant anymore.
Please re-open if you still want this.
